import {publicDocument,positionFor} from '../core/operations';
import {parseDocument,type Project,type ProjectView} from '../core/model';
export const xml=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export function bounds(view:ProjectView){const points=view.nodeIds.map(id=>positionFor(view,id));const x=Math.min(0,...points.map(p=>p.x))-30,y=Math.min(0,...points.map(p=>p.y))-30;return{x,y,width:Math.max(300,...points.map(p=>p.x+250))-x+30,height:Math.max(150,...points.map(p=>p.y+120))-y+30};}
export function svgDiagram(input:Project,viewId=input.rootViewId,metadata=true):string{
 const d=publicDocument(input),v=d.views.find(v=>v.id===viewId)??d.views.find(v=>v.id===d.rootViewId)!,b=bounds(v),offsetY=86;
 const nodes=d.nodes.filter(n=>v.nodeIds.includes(n.id));
 const lines=d.edges.filter(e=>v.edgeIds.includes(e.id)).map(e=>{const s=positionFor(v,e.source),t=positionFor(v,e.target),forward=t.x>s.x;const x1=s.x+220,y1=s.y+50,x2=t.x,y2=t.y+50;const path=forward?`M ${x1} ${y1} C ${x1+55} ${y1}, ${x2-55} ${y2}, ${x2} ${y2}`:`M ${s.x+110} ${s.y+100} L ${s.x+110} ${s.y+138} L ${t.x+110} ${s.y+138} L ${t.x+110} ${t.y}`;return`<path d="${path}" fill="none" stroke="#6d7f96" stroke-width="2" ${e.kind==='control'?'stroke-dasharray="5 5"':''} marker-end="url(#arrow)"/><text x="${forward?(x1+x2)/2:s.x+110}" y="${forward?(y1+y2)/2-9:s.y+131}" text-anchor="middle" fill="#45556d" font-size="10">${xml(e.label.slice(0,36))}</text>`;}).join('');
 const boxes=nodes.map(n=>{const p=positionFor(v,n.id);return`<g data-node-id="${xml(n.id)}"><rect x="${p.x}" y="${p.y}" width="220" height="100" rx="12" fill="#ffffff" stroke="#cbd5e1"/><rect x="${p.x}" y="${p.y+12}" width="4" height="28" rx="2" fill="#2563eb"/><text x="${p.x+16}" y="${p.y+22}" font-size="10" fill="#52647a">${xml(n.provider.toUpperCase())}</text><text x="${p.x+16}" y="${p.y+44}" font-size="14" font-weight="600" fill="#16263d">${xml(n.label.length>25?n.label.slice(0,24)+'…':n.label)}</text><text x="${p.x+16}" y="${p.y+64}" font-size="10" fill="#52647a">${xml(n.summary.length>35?n.summary.slice(0,34)+'…':n.summary)}</text><text x="${p.x+16}" y="${p.y+85}" font-size="10" fill="#2563eb">${xml(n.childViewId?'Open subdiagram':n.blockIds.length?`${n.blockIds.length} evidence block(s)`:'Component')}</text></g>`;}).join('');
 return`<svg xmlns="http://www.w3.org/2000/svg" width="${b.width}" height="${b.height+offsetY+32}" viewBox="0 0 ${b.width} ${b.height+offsetY+32}" role="img" aria-label="${xml(v.title)}"><title>${xml(v.title)}</title>${metadata?`<metadata id="diagramcloud-document">${xml(JSON.stringify(d))}</metadata>`:''}<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#6d7f96"/></marker></defs><rect width="100%" height="100%" fill="#f8fafc"/><g font-family="Arial, sans-serif"><text x="30" y="30" fill="#64748b" font-size="11">DIAGRAMCLOUD / ${xml(d.category.toUpperCase())}</text><text x="30" y="59" fill="#16263d" font-size="20" font-weight="600">${xml(v.title.slice(0,75))}</text><g transform="translate(${-b.x},${offsetY-b.y})">${lines}${boxes}</g><text x="30" y="${b.height+offsetY+16}" fill="#64748b" font-size="10">Static explanatory view · No live telemetry · Details retained in DiagramCloud metadata</text></g></svg>`;
}
/** Only our own metadata is a diagram document; arbitrary SVG is not a graph import. */
export function documentFromSvg(raw:string):Project{
 if(new TextEncoder().encode(raw).length>16*1024*1024)throw new Error('SVG exceeds 16 MiB');
 const match=raw.match(/<metadata\s+id=["']diagramcloud-document["']\s*>([\s\S]*?)<\/metadata>/i);
 if(!match)throw new Error('No DiagramCloud metadata. Import this SVG as an image instead.');
 const decoded=match[1].replace(/&(amp|lt|gt|quot|apos);/g,(_,key:string)=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[key]!));
 return parseDocument(decoded);
}
export function mermaidDiagram(input:Project,viewId=input.rootViewId):string{const d=publicDocument(input),v=d.views.find(v=>v.id===viewId)??d.views[0],ids=new Map(v.nodeIds.map((id,i)=>[id,`n${i}`]));const label=(s:string)=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/[\r\n]/g,' ').replace(/</g,'&lt;').replace(/>/g,'&gt;');return['flowchart LR','  %% DiagramCloud: current view only; evidence and hierarchy remain in JSON.',...d.nodes.filter(n=>v.nodeIds.includes(n.id)).map(n=>`  ${ids.get(n.id)}["${label(n.label)}"]`),...d.edges.filter(e=>v.edgeIds.includes(e.id)).map(e=>`  ${ids.get(e.source)} -->|"${label(e.label)}"| ${ids.get(e.target)}`)].join('\n');}
