import {publicDocument} from '../core/operations';
import type {Project} from '../core/model';
import {svgDiagram,xml} from './diagram';
import {noIcons,type IconData} from './iconData';
const scriptJson=(value:unknown)=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
/** Standalone, read-only public portfolio: no CDN, service, account or framework required. */
export function portfolioHtml(input:Project,icons:IconData=noIcons):string{
 const d=publicDocument(input),diagrams=Object.fromEntries(d.views.map(v=>[v.id,svgDiagram(d,v.id,false,icons)]));
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>${xml(d.title)} | DiagramCloud portfolio</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f9;color:#1d2b42;font:15px/1.6 system-ui,sans-serif}header{padding:30px 5vw 22px;background:#fff;border-bottom:1px solid #dfe5ee}header small{letter-spacing:2px;color:#526c94}h1{font-size:32px;line-height:1.2;margin:12px 0}h2{font-size:20px}h3{font-size:17px}p{white-space:pre-wrap}header p{max-width:900px;color:#58667c}main{display:grid;grid-template-columns:310px minmax(0,1fr);gap:22px;margin:24px 4vw}aside{align-self:start;position:sticky;top:20px;background:white;border:1px solid #dfe5ee;border-radius:14px;padding:20px;max-height:90vh;overflow:auto}section.view{background:white;border:1px solid #dfe5ee;border-radius:14px;margin-bottom:20px;overflow:hidden}section.view h2,section.view>p{padding:0 22px}section.view>p{color:#5d6c81;font-size:13px}svg{width:100%;height:auto;max-height:460px;display:block}g[data-node-id]{cursor:pointer}g[data-node-id]:hover>rect:first-child,g[data-node-id]:focus>rect:first-child{stroke:#2563eb;stroke-width:3}button{border:1px solid #bdc9da;background:#fff;color:#193f78;border-radius:7px;padding:8px 13px;cursor:pointer;font:inherit}button:hover{background:#eef3fc}button:disabled{opacity:.4}button:focus-visible,a:focus-visible,g:focus-visible{outline:3px solid #2563eb;outline-offset:2px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.story{background:#eaf0fc;padding:14px 20px;border-radius:10px;margin-bottom:20px}.muted,small{color:#64748b}article{border-top:1px solid #e4e8ee;margin-top:16px;padding-top:4px}pre{padding:12px;background:#102039;color:#dfebff;overflow:auto;font:12px/1.6 ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere;border-radius:8px}table{border-collapse:collapse;width:100%;font-size:12px;display:block;overflow:auto}td,th{border-bottom:1px solid #e1e6ee;text-align:left;padding:8px;vertical-align:top}th{background:#f1f4f9}img{max-width:100%;height:auto;border-radius:8px}a{color:#245bc0}.badge{font-size:11px;letter-spacing:.7px;text-transform:uppercase;color:#637592}footer{padding:20px 5vw;color:#64748b;font-size:12px}@media(max-width:800px){main{grid-template-columns:1fr}aside{position:static;max-height:none}}@media print{body{background:white}header{padding:12px}.toolbar,.story button{display:none}main{display:block;margin:0}aside{position:static;max-height:none;border:0}section.view{break-inside:avoid}svg{max-height:none}footer{font-size:9px}}
</style></head><body><header><small>DIAGRAMCLOUD / INTERACTIVE PROJECT PORTFOLIO</small><h1>${xml(d.title)}</h1><p>${xml(d.summary)}</p><div class="toolbar"><button id="reset">Architecture overview</button><button id="previous">Previous step</button><button id="next">Next step</button><button id="print">Print / save PDF</button><span class="muted">Click a component to explore its work.</span></div></header><main><aside id="details" aria-label="Component evidence"></aside><div><div id="story" class="story" aria-live="polite"></div><div id="views"></div></div></main><footer>${xml(d.provenance)}<br>Public, static, read-only export. No live telemetry, code execution, tracking or network requests.</footer><script>
const doc=${scriptJson(d)};
const diagrams=${scriptJson(diagrams)};
let path=[doc.rootViewId],selected=null,step=-1;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
function pathTo(target,current=doc.rootViewId,seen=[]){if(current===target)return seen.concat(current);if(seen.includes(current))return null;const view=doc.views.find(v=>v.id===current);for(const node of doc.nodes.filter(n=>view.nodeIds.includes(n.id)&&n.childViewId)){const found=pathTo(target,node.childViewId,seen.concat(current));if(found)return found;}return null;}
function evidence(){const pane=document.getElementById('details');pane.replaceChildren();const node=doc.nodes.find(n=>n.id===selected);pane.append(el('div',node?node.provider:'PROJECT CONTEXT','badge'),el('h2',node?node.label:'Architecture → task → evidence'),el('p',node?node.summary:doc.summary));if(node&&node.role)pane.append(el('h3','My contribution'),el('p',node.role));if(!node){pane.append(el('p','Select a component. Its subdiagram opens below the architecture; code, tables and explanations appear here.','muted'));return;}
 for(const block of doc.blocks.filter(b=>node.blockIds.includes(b.id))){const a=el('article');a.append(el('h3',block.title),el('small',block.provenance,'badge'));if(block.type==='text')a.append(el('p',block.text));if(block.type==='code')a.append(el('pre',block.code));if(block.type==='table'){const table=el('table'),thead=el('thead'),head=el('tr');block.columns.forEach(c=>head.append(el('th',c)));thead.append(head);table.append(thead);const body=el('tbody');block.rows.forEach(row=>{const tr=el('tr');row.forEach(c=>tr.append(el('td',c===null?'—':c)));body.append(tr);});table.append(body);a.append(table);}if(block.type==='image'){const asset=doc.assets.find(a=>a.id===block.assetId);if(asset){const image=el('img');image.src=asset.data;image.alt=block.caption||block.title;a.append(image,el('p',block.caption),el('small',asset.rights));}}if(block.type==='metrics')block.items.forEach(i=>a.append(el('h3',i.value+' · '+i.label),el('p',i.note)));pane.append(a);}
 const refs=new Set(node.sourceIds.concat(doc.blocks.filter(b=>node.blockIds.includes(b.id)).flatMap(b=>b.sourceIds)));if(refs.size){pane.append(el('h3','Sources'));doc.sources.filter(s=>refs.has(s.id)).forEach(s=>{const a=s.url?el('a',s.title):el('span',s.title);if(s.url){a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';}pane.append(a,el('p',s.location,'muted'));});}}
function render(){const container=document.getElementById('views');container.replaceChildren();path.forEach((id,level)=>{const view=doc.views.find(v=>v.id===id);if(!view)return;const section=el('section',undefined,'view');section.append(el('h2',(level?'↳ ':'')+view.title),el('p',view.description));const canvas=el('div');canvas.innerHTML=diagrams[id];canvas.querySelectorAll('[data-node-id]').forEach(g=>{const node=doc.nodes.find(n=>n.id===g.getAttribute('data-node-id'));g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',node.label);const activate=()=>{selected=node.id;path=path.slice(0,level+1);if(node.childViewId)path.push(node.childViewId);step=-1;render();};g.onclick=activate;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}};if(node.id===selected){g.querySelector('rect').setAttribute('stroke','#2563eb');g.querySelector('rect').setAttribute('stroke-width','3');}});section.append(canvas);container.append(section);});evidence();const story=document.getElementById('story');story.textContent=step>=0?(step+1)+' / '+doc.story.length+' · '+doc.story[step].title+' — '+doc.story[step].narration:'Explore freely, or use Next step for the guided interview narrative.';document.getElementById('previous').disabled=step<=0;document.getElementById('next').disabled=!doc.story.length||step>=doc.story.length-1;}
function go(index){if(index<0||index>=doc.story.length)return;step=index;const s=doc.story[index];path=pathTo(s.viewId)||[s.viewId];selected=s.nodeId||null;render();}
document.getElementById('reset').onclick=()=>{path=[doc.rootViewId];selected=null;step=-1;render();};document.getElementById('previous').onclick=()=>go(step-1);document.getElementById('next').onclick=()=>go(step+1);document.getElementById('print').onclick=()=>window.print();render();
</script></body></html>`;
}
