import {publicDocument,positionFor} from '../core/operations';
import type {Project,EvidenceBlock} from '../core/model';
import {bounds} from './diagram';
function wrapped(text:string,width:number):string[]{return text.split('\n').flatMap(line=>{if(!line)return [''];const words=line.split(' '),lines:string[]=[];let current='';for(const word of words){if(current&&(current+' '+word).length>width){lines.push(current);current=word;}else current+=(current?' ':'')+word;}if(current)lines.push(current);return lines.flatMap(l=>l.length>width?l.match(new RegExp(`.{1,${width}}`,'g'))??['']:[l]);});}
function caption(text:string,width:number,lines:number){const chunks=wrapped(text,width);return chunks.length<=lines?chunks.join('\n'):chunks.slice(0,lines).join('\n').slice(0,-1)+'…';}
function textOf(block:EvidenceBlock):string{if(block.type==='text')return block.text;if(block.type==='code')return block.code;if(block.type==='metrics')return block.items.map(i=>`${i.label}: ${i.value}\n${i.note}`).join('\n\n');return '';}
/** Native PowerPoint shapes, text and tables. This browser exporter does not rasterize diagrams. */
export async function exportPptx(input:Project):Promise<void>{
 const d=publicDocument(input),attached=new Set(d.nodes.flatMap(n=>n.blockIds)),blocks=d.blocks.filter(b=>attached.has(b.id));
 const estimate=2+d.views.length+blocks.reduce((sum,b)=>sum+(b.type==='table'?Math.max(1,Math.ceil(b.rows.length/12)):b.type==='image'?1:Math.max(1,Math.ceil(wrapped(textOf(b),95).length/(b.type==='code'?23:18)))),0);
 if(estimate>180)throw new Error('This project would create more than 180 slides. Export a smaller public project or use HTML.');
 const {default:PptxGenJS}=await import('pptxgenjs');const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author=d.author||'DiagramCloud';pptx.subject=d.summary;pptx.title=d.title;pptx.company='DiagramCloud';pptx.lang='en-GB';pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'en-GB'};
 const width=40/3,shape=pptx.ShapeType;
 const sourceNotes='[Sources]\n'+d.sources.map(s=>`${s.title}\n${s.location}${s.url?'\n'+s.url:''}`).join('\n\n')+'\n[/Sources]';
 function base(title:string,subtitle:string){const slide=pptx.addSlide();slide.background={color:'F5F7FB'};slide.addText('DIAGRAMCLOUD / PROJECT PORTFOLIO',{x:.6,y:.28,w:12,h:.25,fontSize:10,color:'58718F',charSpacing:2,margin:0});slide.addText(caption(title,74,2),{x:.6,y:.8,w:12.1,h:.68,fontSize:title.length>70?22:27,bold:true,color:'172C48',margin:0});slide.addText(caption(subtitle,145,2),{x:.6,y:1.57,w:12.1,h:.48,fontSize:12,color:'536780',margin:0});slide.addText('Public export · Source labels retained · No live telemetry',{x:.6,y:7.13,w:12.1,h:.18,fontSize:9,color:'6F8197',margin:0});slide.addNotes([title,subtitle,d.provenance,sourceNotes]);return slide;}
 const cover=base(d.title,d.summary);cover.addText('Architecture. The work behind it. The evidence.',{x:.6,y:2.45,w:11.8,h:1.05,fontSize:32,color:'254E88',bold:true,margin:0});cover.addText(d.author,{x:.6,y:3.8,w:11.8,h:.45,fontSize:20,color:'172C48',margin:0});cover.addText(caption(d.provenance,130,6),{x:.6,y:4.55,w:11.8,h:1.35,fontSize:13,color:'536780',margin:0});cover.addText(caption(d.tags.join('  /  '),145,2),{x:.6,y:6.25,w:11.8,h:.45,fontSize:12,color:'536780',margin:0});
 const slideNumbers=new Map(d.views.map((v,i)=>[v.id,i+2]));
 for(const view of d.views){const slide=base(view.title,view.description),b=bounds(view),scale=Math.min((width-1.2)/b.width,4.6/b.height),left=(width-b.width*scale)/2,top=2.2;const position=(id:string)=>{const p=positionFor(view,id);return{x:left+(p.x-b.x)*scale,y:top+(p.y-b.y)*scale};};
  for(const e of d.edges.filter(e=>view.edgeIds.includes(e.id))){const s=position(e.source),t=position(e.target),x1=s.x+220*scale,y1=s.y+50*scale,x2=t.x,y2=t.y+50*scale;slide.addShape(shape.line,{x:Math.min(x1,x2),y:Math.min(y1,y2),w:Math.max(.001,Math.abs(x2-x1)),h:Math.max(.001,Math.abs(y2-y1)),flipH:x1>x2,flipV:y1>y2,line:{color:'8FA2BA',width:1.5,beginArrowType:'none',endArrowType:'triangle',dashType:e.kind==='control'?'dash':'solid'}});slide.addText(caption(e.label,32,1),{x:Math.min(x1,x2),y:(y1+y2)/2-.2,w:Math.max(.6,Math.abs(x2-x1)),h:.18,fontSize:8,color:'536780',align:'center',margin:0});}
  for(const n of d.nodes.filter(n=>view.nodeIds.includes(n.id))){const p=position(n.id),w=220*scale,h=100*scale;slide.addShape(shape.roundRect,{x:p.x,y:p.y,w,h,rectRadius:.12,line:{color:'CAD5E4',width:1},fill:{color:'FFFFFF'}});slide.addText(caption(n.provider.toUpperCase(),30,1),{x:p.x+.12,y:p.y+.08,w:Math.max(.01,w-.24),h:h*.17,fontSize:Math.min(9,scale*1150),color:'58718F',margin:0});slide.addText(caption(n.label,25,2),{x:p.x+.12,y:p.y+h*.3,w:Math.max(.01,w-.24),h:h*.3,fontSize:Math.min(14,scale*1650),bold:true,color:'172C48',margin:0,hyperlink:n.childViewId?{slide:slideNumbers.get(n.childViewId)}:undefined});slide.addText(caption(n.summary,36,2),{x:p.x+.12,y:p.y+h*.66,w:Math.max(.01,w-.24),h:h*.28,fontSize:Math.min(9,scale*1100),color:'536780',margin:0});}
  slide.addNotes(d.nodes.filter(n=>view.nodeIds.includes(n.id)).map(n=>`${n.label}\n${n.summary}\n${n.role}`));const narration=d.story.filter(s=>s.viewId===view.id).map(s=>`${s.title}: ${s.narration}`);if(narration.length)slide.addNotes(narration);
 }
 for(const b of blocks){const subtitle=d.nodes.filter(n=>n.blockIds.includes(b.id)).map(n=>n.label).join(' / ')+` | ${b.provenance}`;
  if(b.type==='image'){const asset=d.assets.find(a=>a.id===b.assetId);if(asset){const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('Cannot decode an evidence image'));image.src=asset.data;});const ratio=image.width/image.height,maxW=11.9,maxH=3.8,w=Math.min(maxW,maxH*ratio),h=w/ratio;const slide=base(b.title,subtitle);slide.addImage({data:asset.data,x:(width-w)/2,y:2.25+(maxH-h)/2,w,h});slide.addText(caption(b.caption+'\n'+asset.rights,145,4),{x:.7,y:6.2,w:11.9,h:.65,fontSize:10,color:'536780',margin:0});}continue;}
  if(b.type==='table'){for(let start=0;start<Math.max(1,b.rows.length);start+=12){const slide=base(b.title+(start?` (continued ${start+1})`:''),subtitle);slide.addTable([b.columns,...b.rows.slice(start,start+12).map(row=>row.map(c=>c===null?'—':caption(String(c),55,3)))],{x:.65,y:2.25,w:12.05,border:{type:'solid',color:'DCE3ED',pt:.5},fontSize:b.columns.length>7?8:11,color:'243B58',fill:'FFFFFF',margin:4,rowH:.3,autoPage:false});slide.addNotes([JSON.stringify({columns:b.columns,rows:b.rows.slice(start,start+12)})]);}continue;}
  const lines=wrapped(textOf(b),95),size=b.type==='code'?23:18;for(let start=0;start<Math.max(1,lines.length);start+=size){const slide=base(b.title+(start?' (continued)':''),subtitle);slide.addText(lines.slice(start,start+size).join('\n'),{x:.8,y:2.35,w:11.7,h:4.35,fontSize:b.type==='code'?12:16,fontFace:b.type==='code'?'Consolas':'Aptos',color:'243B58',valign:'top',margin:0,paraSpaceAfter:0});}
 }
 if(d.sources.length){const lines=wrapped(d.sources.map(s=>`${s.title}\n${s.location}${s.url?'\n'+s.url:''}`).join('\n\n'),135);for(let start=0;start<lines.length;start+=23){const slide=base('Sources and provenance','Source-derived descriptions and synthetic teaching material are distinct.');slide.addText(lines.slice(start,start+23).join('\n'),{x:.7,y:2.25,w:11.9,h:4.5,fontSize:12,color:'536780',valign:'top',margin:0});}}
 await pptx.writeFile({fileName:`${d.id}.pptx`});
}
