import {test,expect} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import JSZip from 'jszip';
import {documentSchema} from '../../src/core/model';
import {customIconData} from '../helpers/customIcon';
test('malformed optional artwork falls back while valid PNG JPEG WebP retain 4:1 native deck aspect',async({page})=>{
 mkdirSync('test-results/custom-icons',{recursive:true});await page.goto('/');const formats=await page.evaluate(async png=>{const image=new Image();image.src=png;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d')!.drawImage(image,0,0);return ['png','jpeg','webp'].map(format=>({format,data:canvas.toDataURL('image/'+format)}));},customIconData());
 const ids=[...formats.map(f=>f.format),'malformed'],doc=documentSchema.parse({schemaVersion:1,id:'synthetic-format-fallback-browser',title:'Synthetic formats and fallback',rootViewId:'root',nodes:ids.map(id=>({id,label:'Synthetic '+id,icon:'generic-api',customIconAssetId:id})),edges:[],views:[{id:'root',title:'Synthetic raster availability',nodeIds:ids,positions:Object.fromEntries(ids.map((id,i)=>[id,{x:(i%2)*300,y:Math.floor(i/2)*160}]))}],assets:[...formats.map(f=>({id:f.format,name:'Original synthetic '+f.format,data:f.data,rights:'Original synthetic four-band fixture; MIT.'})),{id:'malformed',name:'Synthetic unavailable artwork',data:'data:image/png;base64,AAAA',rights:'Original synthetic malformed fixture; MIT.'}]});
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();await page.getByLabel('Project JSON',{exact:true}).fill(JSON.stringify(doc));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await expect(page.getByRole('img',{name:'Synthetic unavailable artwork',exact:true})).toHaveCount(0);for(const f of formats){const image=page.getByRole('img',{name:'Original synthetic '+f.format,exact:true});await expect(image).toBeVisible();expect(await image.evaluate((i:HTMLImageElement)=>i.naturalWidth/i.naturalHeight)).toBe(4);}
 await page.getByRole('button',{name:'Export & share',exact:true}).click();for(const [label,file] of [['SVG diagram','raster-fallback.svg'],['Editable PowerPoint','raster-fallback.pptx']]){const pending=page.waitForEvent('download');await page.getByRole('button',{name:new RegExp('^'+label)}).click();await(await pending).saveAs('test-results/custom-icons/'+file);}const svg=readFileSync('test-results/custom-icons/raster-fallback.svg','utf8');expect(svg).toContain('Synthetic malformed');expect(svg).toContain('container or dimensions unavailable');expect(svg).not.toContain('<image href="data:image/png;base64,AAAA"');expect([...svg.matchAll(/<image href=/g)]).toHaveLength(3);const zip=await JSZip.loadAsync(readFileSync('test-results/custom-icons/raster-fallback.pptx')),xml=await zip.file('ppt/slides/slide2.xml')!.async('string'),notes=await zip.file('ppt/notesSlides/notesSlide2.xml')!.async('string');const pictures=[...xml.matchAll(/<p:pic>[\s\S]*?<\/p:pic>/g)];expect(pictures).toHaveLength(3);for(const picture of pictures){const ext=/<a:ext cx="(\d+)" cy="(\d+)"/.exec(picture[0])!;expect(Number(ext[1])/Number(ext[2])).toBeCloseTo(4,2);}expect(xml).toContain('Synthetic malformed');expect(notes).toContain('container or dimensions unavailable');await page.screenshot({path:'test-results/custom-icons/raster-fallback-canvas.png',fullPage:true});
});

test('project custom artwork selection persists, preserves aspect and public privacy in offline SVG/HTML/PowerPoint',async({page,browser})=>{
 test.setTimeout(120000);mkdirSync('test-results/custom-icons',{recursive:true});
 const doc=documentSchema.parse({schemaVersion:1,id:'synthetic-browser-icons',title:'Synthetic custom icon browser',rootViewId:'root',nodes:[{id:'api',label:'Synthetic API',kind:'app',icon:'generic-api'},{id:'job',label:'Synthetic job',kind:'process',icon:'generic-job',customIconAssetId:'private-icon'}],edges:[],views:[{id:'root',title:'Synthetic icon view',nodeIds:['api','job'],edgeIds:[],positions:{api:{x:0,y:0},job:{x:300,y:0}}}],assets:[{id:'wide',name:'Synthetic wide colour bands',data:customIconData(),rights:'Original DiagramCloud synthetic fixture; MIT.',visibility:'public'},{id:'private-icon',name:'PRIVATE_CUSTOM_ASSET_NAME',data:customIconData(),rights:'PRIVATE_CUSTOM_ASSET_RIGHTS',visibility:'private'}]});
 await page.goto('/');await page.getByRole('button',{name:'JSON / AI',exact:true}).click();await page.getByLabel('Project JSON',{exact:true}).fill(JSON.stringify(doc));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Explore Synthetic API',exact:true}).click();
 await page.getByLabel('Project custom icon',{exact:true}).selectOption('wide');await page.getByRole('button',{name:'Apply component',exact:true}).click();await expect(page.getByRole('img',{name:'Synthetic wide colour bands',exact:true})).toBeVisible();expect(await page.getByRole('img',{name:'Synthetic wide colour bands',exact:true}).evaluate((i:HTMLImageElement)=>({ratio:i.naturalWidth/i.naturalHeight,fit:getComputedStyle(i).objectFit}))).toEqual({ratio:4,fit:'contain'});
 await page.goto('/?project='+doc.id);await expect(page.getByText('Local workspace ready',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Explore Synthetic API',exact:true}).click();await expect(page.getByLabel('Project custom icon',{exact:true})).toHaveValue('wide');
 await page.getByRole('button',{name:'Export & share',exact:true}).click();
 for(const [label,file] of [['SVG diagram','synthetic.svg'],['Interactive HTML','synthetic.html'],['Editable PowerPoint','synthetic.pptx']]){const promise=page.waitForEvent('download');await page.getByRole('button',{name:new RegExp('^'+label)}).click();await(await promise).saveAs('test-results/custom-icons/'+file);}
 const svg=readFileSync('test-results/custom-icons/synthetic.svg','utf8'),html=readFileSync('test-results/custom-icons/synthetic.html','utf8');for(const output of [svg,html]){expect(output).toContain('Synthetic wide colour bands');expect(output).toContain('Original DiagramCloud synthetic fixture');expect(output).not.toContain('PRIVATE_CUSTOM_ASSET_NAME');expect(output).not.toContain('PRIVATE_CUSTOM_ASSET_RIGHTS');}expect(svg).toContain('preserveAspectRatio="xMidYMid meet"');expect(svg).toContain('diagramcloud-asset-fidelity');
 const zip=await JSZip.loadAsync(readFileSync('test-results/custom-icons/synthetic.pptx'));const xml=await zip.file('ppt/slides/slide2.xml')!.async('string');expect(xml).toContain('Synthetic wide colour bands');const picture=/<p:pic>[\s\S]*?<\/p:pic>/.exec(xml)![0],ext=/<a:ext cx="(\d+)" cy="(\d+)"/.exec(picture)!;expect(Number(ext[1])/Number(ext[2])).toBeCloseTo(4,2);for(const file of Object.values(zip.files).filter(f=>/\.xml$/.test(f.name))){const text=await file.async('string');expect(text).not.toContain('PRIVATE_CUSTOM_ASSET_NAME');expect(text).not.toContain('PRIVATE_CUSTOM_ASSET_RIGHTS');}
 const offline=await browser.newContext({offline:true}),exported=await offline.newPage();let requests=0;await exported.route('**/*',r=>{requests++;return r.abort();});await exported.setContent(html);await expect(exported.getByRole('heading',{name:'Synthetic custom icon browser',exact:true})).toBeVisible();expect(await exported.locator('image').first().getAttribute('preserveAspectRatio')).toBe('xMidYMid meet');expect(requests).toBe(0);await exported.screenshot({path:'test-results/custom-icons/offline.png',fullPage:true});await offline.close();
});
