import {test,expect} from '@playwright/test';
import {resolve} from 'node:path';
test('optional actual Tree-sitter worker parses selected source offline, cancels and reviews a private projection',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Guided/}).check();await page.getByLabel('Guided project title').fill('Synthetic deep source');await page.getByLabel('Guided project steps').fill('Synthetic source root');await page.getByRole('button',{name:'Preview project',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Business overview',exact:true}).click();const panel=page.getByLabel('Deep source analysis',{exact:true});await panel.getByText('Deep source analysis · actual Tree-sitter',{exact:true}).click();await panel.getByLabel('Deep source folder',{exact:true}).setInputFiles(resolve('tests/fixtures/deep/synthetic-client'));
 let release!:()=>void;const hold=new Promise<void>(r=>{release=r;});let blocked!:()=>void;const observed=new Promise<void>(r=>{blocked=r;});await page.route('**/*.wasm',async route=>{blocked();await hold;await route.continue().catch(()=>{});});
 try{await panel.getByRole('button',{name:'Analyze source syntax',exact:true}).click();await observed;await panel.getByRole('button',{name:'Cancel deep analysis',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('cancelled');await expect(panel.getByRole('button',{name:'Review selected syntax projection',exact:true})).toHaveCount(0);}finally{release();await page.unroute('**/*.wasm');}
 await panel.getByRole('button',{name:'Analyze source syntax',exact:true}).click();await expect(panel.getByLabel('Deep syntax items',{exact:true})).toContainText('SyntheticProgram.Run');await expect(panel.getByLabel('Deep syntax items',{exact:true})).toContainText('main');
 let repeatWasmRequests=0;await page.route('**/*.wasm',async route=>{repeatWasmRequests++;await route.abort();});try{await panel.getByRole('button',{name:'Analyze source syntax',exact:true}).click();await expect(panel.getByLabel('Deep syntax items',{exact:true})).toContainText('SyntheticProgram.Run');await expect(panel.getByRole('button',{name:'Analyze source syntax',exact:true})).toBeEnabled();expect(repeatWasmRequests).toBe(0);}finally{await page.unroute('**/*.wasm');}
 const list=panel.getByLabel('Deep syntax items',{exact:true});await list.getByRole('checkbox').first().check();await panel.getByRole('button',{name:'Review selected syntax projection',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Review');await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const saved=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());expect(saved.nodes.some((n:{tags:string[];visibility:string})=>n.tags.includes('Tree-sitter')&&n.visibility==='private')).toBe(true);expect(saved.observations).toHaveLength(0);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.goto('/?project='+encodeURIComponent(saved.id));await expect(page.getByText('Local workspace ready',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const reopened=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());expect(reopened.id).toBe(saved.id);expect(reopened.nodes.filter((n:{tags:string[]})=>n.tags.includes('Tree-sitter'))).toHaveLength(2);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('tab',{name:'Portfolio',exact:true}).click();for(const node of await page.locator('.react-flow__node').all())await expect(node).not.toContainText('SyntheticProgram');expect(errors).toEqual([]);
});
