import {test,expect,type Page} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import {syntheticDeliveryProject,publicSyntheticDeliveryProject} from '../helpers/delivery';
const apply=async(page:Page)=>{await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();};
test('promotion output excludes uncited endpoint declarations with an explicit citation gap while matrix declarations survive',async({page,browser})=>{
 const doc=publicSyntheticDeliveryProject();doc.delivery!.environments.find(e=>e.id==='prod')!.sourceIds=[];await page.goto('/');await page.getByRole('button',{name:'JSON / AI',exact:true}).click();await page.getByLabel('Project JSON',{exact:true}).fill(JSON.stringify(doc));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await apply(page);await page.getByRole('button',{name:'Business overview',exact:true}).click();const panel=page.getByLabel('Environments and delivery',{exact:true});await panel.getByText('Public delivery figures',{exact:true}).click();await panel.getByLabel('Delivery figure profile',{exact:true}).selectOption('promotion');const download=page.waitForEvent('download');await panel.getByRole('button',{name:'Download delivery SVG',exact:true}).click();await(await download).saveAs('test-results/promotion-citation-gap.svg');const svg=readFileSync('test-results/promotion-citation-gap.svg','utf8');expect(svg).toContain('1 public environment declarations and 1 promotion paths excluded');expect(svg).toContain('missing public environment source citations');expect(svg).not.toContain('Synthetic production');
 const offline=await browser.newContext({offline:true}),output=await offline.newPage();await output.setContent(svg);await expect(output.getByText(/missing public environment source citations/)).toBeVisible();await output.screenshot({path:'test-results/promotion-citation-gap.png'});await offline.close();await panel.getByLabel('Delivery figure profile',{exact:true}).selectOption('environment');await expect(panel.getByRole('img',{name:'Public delivery environment figure',exact:true})).toBeVisible();await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const saved=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());expect(saved.delivery.promotions).toHaveLength(1);expect(saved.delivery.environments).toHaveLength(2);expect(saved.observations).toEqual([]);
});
test('human delivery publication choices review closure and produce useful offline environment/release/promotion figures',async({page,browser})=>{
 test.setTimeout(120000);mkdirSync('test-results/delivery-figures',{recursive:true});const doc=syntheticDeliveryProject();
 await page.goto('/');await page.getByRole('button',{name:'JSON / AI',exact:true}).click();await page.getByLabel('Project JSON',{exact:true}).fill(JSON.stringify(doc));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await apply(page);await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Business overview',exact:true}).click();const panel=page.getByLabel('Environments and delivery',{exact:true});await panel.getByText('Delivery publication choices',{exact:true}).click();
 for(const [kind,id] of [['instances','api-dev'],['instances','api-prod'],['promotions','promotion'],['applicability','not-applicable']]){await panel.getByLabel('Delivery publication type',{exact:true}).selectOption(kind);await panel.getByLabel('Delivery publication object',{exact:true}).selectOption(id);await panel.getByLabel('Delivery publication visibility',{exact:true}).selectOption('public');await panel.getByLabel('Include required declaration context and cited sources',{exact:true}).check();await panel.getByRole('button',{name:'Review delivery publication choice',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Human-selected delivery publication');await apply(page);}
 await panel.getByText('Public delivery figures',{exact:true}).click();await expect(panel.getByRole('img',{name:'Public delivery environment figure',exact:true})).toBeVisible();
 for(const profile of ['environment','release-chain','promotion']){await panel.getByLabel('Delivery figure profile',{exact:true}).selectOption(profile);const download=page.waitForEvent('download');await panel.getByRole('button',{name:'Download delivery SVG',exact:true}).click();await(await download).saveAs('test-results/delivery-figures/'+profile+'.svg');const svg=readFileSync('test-results/delivery-figures/'+profile+'.svg','utf8');expect(svg).toContain('data-delivery-profile="'+profile+'"');for(const secret of ['PRIVATE_TENANT_DECLARATION','PRIVATE_CONFIG_DECLARATION'])expect(svg).not.toContain(secret);if(profile==='environment'){expect(svg).toContain('NOT APPLICABLE');expect(svg).toContain('Runtime UNKNOWN');}if(profile==='release-chain')for(const id of ['source-revision-1','build-run-42','artifact-version-7','release-label-9'])expect(svg).toContain(id);if(profile==='promotion')expect(svg).toContain('Synthetic human approval gate');}
 const download=page.waitForEvent('download');await panel.getByRole('button',{name:'Download offline delivery HTML',exact:true}).click();await(await download).saveAs('test-results/delivery-figures/delivery.html');const html=readFileSync('test-results/delivery-figures/delivery.html','utf8'),offline=await browser.newContext({offline:true}),exported=await offline.newPage();let requests=0;await exported.route('**/*',r=>{requests++;return r.abort();});await exported.setContent(html);await expect(exported.getByRole('heading',{name:'Synthetic delivery figures · Delivery figures',exact:true})).toBeVisible();await expect(exported.locator('svg')).toHaveCount(3);expect(requests).toBe(0);await exported.screenshot({path:'test-results/delivery-figures/offline.png',fullPage:true});await offline.close();
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const saved=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());expect(saved.observations).toEqual([]);expect(saved.delivery.environments[0].bindings[0].visibility).toBe('private');expect(saved.delivery.configurations[0].visibility).toBe('private');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/delivery-figures/narrow.png',fullPage:true});
});
