import {test,expect,type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const apply=async(page:Page)=>{await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();};
async function start(page:Page){await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Guided/}).check();await page.getByLabel('Guided project title').fill('Synthetic evolution and delivery');await page.getByLabel('Guided project steps').fill('Synthetic API');await page.getByRole('button',{name:'Preview project',exact:true}).click();await apply(page);}
test('immutable snapshots and planned migration references survive review/reload without rewriting original facts',async({page})=>{
 test.setTimeout(120000);
 await start(page);const panel=page.getByLabel('Project Evolution',{exact:true});await panel.getByText('Project Evolution · compare a previous backup',{exact:true}).click();await panel.getByLabel('Snapshot label',{exact:true}).fill('Synthetic baseline');await panel.getByRole('button',{name:'Review retaining current snapshot',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Private evolution receipt');await apply(page);await expect(panel).toContainText('1 of 12 snapshots retained');
 await panel.getByLabel('Before snapshot',{exact:true}).selectOption({index:1});await expect(panel.getByLabel('Evolution diff rail')).toBeVisible();await expect(panel).toContainText('source collection time');
 await panel.getByText('Current → transition → target and rollback plan',{exact:true}).click();await panel.getByLabel('Migration plan label',{exact:true}).fill('Synthetic coexistence plan');await panel.getByLabel('target components',{exact:true}).selectOption({label:'Synthetic API'});await panel.getByLabel('target contribution and constraints',{exact:true}).fill('Author-selected future architecture; runtime unknown');await panel.getByLabel('Coexistence intent',{exact:true}).fill('Keep both designs until owner cutover review');await panel.getByLabel('Rollback intent',{exact:true}).fill('Return to planning baseline');await panel.getByRole('button',{name:'Review migration plan',exact:true}).click();await apply(page);await expect(panel).toContainText('Synthetic coexistence plan');await expect(panel.getByLabel('Before snapshot',{exact:true})).not.toHaveValue('');
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const project=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());expect(project.observations).toEqual([]);expect(project.nodes.find((n:{label:string})=>n.label==='Synthetic API')).toBeTruthy();const receipt=JSON.parse(project.blocks.filter((b:{id:string})=>b.id.startsWith('analysis-evolution-')).map((b:{code:string})=>b.code).join(''));expect(receipt.snapshots[0].label).toBe('Synthetic baseline');expect(receipt.plans[0].phases.find((p:{stage:string})=>p.stage==='target').basis).toBe('planned');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.reload();await page.locator('.project-card').filter({hasText:'Synthetic evolution and delivery'}).click();await page.getByRole('button',{name:'Business overview',exact:true}).click();await page.getByRole('tab',{name:'Edit',exact:true}).click();await panel.getByText('Project Evolution · compare a previous backup',{exact:true}).click();await expect(panel).toContainText('1 of 12 snapshots retained');await panel.getByText('Current → transition → target and rollback plan',{exact:true}).click();await expect(panel).toContainText('Keep both designs until owner cutover review');
});
test('environment authoring preserves independent release/config identities and explicit unknown/not-applicable cells',async({page})=>{
 test.setTimeout(120000);
 await start(page);const panel=page.getByLabel('Environments and delivery',{exact:true});await panel.getByText('Environments and delivery',{exact:true}).click();await panel.getByLabel('Deployment component',{exact:true}).selectOption({label:'Synthetic API'});await panel.getByLabel('Environment name',{exact:true}).fill('Synthetic development');await panel.getByLabel('Artifact version',{exact:true}).fill('artifact-1');await panel.getByLabel('Declared source revision',{exact:true}).fill('aaaaaaa');await panel.getByLabel('Build identity',{exact:true}).fill('build-42');await panel.getByLabel('Release identity',{exact:true}).fill('release-7');await panel.getByRole('button',{name:'Review delivery declaration',exact:true}).click();await apply(page);
 await panel.getByText('Source → build → artifact → release → instance',{exact:true}).click();await expect(panel).toContainText('build-42');await expect(panel).toContainText('release-7');await expect(panel).toContainText('does not prove a deployment');
 await panel.getByLabel('Environment name',{exact:true}).fill('Synthetic production');await panel.getByLabel('Declaration type',{exact:true}).selectOption('configuration');await panel.getByLabel('Configuration name',{exact:true}).fill('synthetic-preview');await panel.getByLabel('Declared configuration state',{exact:true}).selectOption('declared-disabled');await panel.getByRole('button',{name:'Review delivery declaration',exact:true}).click();await apply(page);await panel.getByText('Environment scopes and nonsecret configuration',{exact:true}).click();await expect(panel).toContainText('synthetic-preview');await expect(panel).toContainText('Values are not stored');
 await panel.getByLabel('Declaration type',{exact:true}).selectOption('not-applicable');await panel.getByLabel('Applicability reason',{exact:true}).fill('Author planning exclusion; no deployed claim');await panel.getByRole('button',{name:'Review delivery declaration',exact:true}).click();await apply(page);await expect(panel).toContainText('not-applicable');
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const doc=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());expect(doc.observations).toEqual([]);expect(doc.delivery.artifacts[0].sourceRevision).toBe('aaaaaaa');expect(doc.delivery.artifacts[0].buildId).toBe('build-42');expect(doc.delivery.releases[0].artifactIds).toContain(doc.delivery.artifacts[0].id);expect(doc.delivery.configurations[0].value).toBeUndefined();expect(doc.delivery.applicability[0].state).toBe('not-applicable');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/evolution-delivery-narrow.png',fullPage:true});
 await page.getByRole('tab',{name:'Portfolio',exact:true}).click();await expect(page.getByLabel('Project intelligence workbench')).not.toContainText('synthetic-preview');await expect(page.getByLabel('Project intelligence workbench')).not.toContainText('release-7');
});
