import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';

test('collection conflicts retain the newer row and library storage failures leave projects usable',async({page,context})=>{
 await page.goto('/');await page.getByRole('button',{name:'Business overview',exact:true}).click();const panel=page.getByLabel('Project collections and publication library');await panel.getByText('Independent project collections',{exact:true}).click();await panel.getByLabel('Collection title',{exact:true}).fill('Concurrent collection');await panel.locator('fieldset').filter({hasText:'Explicit project membership'}).getByRole('checkbox').first().check();await panel.getByRole('button',{name:'Save collection',exact:true}).click();await expect(panel).toContainText('Collection saved');
 const other=await context.newPage();await other.goto('/');await other.getByRole('button',{name:'Business overview',exact:true}).click();const second=other.getByLabel('Project collections and publication library');await second.getByText('Independent project collections',{exact:true}).click();await second.getByRole('button',{name:'Concurrent collection',exact:true}).click();
 await panel.getByLabel('Collection title',{exact:true}).fill('Newer collection');await panel.getByRole('button',{name:'Save collection',exact:true}).click();await expect(panel.getByRole('button',{name:'Newer collection',exact:true})).toBeVisible();
 await second.getByLabel('Collection title',{exact:true}).fill('Stale overwrite');await second.getByRole('button',{name:'Save collection',exact:true}).click();await expect(second.getByRole('alert')).toContainText('Another tab changed this collection');
 const stored=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('diagramcloud-library-v1',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise<unknown[]>((resolve,reject)=>{const r=db.transaction('collections').objectStore('collections').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{db.close();}});expect(stored).toHaveLength(1);expect(stored[0]).toMatchObject({title:'Newer collection',revision:1});await other.close();
 const failed=await context.newPage();await failed.addInitScript(()=>{const original=indexedDB.open.bind(indexedDB);indexedDB.open=((name:string,version?:number)=>{if(name==='diagramcloud-library-v1')throw new DOMException('Synthetic library quota failure','QuotaExceededError');return original(name,version);}) as typeof indexedDB.open;});await failed.goto('/');await failed.getByRole('button',{name:'Business overview',exact:true}).click();await expect(failed.getByLabel('Project collections and publication library').getByRole('alert')).toContainText('Synthetic library quota failure');await failed.getByRole('button',{name:'JSON / AI',exact:true}).click();expect(JSON.parse(await failed.getByLabel('Project JSON',{exact:true}).inputValue()).nodes.length).toBeGreaterThan(0);await failed.close();
});

test('start wizard is keyboard accessible and retains source, purpose and depth for the session',async({page})=>{
 await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('radio',{name:/Guided/}).focus();await page.keyboard.press('Space');await dialog.getByLabel('Analysis purpose',{exact:true}).selectOption('education');await dialog.getByLabel('Analysis depth',{exact:true}).selectOption('quick');expect(await dialog.getByText('Advanced · manual assistance',{exact:true}).evaluate(el=>(el.parentElement as HTMLDetailsElement).open)).toBe(false);await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();
 await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await expect(page.getByRole('radio',{name:/Guided/})).toBeChecked();await expect(page.getByLabel('Analysis purpose',{exact:true})).toHaveValue('education');await expect(page.getByLabel('Analysis depth',{exact:true})).toHaveValue('quick');
});
test('shared graph filters and keyboard collapse project on canvas without editing saved membership',async({page})=>{
 await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Graph/}).check();await page.getByLabel('GraphSnapshot JSON').fill(readFileSync('tests/fixtures/night4/graph-fixture.json','utf8'));await page.getByRole('button',{name:'Preview GraphSnapshot',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();
 const explorer=page.getByTestId('graph-explorer');await explorer.getByText('Perspectives and scope limits',{exact:true}).click();await explorer.getByRole('button',{name:'Work and dependencies',exact:true}).click();
 const canvas=page.getByTestId('view-graph-view-task');await canvas.getByText('Canvas filters and groups',{exact:true}).click();const original=await canvas.locator('.react-flow__node').count();expect(original).toBeGreaterThan(1);
 await canvas.getByLabel('Canvas graph state',{exact:true}).selectOption('PLANNED');await expect(canvas.locator('.react-flow__node')).toHaveCount(2);await expect(page.getByTestId('view-graph-root')).toBeVisible();
 await canvas.getByRole('button',{name:'Reset graph filters',exact:true}).click();await expect(canvas.locator('.react-flow__node')).toHaveCount(original);
 const collapse=canvas.getByRole('button',{name:/Collapse demo-group/});await collapse.focus();await page.keyboard.press('Enter');await expect(canvas.locator('.react-flow__node')).toHaveCount(1);await canvas.getByRole('button',{name:'Expand all groups',exact:true}).click();await expect(canvas.locator('.react-flow__node')).toHaveCount(original);
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const saved=JSON.parse(await page.getByLabel('Project JSON').inputValue());expect(saved.views.find((v:{id:string})=>v.id==='graph-view-task').nodeIds).toHaveLength(original);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/graph-canvas-grouped.png',fullPage:true});
});
test('collection membership and immutable curated public snapshots persist independently of project edits',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Business overview',exact:true}).click();const panel=page.getByLabel('Project collections and publication library');await panel.getByText('Independent project collections',{exact:true}).click();await panel.getByLabel('Collection title',{exact:true}).fill('Synthetic review collection');await panel.locator('fieldset').filter({hasText:'Explicit project membership'}).getByRole('checkbox').first().check();await panel.getByRole('button',{name:'Save collection',exact:true}).click();await expect(panel).toContainText('Collection saved with independent revision vectors');await panel.getByText('Curated public snapshots',{exact:true}).click();await panel.getByLabel('Publication title',{exact:true}).fill('Synthetic frozen handbook');await panel.locator('fieldset').filter({hasText:'Existing public views'}).getByRole('checkbox').first().check();await panel.getByRole('button',{name:'Save immutable public snapshot',exact:true}).click();await expect(panel).toContainText('Immutable public snapshot saved');
 await page.reload();await page.getByRole('button',{name:'Business overview',exact:true}).click();await page.getByText('Curated public snapshots',{exact:true}).click();await expect(page.getByLabel('Project collections and publication library')).toContainText('Synthetic frozen handbook');await page.getByText('Independent project collections',{exact:true}).click();await expect(page.getByLabel('Project collections and publication library')).toContainText('Synthetic review collection');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download public snapshot',exact:true}).click();const file=await download;await file.saveAs('test-results/publication-library.json');const snapshot=JSON.parse(readFileSync('test-results/publication-library.json','utf8'));expect(snapshot.document.privateNotes).toBeUndefined();expect(snapshot.digest).toMatch(/^sha256:[a-f0-9]{64}$/);expect(snapshot.viewIds).toHaveLength(1);
});
