import {test,expect,type Page} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
const fixture=()=>JSON.parse(readFileSync('tests/fixtures/night4/graph-fixture.json','utf8'));
const apply=async(page:Page)=>{await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();};
async function importGraph(page:Page,g:unknown){await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Graph/}).check();await page.getByLabel('GraphSnapshot JSON').fill(JSON.stringify(g));await page.getByRole('button',{name:'Preview GraphSnapshot',exact:true}).click();await apply(page);}
test('offline graph import, filters, supplied evidence, parent navigation, reimport, reopen and public export',async({page,browser})=>{
 await page.goto('/');await importGraph(page,fixture());const graph=page.getByTestId('graph-explorer');await expect(graph).toContainText('fixture-1');
 await page.getByLabel('Graph state',{exact:true}).selectOption('PLANNED');await expect(graph).toContainText('2 matching components');await page.getByLabel('Graph state',{exact:true}).selectOption('');
 await graph.getByRole('button',{name:'Selected example feature',exact:true}).click();await expect(page.getByLabel('Graph evidence chain')).toContainText('fixtures/declared.json');await expect(page.getByLabel('Graph evidence chain')).toContainText('Example CI observation');
 await graph.getByText('Perspectives and scope limits',{exact:true}).click();await graph.getByRole('button',{name:'Work and dependencies',exact:true}).click();await expect(page.getByTestId('view-graph-root')).toBeVisible();await expect(page.getByTestId('view-graph-view-task')).toBeVisible();
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const current=JSON.parse(await page.getByLabel('Project JSON').inputValue());const feature=current.nodes.find((n:{label:string})=>n.label==='Selected example feature');feature.label='Author caption retained';const view=current.views.find((v:{nodeIds:string[]})=>v.nodeIds.includes(feature.id));view.positions[feature.id]={x:721,y:451};await page.getByLabel('Project JSON').fill(JSON.stringify(current));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await apply(page);
 const changed=fixture();changed.generation_id='fixture-2';changed.predecessor_generation='fixture-1';changed.nodes.find((n:{id:string})=>n.id==='feature').label='Producer changed caption';changed.assertions[1].predicate='changed relation';await importGraph(page,changed);
 await expect(page.getByTestId('graph-explorer')).toContainText('fixture-2');await expect(page.getByTestId('graph-explorer')).toContainText('Author caption retained');
 await page.reload();await page.locator('.project-card').filter({hasText:'Selected GraphSnapshot'}).click();await page.getByRole('button',{name:'Business overview',exact:true}).click();await expect(page.getByTestId('graph-explorer')).toContainText('fixture-2');
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const reopened=JSON.parse(await page.getByLabel('Project JSON').inputValue());expect(reopened.views.find((v:{id:string})=>v.id===view.id).positions[feature.id]).toEqual({x:721,y:451});await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByText('Project Evolution · compare a previous backup',{exact:true}).click();await page.getByLabel('Previous project JSON',{exact:true}).setInputFiles({name:'previous.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(current))});await expect(page.getByLabel('Project Evolution',{exact:true})).toContainText('partial');await expect(page.getByLabel('Evolution diff rail')).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export public intelligence report',exact:true}).click();const file=await download;mkdirSync('test-results',{recursive:true});await file.saveAs('test-results/graph-public.html');const html=readFileSync('test-results/graph-public.html','utf8');for(const sentinel of ['Author caption retained','fixtures/declared.json','demo-private','fixture-2'])expect(html).not.toContain(sentinel);
 const offline=await browser.newContext({offline:true}),viewPage=await offline.newPage();let requests=0;await viewPage.route('**/*',r=>{requests++;return r.abort();});await viewPage.setContent(html);await expect(viewPage.getByRole('heading',{name:'Environments and artifacts',exact:true})).toBeVisible();expect(requests).toBe(0);await offline.close();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/graph-client-narrow.png',fullPage:true});
});

test('large graph browse stays transient until a bounded partial selection is reviewed',async({page})=>{
 const g=fixture();for(let i=0;i<600;i++)g.nodes.push({...g.nodes[1],id:'large-'+i,label:'Synthetic large '+i,parent_id:null});
 await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Graph/}).check();await page.getByLabel('GraphSnapshot JSON').fill(JSON.stringify(g));await page.getByRole('button',{name:'Preview GraphSnapshot',exact:true}).click();
 const table=page.getByLabel('Large snapshot table');await expect(table).toContainText('no import has been applied');await page.getByLabel('Large graph search').fill('Synthetic large 59');await table.getByRole('button',{name:'Select matching components',exact:true}).click();await table.getByRole('button',{name:'Preview selected components',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('PARTIAL');await apply(page);await expect(page.getByTestId('graph-explorer')).toContainText('11 matching components');
});
test('guided delivery declaration is reviewed, persists and leaves runtime unknown',async({page})=>{
 await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Guided/}).check();await page.getByLabel('Guided project title').fill('Synthetic delivery project');await page.getByLabel('Guided project steps').fill('Synthetic API');await page.getByRole('button',{name:'Preview project',exact:true}).click();await apply(page);
 await page.getByText('Environments and delivery',{exact:true}).click();await page.getByLabel('Deployment component',{exact:true}).selectOption({label:'Synthetic API'});await page.getByLabel('Environment name',{exact:true}).fill('Synthetic development');await page.getByLabel('Artifact version',{exact:true}).fill('candidate-1');await page.getByRole('button',{name:'Review delivery declaration',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Typed author declarations');await apply(page);
 await expect(page.getByLabel('Project intelligence workbench')).toContainText('Synthetic development');await expect(page.getByLabel('Project intelligence workbench')).toContainText('UNKNOWN');
 await page.reload();await page.locator('.project-card').filter({hasText:'Synthetic delivery project'}).click();await page.getByRole('button',{name:'Business overview',exact:true}).click();await expect(page.getByLabel('Project intelligence workbench')).toContainText('candidate-1');
 await page.getByRole('tab',{name:'Portfolio',exact:true}).click();await expect(page.getByLabel('Project intelligence workbench')).not.toContainText('Synthetic development');
});
