import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {imageManualProject} from '../helpers/manualImages';
test('saved library identities reopen independently, frozen images retain rights offline, and missing targets do not replace editable projects',async({page,browser})=>{
 const doc=imageManualProject();await page.goto('/');await page.getByRole('button',{name:'JSON / AI',exact:true}).click();await page.getByLabel('Project JSON',{exact:true}).fill(JSON.stringify(doc));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Business overview',exact:true}).click();
 const library=page.getByLabel('Project collections and publication library',{exact:true});await library.getByText('Curated public snapshots',{exact:true}).click();await library.getByLabel('Publication title',{exact:true}).fill('Synthetic frozen image handbook');await library.getByLabel('Audience',{exact:true}).fill('Synthetic reviewer');await library.getByRole('checkbox',{name:'Synthetic image flow',exact:true}).check();await library.getByRole('button',{name:'Save immutable public snapshot',exact:true}).click();await expect(library.getByRole('status')).toContainText('Immutable public snapshot saved');
 const publication=library.locator('article').filter({has:page.getByRole('heading',{name:'Synthetic frozen image handbook',exact:true})});await expect(publication).toContainText('Public document digest');await expect(publication).toContainText('Output digest');
 const download=page.waitForEvent('download');await publication.getByRole('button',{name:'Download public snapshot',exact:true}).click();await(await download).saveAs('test-results/library-image-publication.json');const frozen=JSON.parse(readFileSync('test-results/library-image-publication.json','utf8'));expect(frozen.outputBinding).toBe('bound');expect(frozen.outputDigest).toMatch(/^sha256:/);expect(JSON.stringify(frozen)).not.toContain('PRIVATE_IMAGE_');
 const publicationLink=await publication.getByRole('link',{name:'Open stable publication link',exact:true}).getAttribute('href');expect(publicationLink).toContain('publication='+frozen.id);expect(publicationLink).not.toContain('project=');
 const popupEvent=page.waitForEvent('popup');await publication.getByRole('button',{name:'Open frozen handbook',exact:true}).click();const popup=await popupEvent;await expect(popup.getByRole('heading',{name:'Synthetic frozen image handbook',exact:true})).toBeVisible();expect(popup.url()).toMatch(/^blob:/);await expect(popup.locator('.evidence-image img')).toHaveCount(1);await expect(popup.getByText('Recorded rights:',{exact:false})).toContainText('Original synthetic <rights>');await popup.close();
 const handbookDownload=page.waitForEvent('download');await publication.getByRole('button',{name:'Export curated handbook',exact:true}).click();await(await handbookDownload).saveAs('test-results/library-image-handbook.html');const html=readFileSync('test-results/library-image-handbook.html','utf8');expect(html).not.toContain('PRIVATE_IMAGE_');expect(html).toContain('Synthetic caption &lt;img onerror=&quot;bad&quot;&gt;');expect(html).toContain('Original synthetic &lt;rights&gt;');
 const offline=await browser.newContext({offline:true,viewport:{width:1000,height:900}}),output=await offline.newPage();let requests=0;await output.route('**/*',route=>{requests++;return route.abort();});await output.setContent(html);const image=output.locator('.evidence-image img');await expect(image).toBeVisible();await expect(image).toHaveJSProperty('complete',true);const dimensions=await image.evaluate((element:HTMLImageElement)=>({natural:element.naturalWidth/element.naturalHeight,rendered:element.getBoundingClientRect().width/element.getBoundingClientRect().height}));expect(dimensions.natural).toBe(4);expect(dimensions.rendered).toBeCloseTo(4,2);expect(requests).toBe(0);await output.locator('.evidence-image').screenshot({path:'test-results/library-image-evidence-offline.png'});await offline.close();
 await library.getByText('Independent project collections',{exact:true}).click();await library.getByLabel('Collection title',{exact:true}).fill('Synthetic independent collection');await library.getByRole('checkbox',{name:/Synthetic image handbook · document/}).check();await library.getByRole('button',{name:'Save collection',exact:true}).click();await expect(library.getByRole('status')).toContainText('Collection saved');const collection=library.locator('article').filter({has:page.getByRole('heading',{name:'Synthetic independent collection',exact:true})}),collectionLink=await collection.getByRole('link',{name:'Open stable collection link',exact:true}).getAttribute('href');
 const readStored=()=>page.evaluate(async(id)=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('diagramcloud-v1',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise<string>((resolve,reject)=>{const r=db.transaction('projects','readonly').objectStore('projects').get(id);r.onsuccess=()=>resolve(r.result.json);r.onerror=()=>reject(r.error);});}finally{db.close();}},doc.id),before=await readStored();
 await page.goto(publicationLink!);await expect(page.getByTestId('library-link-target')).toContainText('Linked frozen publication selected');await expect(page.locator('[data-library-target="selected"]')).toContainText('Synthetic frozen image handbook');expect(await readStored()).toBe(before);
 await page.goto(collectionLink!);await expect(page.getByTestId('library-link-target')).toContainText('Linked collection selected');await expect(page.getByLabel('Collection title',{exact:true})).toHaveValue('Synthetic independent collection');expect(await readStored()).toBe(before);
 await page.goto('/?publication=publication-unavailable');await expect(page.getByTestId('library-link-target')).toContainText('unavailable');expect(await readStored()).toBe(before);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await library.screenshot({path:'test-results/library-link-missing-narrow.png'});
});
