import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
test('logical mappings preserve parents and selected context, purpose and public redaction',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const brief={format:'diagramcloud.project-brief',version:1,project:{id:'navigation-context',title:'Synthetic navigation context'},scope:[{id:'work',title:'Declared workstream',kind:'workstream',repositoryIds:['app']},{id:'task',title:'Selected task',kind:'task',parentId:'work'}],repositories:[{id:'app',title:'Synthetic implementation',host:'local',locator:'app',revision:'a'.repeat(40)},{id:'other',title:'Unbound implementation',host:'local',locator:'other',revision:'b'.repeat(40)}]};
 await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Hybrid/}).check();await page.getByLabel('Analysis purpose',{exact:true}).selectOption('education');await page.getByLabel('Project brief JSON',{exact:true}).fill(JSON.stringify(brief));await page.getByRole('button',{name:'Preview project',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await expect(page.getByLabel('Recipe and pattern workbench').getByLabel('View purpose',{exact:true})).toHaveValue('education');
 const nav=page.getByTestId('project-navigator');await nav.getByRole('tab',{name:'Mappings',exact:true}).click();await expect(nav).toContainText('Explicit experience relation');await expect(nav).toContainText('project-brief-source');await expect(nav).not.toContainText('Unbound implementation');await nav.getByRole('button',{name:'Declared workstream',exact:true}).click();await expect(page.getByTestId('view-brief-overview')).toBeVisible();await expect(page.getByTestId('view-brief-children-work')).toBeVisible();
 await page.getByRole('button',{name:'Details panel',exact:true}).click();const context=page.getByTestId('project-context');await expect(context).toContainText('Selection: Declared workstream');await expect(context).toContainText('brief-scope-work');await context.getByRole('tab',{name:'Alternatives',exact:true}).click();await expect(context).toContainText('Code');await expect(context).toContainText('unsupported');await context.getByRole('tab',{name:'Evidence',exact:true}).click();await expect(context).toContainText('Author-supplied ProjectBrief');await context.getByText('Manual assistance',{exact:true}).click();const downloading=page.waitForEvent('download');await context.getByRole('button',{name:'Download context',exact:true}).click();const file=await downloading;await file.saveAs('test-results/selected-navigation-context.json');const selected=JSON.parse(readFileSync('test-results/selected-navigation-context.json','utf8'));expect(selected.selection.nodeId).toBe('brief-scope-work');expect(selected.components).toHaveLength(1);expect(selected.assets.requirements).toHaveLength(1);expect(selected.assets.requirements[0].nodeId).toBe('brief-scope-work');
 await nav.getByLabel('Navigation filter',{exact:true}).fill('Selected task');await expect(nav.getByRole('status')).toContainText('remains selected outside this filter');await context.getByRole('tab',{name:'Details',exact:true}).click();await expect(context).toContainText('Selection: Declared workstream');await nav.getByRole('tab',{name:'Views',exact:true}).click();await nav.getByLabel('Navigation filter',{exact:true}).fill('author-declared structure');await expect(nav.getByRole('heading',{name:'System',exact:true})).toBeVisible();await expect(nav.getByRole('button',{name:'Inside Declared workstream',exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await context.screenshot({path:'test-results/selected-context-narrow.png'});
 await page.getByRole('tab',{name:'Portfolio',exact:true}).click();await expect(context).not.toContainText('brief-scope-work');await expect(nav).not.toContainText('brief-scope-work');await expect(context).not.toContainText('Declared workstream');expect(errors).toEqual([]);
});
