import {test,expect,type Page} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const fixture=resolve('test-results/intelligence-input');
test.beforeAll(()=>{mkdirSync(fixture,{recursive:true});writeFileSync(`${fixture}/README.md`,'# Synthetic handbook\nSee [sources](sources.csv).\n[Missing](missing.md)\n');writeFileSync(`${fixture}/sources.csv`,'id,title\nsource-a,Synthetic source\n');writeFileSync(`${fixture}/notes.csv`,'id,source_ids\nnote-a,source-a\n');writeFileSync(`${fixture}/program.unknown`,'Unsupported language, deliberately no architecture inferred.');});
async function start(page:Page){await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();}
async function apply(page:Page){await expect(page.getByRole('button',{name:'Apply imported document',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();}
const brief={format:'diagramcloud.project-brief',version:1,project:{id:'journey',title:'Synthetic Guided Journey',summary:'Synthetic training project; no employer or runtime result.'},scope:[{id:'prepare',title:'Prepare data',kind:'workstream'},{id:'check',title:'Validate inputs',kind:'task',parentId:'prepare'},{id:'report',title:'Publish report',kind:'system'}],relationships:[{id:'publish',from:'check',to:'report',label:'Declared handoff',kind:'batch'}]};
test('unknown/docs-only selection has usable source outputs, private docs and persistent inventory',async({page})=>{
  await page.goto('/');await start(page);await page.getByLabel('Analysis repository folder').setInputFiles(fixture);await apply(page);
  await expect(page.getByTestId('project-overview')).toBeVisible();await page.getByRole('button',{name:'Structure',exact:true}).click();await expect(page.getByLabel('Structure output')).toContainText('program.unknown');await expect(page.getByLabel('Structure output')).toContainText('source-a');
  await page.screenshot({path:'test-results/intelligence-source.png',fullPage:true});await page.getByRole('button',{name:'Relationships',exact:true}).click();await expect(page.getByLabel('Relationships output')).toContainText('No relationship was established');
  await page.getByRole('button',{name:'Evidence / gaps',exact:true}).click();await expect(page.getByLabel('Evidence output')).toContainText('sha256:');await page.reload();await page.locator('.project-card').filter({hasText:'Selected repository analysis'}).click();await page.getByRole('button',{name:'Structure',exact:true}).click();await expect(page.getByLabel('Structure output')).toContainText('notes.csv');
  await page.getByRole('tab',{name:'Portfolio',exact:true}).click();await expect(page.getByLabel('Structure output')).not.toContainText('notes.csv');
});
test('Guided no-Git project drills to task, preserves author work on reimport and publishes offline overview',async({page,browser})=>{
  await page.goto('/');await start(page);await page.getByRole('radio',{name:/Guided/}).check();await page.getByLabel('Project brief JSON').fill(JSON.stringify(brief));await page.getByRole('button',{name:'Preview project',exact:true}).click();await apply(page);
  await page.getByTestId('project-navigator').getByRole('button',{name:'Prepare data',exact:true}).click();await expect(page.getByTestId('view-brief-overview')).toBeVisible();await expect(page.getByTestId('view-brief-children-prepare')).toBeVisible();
  await page.getByTestId('project-navigator').getByRole('button',{name:'Workspace',exact:true}).first().click();await expect(page.getByRole('dialog')).toContainText('Validate inputs');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const current=JSON.parse(await page.getByLabel('Project JSON').inputValue());current.nodes.find((n:{id:string})=>n.id==='brief-scope-prepare').label='Author-retained preparation';current.privateNotes='PRIVATE_INTELLIGENCE_SENTINEL';const node=current.nodes.find((n:{id:string})=>n.id==='brief-scope-report');node.visibility='public';node.sourceIds=[];node.summary='Author-selected public contribution.';await page.getByLabel('Project JSON').fill(JSON.stringify(current));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await apply(page);
  await start(page);await page.getByRole('radio',{name:/Guided/}).check();await page.getByLabel('Project brief JSON').fill(JSON.stringify({...brief,scope:[...brief.scope,{id:'later',title:'New declared step',kind:'component'}]}));await page.getByRole('button',{name:'Preview project',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Existing project ID');await apply(page);await expect(page.getByTestId('project-navigator')).toContainText('Author-retained preparation');
  await page.getByRole('button',{name:'Business overview',exact:true}).click();await page.screenshot({path:'test-results/intelligence-guided.png',fullPage:true});
  const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export public overview HTML',exact:true}).click();const file=await downloading;await file.saveAs('test-results/intelligence-overview.html');const html=readFileSync('test-results/intelligence-overview.html','utf8');expect(html).not.toContain('PRIVATE_INTELLIGENCE_SENTINEL');expect(html).not.toContain('Author-retained preparation');expect(html).toContain('Author-selected public contribution');
  const offline=await browser.newContext({offline:true}),view=await offline.newPage();let requests=0;await view.route('**/*',route=>{requests++;return route.abort();});await view.setContent(html);await expect(view.getByRole('heading',{name:'Steps and components'})).toBeVisible();expect(requests).toBe(0);await view.screenshot({path:'test-results/intelligence-public-offline.png',fullPage:true});await offline.close();
});
test('Hybrid keeps three explicit repositories, declared bindings, source gaps and offline asset fallback',async({page})=>{
  await page.goto('/');await start(page);await page.getByRole('radio',{name:/Hybrid/}).check();const input={...brief,relationships:[],project:{...brief.project,id:'hybrid',title:'Synthetic Hybrid Journey'},scope:[{id:'delivery',title:'Delivery workstream',kind:'workstream',repositoryIds:['app','data','docs']}],repositories:['app','data','docs'].map(id=>({id,title:`Synthetic ${id}`,host:'local',locator:id,role:id==='docs'?'documentation':'application',...(id==='app'?{revision:'aaaaaaaa'}:{})})),repositoryRelationships:[{from:'app',to:'data',label:'Author-declared input',kind:'batch'}]};await page.getByLabel('Project brief JSON').fill(JSON.stringify(input));await page.getByRole('button',{name:'Preview project',exact:true}).click();await apply(page);
  await page.getByTestId('project-navigator').getByRole('tab',{name:'Repositories',exact:true}).click();await expect(page.getByTestId('project-navigator')).toContainText('aaaaaaaa');await expect(page.getByTestId('project-navigator')).toContainText('Synthetic docs');await expect(page.getByTestId('project-navigator')).toContainText('not-scanned');await page.getByTestId('project-navigator').getByRole('button',{name:'Synthetic app',exact:true}).click();await expect(page.getByTestId('view-atlas')).toBeVisible();
  await page.getByRole('button',{name:'Project atlas',exact:true}).click();await page.getByLabel('Rescan Synthetic app',{exact:true}).setInputFiles(fixture);await apply(page);await page.getByTestId('project-navigator').getByRole('button',{name:'Synthetic app',exact:true}).click();await page.getByRole('button',{name:'Structure',exact:true}).click();await expect(page.getByLabel('Structure output')).toContainText('notes.csv');await expect(page.getByTestId('project-navigator')).not.toContainText('aaaaaaaa');await expect(page.getByTestId('project-navigator')).toContainText('Synthetic data');
  await page.getByRole('button',{name:'Details panel',exact:true}).click();await page.getByTestId('project-context').getByRole('tab',{name:'Gaps',exact:true}).click();await expect(page.getByTestId('project-context')).toContainText('Information gaps');await page.getByTestId('project-context').getByRole('tab',{name:'Assets',exact:true}).click();const downloading=page.waitForEvent('download');await page.getByTestId('project-context').getByRole('button',{name:'Download asset plan JSON',exact:true}).click();expect((await downloading).suggestedFilename()).toContain('asset-plan');await page.screenshot({path:'test-results/intelligence-hybrid.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await expect(page.getByTestId('project-context')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

