import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const commit='a'.repeat(40);
test('actual public candidates show three images, measured scores and an author-review design brief',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Business overview',exact:true}).click();await page.getByText('Figure geometry and offline quality',{exact:true}).click();await page.getByRole('button',{name:'Check selected figure geometry',exact:true}).click();await expect(page.getByLabel('Figure quality result')).toContainText('measured text boxes');await page.getByRole('button',{name:'Compare render candidates A/B/C',exact:true}).click();const comparison=page.getByLabel('Render candidate comparison');await expect(comparison.getByRole('img')).toHaveCount(3);await expect(comparison).toContainText('Scores subtract stated defect penalties');await expect(comparison).toContainText('common source-layout crossings');const downloading=page.waitForEvent('download');await comparison.getByRole('button',{name:'Download candidate A for author review',exact:true}).click();const file=await downloading;await file.saveAs('test-results/quality-candidate-a.json');const brief=JSON.parse(readFileSync('test-results/quality-candidate-a.json','utf8'));expect(brief.format).toBe('diagramcloud.design-brief');expect(brief.views).toHaveLength(1);expect(brief.nodes).toBeUndefined();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await comparison.screenshot({path:'test-results/quality-candidates-narrow.png'});
});
test('recipes expose reasons and validated profile; external receipt is reviewed and remains private',async({page})=>{
 await page.goto('/');await page.locator('.header-actions').getByRole('button',{name:'New analysis',exact:true}).click();await page.getByRole('radio',{name:/Guided/}).check();await page.getByLabel('Guided project title').fill('Synthetic verification journey');await page.getByLabel('Guided project steps').fill('Synthetic API');await page.getByRole('button',{name:'Preview project',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Business overview',exact:true}).click();const panel=page.getByLabel('Recipe and pattern workbench');await expect(panel).toContainText('Missing facts stay unknown');await panel.getByLabel('View purpose',{exact:true}).selectOption('education');await panel.getByLabel('View detail',{exact:true}).selectOption('custom');await panel.getByText('Advanced analysis parameters',{exact:true}).click();await panel.getByLabel('Preview component budget',{exact:true}).fill('21');const downloading=page.waitForEvent('download');await panel.getByRole('button',{name:'Download validated analysis profile',exact:true}).click();const download=await downloading;await download.saveAs('test-results/verification-analysis-profile.json');const profile=JSON.parse(readFileSync('test-results/verification-analysis-profile.json','utf8'));expect(profile.depth).toBe('custom');expect(profile.purpose).toBe('education');expect(profile.budgets.nodes).toBe(21);expect(profile.autonomy).toBe('review-required');
 const assetRow=panel.locator('li').filter({has:page.getByRole('button',{name:'Download recipe asset plan',exact:true})}).first(),assetDownload=page.waitForEvent('download');await assetRow.getByRole('button',{name:'Download recipe asset plan',exact:true}).click();const assetFile=await assetDownload;await assetFile.saveAs('test-results/recipe-private-assets.json');const assets=JSON.parse(readFileSync('test-results/recipe-private-assets.json','utf8'));expect(assets.scope.kind).toBe('recipe');expect(assets.scope.recipeId).toBeTruthy();expect(new Set(assets.scope.nodeIds).size).toBe(assets.scope.nodeIds.length);expect(assets.scope.options.purpose).toBe('education');const csvDownload=page.waitForEvent('download');await assetRow.getByRole('button',{name:'Download recipe asset checklist',exact:true}).click();const csv=await csvDownload;await csv.saveAs('test-results/recipe-private-assets.csv');expect(readFileSync('test-results/recipe-private-assets.csv','utf8')).toContain('Private authoring checklist; inspect before sharing');
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const current=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByText('Work and verification brief · external check review',{exact:true}).click();await page.getByLabel('Exact verification repository').fill('owner/synthetic-fixture');await page.getByLabel('Verification source commit').fill(commit);await page.getByLabel('Verification component').selectOption({label:'Synthetic API'});await page.getByRole('button',{name:'Propose NOT_RUN check',exact:true}).click();await expect(page.getByText(/Spec selected-checks · PROPOSED/)).toBeVisible();await page.getByLabel('External runner name').fill('Synthetic test runner fixture');await page.getByLabel('External run identity').fill('synthetic-run-1');
 const receipt={schema_version:1,receipt_id:'synthetic-receipt-e2e',subject:{schema_version:1,entity_id:'fixture:release',owner_app:'external-ci',entity_type:'release',local_id:'fixture'},app_id:'external-ci',product_version:'1.0',document_schema_version:1,galaxy_level:'G0',revision:{vcs:'git',repository:'owner/synthetic-fixture',commit,dirty:false},verification_level:'DECLARED',status:'passed',checks:[{check_id:'test',status:'passed',evidence_ref_ids:['evidence']}],evidence_refs:[{schema_version:1,evidence_id:'evidence',kind:'test_run',source_system:'ci',locator:{run_id:'synthetic-run'},captured_at:'2026-10-09T00:00:00Z',observed_revision:commit,visibility:'private',synthetic:false,review_state:'unreviewed'}],created_at:'2026-10-09T00:00:00Z',caveats:['Synthetic browser test fixture; not a real verification result.']};
 await page.getByLabel('Select Galaxy verification receipt').setInputFiles({name:'synthetic-receipt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...receipt,revision:{...receipt.revision,commit:'b'.repeat(40)}}))});await expect(page.getByRole('alert').filter({hasText:'differs from requested revision vector'})).toBeVisible();
 await page.getByLabel('Select Galaxy verification receipt').setInputFiles({name:'synthetic-receipt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(receipt))});await expect(page.getByRole('dialog')).toContainText('private and unreviewed');await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'JSON / AI',exact:true}).click();const stored=JSON.parse(await page.getByLabel('Project JSON',{exact:true}).inputValue());expect(stored.observations).toHaveLength(1);expect(stored.observations[0].reviewedAt).toBeUndefined();expect(stored.observations[0].visibility).toBe('private');expect(stored.observations[0].shareable).toBe(false);expect(stored.observations[0].sourceRevision).toBe(commit);expect(current.observations).toHaveLength(0);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('tab',{name:'Portfolio',exact:true}).click();await expect(page.getByLabel('Project intelligence workbench')).not.toContainText('Synthetic test runner fixture');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByLabel('Recipe and pattern workbench').screenshot({path:'test-results/recipe-workbench-narrow.png'});
});
