import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {documentSchema} from '../../src/core/model';
import JSZip from 'jszip';
for(const dense of [false,true])test('supplied signed increments '+(dense?'dense with missing values':'small')+' render a public waterfall and export a genuine picture deck',async({page})=>{
 const doc=documentSchema.parse({schemaVersion:1,id:'synthetic-waterfall-browser',title:'Synthetic signed increments',summary:'Illustrative increments; running sums are derived, never measured or causal outcomes.',rootViewId:'root',nodes:[{id:'data',label:'Illustrative supplied data',blockIds:['signed']},{id:'private',label:'PRIVATE_WATERFALL_SENTINEL',visibility:'private',blockIds:['private']}],edges:[],views:[{id:'root',title:'Supplied signed steps',nodeIds:['data','private'],positions:{data:{x:0,y:0},private:{x:300,y:0}},design:{type:'waterfall'}}],blocks:[{id:'signed',title:'Synthetic signed increment table',type:'table',columns:['Step','Delta (illustrative units)'],rows:dense?Array.from({length:24},(_,i)=>['Synthetic long category label '+i+' retained completely in the attached source evidence',i===2?null:i%3===0?-4:i%3===1?10:0]):[['Initial',10],['Reduction',-4],['No change',0],['Increment',6]],provenance:'synthetic'},{id:'private',title:'PRIVATE_WATERFALL_BLOCK_SENTINEL',type:'table',columns:['Step','Delta'],rows:[['Private amount',999]],visibility:'private'}]});
 await page.goto('/');await page.getByRole('button',{name:'JSON / AI',exact:true}).click();await page.getByLabel('Project JSON',{exact:true}).fill(JSON.stringify(doc));await page.getByRole('button',{name:'Validate JSON',exact:true}).click();await page.getByRole('button',{name:'Apply imported document',exact:true}).click();await expect(page.getByText('Saved locally',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Diagram Design',exact:true}).click();const preview=page.getByTestId('design-preview');await expect(preview.locator('img.design-figure')).toHaveAttribute('data-design-type','waterfall');await expect.poll(()=>preview.locator('img.design-figure').evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth)).toBeGreaterThan(500);await preview.screenshot({path:'test-results/waterfall-'+(dense?'dense':'small')+'-preview.png'});await page.getByRole('button',{name:'Business overview',exact:true}).click();await page.getByText('Figure geometry and offline quality',{exact:true}).click();await page.getByRole('button',{name:'Check selected figure geometry',exact:true}).click();const result=page.getByLabel('Figure quality result');await expect(result).toContainText('0 defects');await expect(result).toContainText(dense?'PARTIAL':'SEMANTICS_CHECKED');await expect(result).toContainText('waterfall-geometric-encoding: passed');
 await page.getByRole('button',{name:'Export & share',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:/Diagram Design deck \(PowerPoint\)/}).click();const file=await download;await file.saveAs('test-results/waterfall-'+(dense?'dense':'small')+'-figures.pptx');const zip=await JSZip.loadAsync(readFileSync('test-results/waterfall-'+(dense?'dense':'small')+'-figures.pptx')),slideXml=(await Promise.all(Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).map(n=>zip.file(n)!.async('string')))).join('\n');expect(Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n))).toHaveLength(2);expect(slideXml).toContain('Waterfall (supplied signed increments)');expect(slideXml).not.toContain('PRIVATE_WATERFALL');expect(Object.keys(zip.files).some(n=>/^ppt\/media\/.*\.png$/.test(n))).toBe(true);
});
