import test from 'node:test';
import assert from 'node:assert/strict';
import {documentSchema} from '../src/core/model';
import {designSvg} from '../src/export/design';
import {waterfallTable,waterfallValues} from '../src/export/design/waterfall';
import {designContext} from '../src/export/design/context';
import {semanticVisualQuality} from '../src/intelligence/visualQuality';
import {recommendFigures} from '../src/export/design/recommend';
import {defects} from '../src/export/design/quality';
const fixture=(rows:unknown[][]=[['Initial',10],['Reduction',-4],['No change',0],['Increment',6]])=>documentSchema.parse({schemaVersion:1,id:'synthetic-waterfall',title:'Synthetic waterfall example',rootViewId:'root',nodes:[{id:'evidence',label:'Supplied illustrative increments',blockIds:['increments']}],edges:[],views:[{id:'root',title:'Supplied signed increments',nodeIds:['evidence'],positions:{evidence:{x:0,y:0}},design:{type:'waterfall'}}],blocks:[{id:'increments',title:'Synthetic signed increments',type:'table',columns:['Step','Delta (illustrative units)'],rows,provenance:'synthetic'}]});
test('waterfall faithfully accumulates supplied signed increments, not causal/observed outcomes, with zero floor and actual geometry',()=>{
 const p=fixture(),before=structuredClone(p),found=waterfallTable(designContext(p,'root','waterfall'))!,values=waterfallValues(found);assert.deepEqual(values.rows.map(r=>[r.value,r.start,r.end]),[[10,0,10],[-4,10,6],[0,6,6],[6,6,12]]);assert.equal(semanticVisualQuality(p,'root','waterfall').state,'SEMANTICS_CHECKED');assert.match(recommendFigures(p,'root').find(r=>r.type==='waterfall')!.reason,/not observed or causal totals/);for(const theme of ['light','dark','editorial'] as const){const svg=designSvg(p,'root',{type:'waterfall',theme});assert.match(svg,/SYNTHETIC DATA/);assert.match(svg,/not measured or verified/);assert.match(svg,/not supplied observed totals, causal effects or timing/);assert.deepEqual(defects(svg,'waterfall').failures,[]);}assert.deepEqual(p,before);
});
test('waterfall refuses altered deltas, cumulative sums, rectangle positions/heights and cumulative connectors',()=>{
 const p=fixture(),svg=designSvg(p,'root',{type:'waterfall'});for(const [from,to] of [['data-delta="-4"','data-delta="4"'],['data-end="6"','data-end="16"'],['data-start="10"','data-start="0"']])assert.equal(semanticVisualQuality(p,'root','waterfall',svg.replace(from,to)).state,'DEFECTS_FOUND');const altered=svg.replace(/(<rect data-waterfall-row="1"[^>]*height=")[^"]+/, '$1'+'999');assert.equal(semanticVisualQuality(p,'root','waterfall',altered).state,'DEFECTS_FOUND');const moved=svg.replace(/(<rect data-waterfall-row="1"[^>]* y=")[^"]+/,'$1'+'0');assert.equal(semanticVisualQuality(p,'root','waterfall',moved).state,'DEFECTS_FOUND');const connector=svg.replace(/(<line data-waterfall-connector="0"[^>]*y1=")[^"]+/,'$1'+'0');assert.equal(semanticVisualQuality(p,'root','waterfall',connector).state,'DEFECTS_FOUND');
});
test('waterfall is bounded, reports null gaps and omitted rows, handles all zero values and refuses nonfinite derived arithmetic',()=>{
 const p=fixture(Array.from({length:31},(_,i)=>['Synthetic step '+i,i===4?null:i%2?-i:i]));const svg=designSvg(p,'root',{type:'waterfall'});assert.equal((svg.match(/data-waterfall-row=/g)??[]).length,7);assert.match(svg,/23 further source row\(s\) not drawn/);assert.match(svg,/missing value\(s\).*never replaced with zero/);assert.equal(semanticVisualQuality(p,'root','waterfall').state,'PARTIAL');assert.deepEqual(defects(svg,'waterfall').failures,[]);assert.equal(semanticVisualQuality(fixture([['Zero',0]]),'root','waterfall').state,'SEMANTICS_CHECKED');const overflow=fixture([['Huge',1e308],['Overflow',1e308]]),bad=designSvg(overflow,'root',{type:'waterfall'});assert.match(bad,/exceeds finite numeric limits/);assert.ok(!bad.includes('data-waterfall-row='));assert.equal(semanticVisualQuality(overflow,'root','waterfall').state,'PARTIAL');const missing=fixture([]);assert.match(designSvg(missing,'root',{type:'waterfall'}),/No public numeric table/);assert.equal(semanticVisualQuality(missing,'root','waterfall').state,'PARTIAL');
});
test('private numeric evidence is removed before selection and an unlabelled numeric series remains an explicit interpretation',()=>{
 const p=fixture();p.blocks[0].visibility='private';const svg=designSvg(p,'root',{type:'waterfall'});assert.ok(!svg.includes('Synthetic signed increments'));assert.equal(semanticVisualQuality(p,'root','waterfall').state,'PARTIAL');p.blocks[0].visibility='public';if(p.blocks[0].type==='table')p.blocks[0].columns[1]='Supplied values';const result=semanticVisualQuality(p,'root','waterfall');assert.equal(result.state,'PARTIAL');assert.ok(result.checks.some(c=>c.id==='waterfall-increment-interpretation'&&c.state==='unknown'));
});
