import test from 'node:test';
import assert from 'node:assert/strict';
import {documentSchema} from '../src/core/model';
import {publicationPages,publicationPageProject,scopePublicationSvg} from '../src/export/publicationPages';
import {technicalManualHtml} from '../src/export/manual';
import {designSvg} from '../src/export/design';
import {defects} from '../src/export/design/quality';
import {publicationFidelity,validatePublicationBrief} from '../src/intelligence/publicationBrief';
import {readFileSync} from 'node:fs';
import {parseDocument} from '../src/core/model';
import {publicDocument} from '../src/core/operations';
const NOW=new Date('2026-10-09T10:00:00Z');
const dense=()=>documentSchema.parse({schemaVersion:1,id:'synthetic-paged-manual',title:'Synthetic bounded handbook',rootViewId:'root',nodes:[...Array.from({length:49},(_,i)=>({id:'n'+i,label:'Synthetic component '+i,kind:'process',basis:'planned',...(i===0?{childViewId:'detail'}:{})})),{id:'secret',label:'PRIVATE_PAGE_SENTINEL',visibility:'private'}],edges:Array.from({length:48},(_,i)=>({id:'e'+i,source:'n'+i,target:'n'+(i+1),label:'Supplied handoff '+i,basis:'planned',quantity:{value:i+1,unit:'rows/day',provenance:'synthetic'}})),views:[{id:'root',title:'Synthetic dense flow',nodeIds:[...Array.from({length:49},(_,i)=>'n'+i),'secret'],edgeIds:Array.from({length:48},(_,i)=>'e'+i),design:{type:'sankey'},positions:Object.fromEntries(Array.from({length:49},(_,i)=>['n'+i,{x:i*300,y:0}]))},{id:'detail',title:'Existing supplied details',nodeIds:['n1','n2'],edgeIds:['e1'],positions:{n1:{x:0,y:0},n2:{x:300,y:0}}}]});
test('twelve and forty wide components split under measured Classic paper readability rather than count alone',()=>{
 for(const count of [12,40]){const ids=Array.from({length:count},(_,i)=>'node'+i),doc=documentSchema.parse({schemaVersion:1,id:'synthetic-wide-'+count,title:'Synthetic wide source layout',rootViewId:'root',nodes:ids.map(id=>({id,label:id})),edges:[],views:[{id:'root',title:'Wide view',nodeIds:ids,edgeIds:[],positions:Object.fromEntries(ids.map((id,i)=>[id,{x:i*300,y:0}]))}]}),before=JSON.stringify(doc),brief=validatePublicationBrief({format:'diagramcloud.publication-brief/1',title:'Synthetic wide handbook',audience:'Reviewer',viewIds:['root'],profile:'classic',paper:'A4'},doc),plan=publicationPages(doc,'root',['root'],{profile:'classic',paper:'A4'}),ledger=publicationFidelity(doc,brief).views[0];
  assert.equal(plan.dense,true);assert.ok(plan.legibility.displayLabelSize<8);assert.equal(plan.pages.length,Math.ceil(count/8));assert.deepEqual(plan.pages.flatMap(page=>page.nodeIds),ids);assert.equal(ledger.complexity.paginated,true);assert.equal(ledger.complexity.withinOverviewBudget,true);assert.equal(ledger.pages.length,plan.pages.length);assert.equal((technicalManualHtml(doc,{brief,now:NOW}).match(/data-publication-page=/g)??[]).length,plan.pages.length);assert.equal(JSON.stringify(doc),before);
  for(let i=0;i<plan.pages.length;i++){const projected=publicationPageProject(doc,plan,i),page=publicationPages(projected,'root',undefined,{profile:'classic',paper:'A4'});assert.ok(page.legibility.displayLabelSize>=8);}
 }
});
test('dense pages partition only canonical public primary membership, prefer supplied child details and retain every connection',()=>{
 const p=dense(),before=structuredClone(p),plan=publicationPages(p,'root',['root','detail']);assert.equal(plan.dense,true);assert.deepEqual(plan.pages[0].nodeIds,['n1','n2']);assert.ok(plan.pages.every(page=>page.nodeIds.length<=8&&page.edgeIds.length<=24));assert.deepEqual(new Set(plan.pages.flatMap(page=>page.nodeIds)),new Set(p.nodes.filter(n=>n.visibility!=='private').map(n=>n.id)));assert.deepEqual(new Set([...plan.ledger.edges.shown,...plan.ledger.edges.collapsed]),new Set(p.edges.map(e=>e.id)));assert.equal(plan.ledger.edges.omitted.length,0);assert.ok(plan.contextEdges.every(e=>e.quantity?.provenance==='synthetic'));assert.ok(!JSON.stringify(plan).includes('PRIVATE_PAGE_SENTINEL'));assert.deepEqual(p,before);
 const curated=publicationPages(p,'root',['root']);assert.equal(curated.details[0].selected,false);assert.equal(curated.pages[0].nodeIds.length,8);assert.ok(curated.pages.every(page=>page.detailViewIds.length===0));
});
test('each bounded chapter figure passes actual geometry checks without changing authoring positions or semantic quantities',()=>{
 const p=dense(),before=structuredClone(p),plan=publicationPages(p,'root',['root']);for(let i=0;i<plan.pages.length;i++){const projected=publicationPageProject(p,plan,i),svg=designSvg(projected,'root',{type:'architecture',now:NOW}),qa=defects(svg,'architecture');assert.deepEqual(qa.failures,[],`page ${i+1}: ${qa.failures.join('; ')}`);assert.ok(qa.texts>0);assert.deepEqual(projected.edges,p.edges);assert.deepEqual(projected.views.find(v=>v.id==='root')!.nodeIds,plan.pages[i].nodeIds);}assert.deepEqual(p,before);
});
test('offline manual prints bounded pages, full fact tables, quantities and truthful private omissions with unique document IDs',()=>{
 const p=dense(),html=technicalManualHtml(p,{now:NOW,viewIds:['root']});assert.ok(!html.includes('PRIVATE_PAGE_SENTINEL'));assert.match(html,/Zero public components or connections omitted by pagination/);assert.match(html,/1 private or unreachable component\(s\) removed/);assert.match(html,/outside the selected chapters; not expanded/);assert.match(html,/Keyed connection context/);assert.match(html,/rows\/day/);assert.match(html,/synthetic/);for(const n of p.nodes.filter(n=>n.id!=='secret'))assert.ok(html.includes('>'+n.id+'<'),n.id);for(const e of p.edges)assert.ok(html.includes('>'+e.id+'<'),e.id);assert.equal((html.match(/data-publication-page=/g)??[]).length,7);assert.equal((html.match(/data-design-type="sankey"/g)??[]).length,0);assert.ok(!/<script\b|(?:src|href)="https?:/i.test(html));const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);assert.equal(html,technicalManualHtml(p,{now:NOW,viewIds:['root']}));
});
test('small chapters retain their selected specialized figure and scoped SVG IDs preserve stable fact metadata',()=>{
 const p=dense();p.views[0].nodeIds=['n0','n1'];p.views[0].edgeIds=['e0'];p.views[0].positions={n0:{x:0,y:0},n1:{x:300,y:0}};const plan=publicationPages(p,'root');assert.equal(plan.dense,false);assert.ok(!technicalManualHtml(p,{now:NOW}).includes('data-publication-page='));assert.match(technicalManualHtml(p,{now:NOW}),/data-design-type="sankey"/);const svg='<svg aria-labelledby="title"><title id="title">Title</title><defs><marker id="arrow"/></defs><path data-dd-edge="arrow" marker-end="url(#arrow)"/></svg>';assert.equal(scopePublicationSvg(svg,'page-2'),'<svg aria-labelledby="title-page-2"><title id="title-page-2">Title</title><defs><marker id="arrow-page-2"/></defs><path data-dd-edge="arrow" marker-end="url(#arrow-page-2)"/></svg>');
});
test('fidelity ledger agrees with dense page figures, deferred connections and business textual representation',()=>{
 const p=dense(),brief={format:'diagramcloud.publication-brief/1',title:'Synthetic ledger',audience:'Technical readers',viewIds:['root'],profile:'design'},fidelity=publicationFidelity(p,brief),plan=publicationPages(p,'root',['root']),row=fidelity.views[0];assert.deepEqual(row.nodes,plan.ledger.nodes);assert.deepEqual(row.edges,plan.ledger.edges);assert.equal(row.pages.length,plan.pages.length);assert.deepEqual(row.contextTableEdgeIds,plan.contextEdges.map(e=>e.id));assert.equal(row.complexity.paginated,true);const business=publicationFidelity(p,{...brief,profile:'business'}).views[0];assert.deepEqual(business.edges.shown,[]);assert.equal(business.edges.collapsed.length,p.edges.length);assert.ok(business.pages.every(page=>page.drawnEdgeIds.length===0));assert.equal(business.representation,'text-and-tables');
});
test('selected real local atlas dense page projections pass unchanged geometry without copying private fixtures',{skip:!process.env.DIAGRAMCLOUD_QUALITY_DOCS},()=>{
 for(const path of process.env.DIAGRAMCLOUD_QUALITY_DOCS!.split(',').filter(Boolean)){const doc=parseDocument(readFileSync(path,'utf8'));for(const view of publicDocument(doc).views){const plan=publicationPages(doc,view.id);if(!plan.dense)continue;for(let i=0;i<plan.pages.length;i++){const svg=designSvg(publicationPageProject(doc,plan,i),view.id,{type:'architecture',now:NOW}),qa=defects(svg,'architecture');assert.equal(qa.failures.length,0,'A selected local atlas projected page has geometric defects');assert.ok(qa.texts>0);assert.equal(qa.unresolvedShapes,0);}}}
});
