import test from 'node:test';
import assert from 'node:assert/strict';
import {buildSourceAnalysisBundle} from '../src/intelligence/sourceBundle';
import {analysisProfile,analysisCacheKey,validateAnalysisBundle} from '../src/intelligence/profile';
import {nodeDeepRuntime} from '../scripts/lib/deepRuntime';
import {sourceBundlePatch} from '../src/intelligence/sourceBundlePatch';
import {documentSchema,validateDocument} from '../src/core/model';
import {applyDocumentPatch} from '../src/core/patch';
import {publicDocument} from '../src/core/operations';
const identity={repositoryId:'synthetic',revision:'a'.repeat(40)},files=[{path:'README.md',text:'# Synthetic selected docs\n## Source contract\n[Module](src/a.ts)'},{path:'src/a.ts',text:'// illustrative fixture\nimport {run} from "./b";\nexport function start(){run();}'},{path:'src/b.ts',text:'export function run(){return 1;}'},{path:'Data/manifest.json',text:JSON.stringify({metadata:{dbt_schema_version:'https://schemas.getdbt.com/dbt/manifest/v12.json'},nodes:{'model.synthetic.clean':{name:'clean',depends_on:{nodes:[]}}}})},{path:'Api/Api.csproj',text:'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>'}];
test('configured source bundle dispatches documents, inventory, relative imports and only the selected native domains',async()=>{
 const before=structuredClone(files),profile=analysisProfile('standard',{analyzers:['documents','inventory','imports','dbt']}),bundle=await buildSourceAnalysisBundle(files,identity,profile);assert.deepEqual(files,before);assert.ok(bundle.items.some(i=>i.kind==='section'&&i.label==='Source contract'));assert.ok(bundle.items.some(i=>i.kind==='native-dbt-model'));assert.ok(!bundle.items.some(i=>i.kind.startsWith('native-dotnet')));assert.equal(bundle.items.filter(i=>i.kind==='selected-source-file').length,5);const edge=bundle.links.find(l=>l.kind==='lexical-relative-import')!;assert.equal(edge.confidence,'inferred');const citation=bundle.sources.find(s=>s.id===edge.sourceIds[0])!;assert.equal(citation.path,'src/a.ts');assert.equal(citation.line,2);assert.ok(bundle.sources.every(s=>s.revision===identity.revision&&/^[a-f0-9]{64}$/.test(s.contentDigest)));assert.doesNotThrow(()=>validateAnalysisBundle(bundle));const native=await buildSourceAnalysisBundle(files,identity,analysisProfile('quick',{analyzers:['dotnet']}));assert.ok(native.items.some(i=>i.kind==='native-dotnet-app'));assert.ok(native.items.every(i=>i.kind.startsWith('native-dotnet')));assert.ok(!native.items.some(i=>i.kind==='section'));assert.deepEqual(bundle,await buildSourceAnalysisBundle([...files].reverse(),identity,profile));
});
test('source bundle enforces safe selected paths, nested boundaries, scope, byte/node/link budgets and preserves absence diagnostics',async()=>{
 const selected=[...files,{path:'Nested/.git',text:'gitdir: ignored'},{path:'Nested/main.ts',text:'export function nested(){}'},{path:'.env',text:'PRIVATE_ENV_VALUE'},{path:'node_modules/vendor/a.ts',text:'PRIVATE_VENDOR_VALUE'},{path:'../unsafe.ts',text:'PRIVATE_PATH_VALUE'},{path:'generated.g.ts',text:'export function generated(){}'}],profile=analysisProfile('standard',{analyzers:['inventory','imports'],scope:['src'],budgets:{nodes:1,links:1,fileBytes:1024,totalBytes:2048}}),bundle=await buildSourceAnalysisBundle(selected,identity,profile);assert.equal(bundle.items.length,1);assert.ok(bundle.omitted.items>0);assert.ok(bundle.omitted.sources>=5);assert.ok(bundle.sources.every(s=>s.path.startsWith('src/')));assert.ok(!JSON.stringify(bundle).includes('PRIVATE_'));assert.ok(bundle.diagnostics.some(d=>d.includes('missing selection is not absent implementation')));await assert.rejects(()=>buildSourceAnalysisBundle([...files,files[0]],identity,profile),/Duplicate selected source paths/);await assert.rejects(()=>buildSourceAnalysisBundle(files,{repositoryId:'other',revision:identity.revision},analysisProfile('quick',{repositoryIds:['synthetic']})),/outside the profile/);const controller=new AbortController();controller.abort();await assert.rejects(()=>buildSourceAnalysisBundle(files,identity,profile,{signal:controller.signal}),{name:'AbortError'});
});
test('configured analysis cache binds selected safe content, profile and analyzer version; inferred off never produces a lexical import verdict',async()=>{
 const profile=analysisProfile('quick',{analyzers:['inventory','imports'],includeInferred:false}),bundle=await buildSourceAnalysisBundle(files,identity,profile);assert.equal(bundle.links.filter(l=>l.kind==='lexical-relative-import').length,0);const altered=await buildSourceAnalysisBundle(files.map(f=>f.path==='src/b.ts'?{...f,text:f.text+'\n// selected content changed'}:f),identity,profile);assert.notEqual(await analysisCacheKey(bundle),await analysisCacheKey(altered));assert.notEqual(await analysisCacheKey(bundle),await analysisCacheKey(await buildSourceAnalysisBundle(files,identity,analysisProfile('standard',{analyzers:['inventory']}))));
});
test('Tree-sitter stays NOT_RUN without a runtime and genuinely parses when an explicit authorized runtime is supplied',async()=>{
 const profile=analysisProfile('deep',{analyzers:['documents','tree-sitter']}),notRun=await buildSourceAnalysisBundle(files,identity,profile);assert.ok(notRun.diagnostics.some(d=>d.includes('Tree-sitter selected')&&d.includes('NOT_RUN')));assert.ok(!notRun.items.some(i=>i.kind==='function_declaration'));const bundle=await buildSourceAnalysisBundle(files,identity,profile,{runtime:await nodeDeepRuntime()});assert.ok(bundle.items.some(i=>i.label==='start'));assert.ok(bundle.items.some(i=>i.label==='run'));assert.ok(bundle.parserVersion.includes('runtime0.25.10'));assert.ok(!bundle.diagnostics.some(d=>d.includes('syntax analysis NOT_RUN')));assert.doesNotThrow(()=>validateAnalysisBundle(bundle));
});
test('selected configured analysis projects only through a guarded private reviewed patch and preserves authoring state',async()=>{
 const bundle=await buildSourceAnalysisBundle(files,identity,analysisProfile('standard',{analyzers:['documents','dbt','imports']})),project=documentSchema.parse({schemaVersion:1,id:'synthetic-source-projection',title:'Synthetic source projection',rootViewId:'root',nodes:[{id:'root-node',label:'Existing authored project'}],edges:[],views:[{id:'root',title:'Project',nodeIds:['root-node']}]}),before=structuredClone(project),selected=bundle.items.slice(0,5).map(i=>i.id),patch=sourceBundlePatch(project,bundle,selected),after=applyDocumentPatch(project,patch).result;assert.deepEqual(project,before);assert.equal(patch.baseRevision,project.revision);assert.equal(after.observations.length,0);assert.ok(after.nodes.filter(n=>selected.includes(n.id)).every(n=>n.visibility==='private'));assert.ok(after.sources.every(s=>s.visibility==='private'));assert.doesNotThrow(()=>validateDocument(after));assert.deepEqual(publicDocument(after).nodes.map(n=>n.id),['root-node']);assert.throws(()=>sourceBundlePatch(after,bundle,selected),/already exists/);assert.throws(()=>applyDocumentPatch({...project,revision:project.revision+1},patch),/revision/i);
});
