import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {readRepositorySelection} from '../scripts/lib/readRepo';
import {scanRepository} from '../src/core/scan/scanner';
import {documentFromScan} from '../src/core/scan/document';
import {publicDocument} from '../src/core/operations';
test('Git boundary metadata labels explicit submodules/worktrees without following or copying gitdir pointers',()=>{
 const selected=[{path:'package.json',text:'{"name":"synthetic"}'},{path:'.gitmodules',text:'[submodule "lib"]\n path = libraries/shared\n url = https://private.example.invalid/lib'},
  {path:'libraries/shared/.git',text:'gitdir: ../../../.git/modules/shared'},{path:'libraries/shared/a.ts',text:'function privateSubmoduleSource(){}'},
  {path:'tools/work/.git',text:'gitdir: ../../.git/worktrees/synthetic'},{path:'tools/work/a.ts',text:'function privateWorktreeSource(){}'}];
 const model=scanRepository(selected);assert.equal(model.boundaries?.find(b=>b.path==='libraries/shared')?.kind,'submodule');assert.equal(model.boundaries?.find(b=>b.path==='tools/work')?.kind,'worktree');
 assert.ok(![...model.items].some(([key])=>key.includes('libraries/shared')||key.includes('tools/work')));assert.equal(model.partition?.boundary,4);
 const document=documentFromScan(model).document,receipt=document.blocks.find(b=>b.id==='scan-source-inventory');assert.ok(receipt&&receipt.visibility==='private');
 const serialized=JSON.stringify(receipt);for(const privateValue of ['../../../.git/modules/shared','../../.git/worktrees/synthetic','private.example.invalid','privateSubmoduleSource','privateWorktreeSource'])assert.ok(!serialized.includes(privateValue));
 assert.ok(!JSON.stringify(publicDocument(document)).includes('libraries/shared'));
});
test('Generated and vendor partitions retain omission counts without treating source absence as removal',()=>{
 const model=scanRepository([{path:'src/a.ts',text:'export const a=1;'},{path:'src/auto.generated.ts',text:'export const ignored=1;'},{path:'node_modules/lib/a.ts',text:'export const vendored=1;'},{path:'src/header.ts',text:'// <auto-generated>\nexport const generated=1;'},{path:'README.md',text:'hi'}]);
 assert.deepEqual(model.partition,{authored:1,generated:2,vendor:1,boundary:0,unsupported:1});
 assert.ok(![...model.items.values()].some(i=>i.evidence.some(e=>e.kind!=='selection-metadata'&&/generated|node_modules|header/.test(e.file))));
 assert.equal(model.skipped.get('generated/build entries excluded'),2);
 const unsafe=scanRepository([{path:'../outside.ts',text:'function shouldNotExist(){}'},{path:'C:/outside/a.ts',text:'function shouldNotExist(){}'}]);assert.equal(unsafe.items.size,1);assert.equal(unsafe.skipped.get('unsafe source paths refused'),2);
});
test('Selected CLI repository boundary inventory excludes all nested content and records directory-count semantics',()=>{
 const root=mkdtempSync(join(tmpdir(),'dc-source-inventory-'));
 try{writeFileSync(join(root,'package.json'),'{}');mkdirSync(join(root,'tools','work'),{recursive:true});writeFileSync(join(root,'tools','work','.git'),'gitdir: ../../.git/worktrees/synthetic');writeFileSync(join(root,'tools','work','private.ts'),'function secretNestedContent(){}');mkdirSync(join(root,'vendor'));writeFileSync(join(root,'vendor','private.ts'),'function vendor(){}');
  const selected=readRepositorySelection(root);assert.ok(!selected.files.some(f=>f.path.startsWith('tools/work/')||f.path.startsWith('vendor/')));assert.equal(selected.omitted['nested Git boundary excluded'],1);assert.equal(selected.omitted['ignored directory excluded (not counted as files)'],1);
  const model=scanRepository(selected.files,{boundaryPaths:selected.boundaryPaths,boundaryMarkers:selected.boundaryMarkers});assert.equal(model.boundaries?.[0].kind,'worktree');assert.ok(!JSON.stringify(model.boundaries).includes('../../.git/worktrees/synthetic'));
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('scanner separates selected-directory metadata from admitted source file citations',()=>{
 const input=[{path:'src/one/a.ts',text:'export const a=1;'},{path:'src/two/b.ts',text:'export const b=2;'}],paths=new Set(input.map(f=>f.path)),model=scanRepository(input);
 for(const item of model.items.values())for(const evidence of item.evidence){if(evidence.kind==='selection-metadata'){assert(!('file' in evidence));assert(!('line' in evidence));assert(['.','src/one','src/two'].includes(evidence.path));}else{assert(paths.has(evidence.file));assert(evidence.line>=1);}}
 const document=documentFromScan(model).document;assert(document.blocks.some(b=>b.type==='table'&&b.provenance==='reference'&&b.title.includes('no source line')));
 const container=document.nodes.find(n=>n.tags.includes('Container'));assert.equal(container?.basis,'unknown');
 const empty=scanRepository([]).items.get('system')!.evidence[0];assert.equal(empty.kind,'selection-metadata');assert(!('file' in empty));assert(!('line' in empty));assert.equal(documentFromScan(scanRepository([])).document.nodes[0].basis,'unknown');
 const declared=scanRepository([{path:'package.json',text:'{}'}]);assert([...declared.items.values()].filter(i=>i.layer==='system'||i.layer==='container').every(i=>i.evidence.every(e=>e.kind!=='selection-metadata'&&e.file==='package.json')));
});
