import {useState} from 'react';
import {ANALYZERS,validateAnalysisProfile,type AnalysisProfile} from '../intelligence/profile';
/** Reusable profile editor. It emits only a validated analysis config, never a Project edit. */
export function AnalysisProfilePanel({profile,onChange}:{profile:AnalysisProfile;onChange:(profile:AnalysisProfile)=>void}){
 const [error,setError]=useState('');
 const change=(partial:Partial<AnalysisProfile>)=>{try{const p=validateAnalysisProfile({...profile,...partial});onChange(p);setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid profile');}};
 const load=async(file:File|undefined)=>{if(!file)return;try{if(file.size>65536)throw new Error('Profile exceeds 64 KiB');onChange(validateAnalysisProfile(JSON.parse(await file.text())));setError('');}catch(e){setError(e instanceof Error?e.message:'Profile refused');}};
 return <fieldset aria-label="Validated analysis profile parameters"><legend>Analyzer and acquisition budgets</legend>{error&&<p role="alert">{error}</p>}<p>Acquisition budget differs from the bounded figure preview. Larger generated analysis never increases authoring Project limits.</p><div className="pi-controls"><fieldset><legend>Selected analyzers</legend>{ANALYZERS.map(a=><label key={a}><input type="checkbox" checked={profile.analyzers.includes(a)} onChange={e=>change({depth:a==='tree-sitter'?'custom':profile.depth,analyzers:e.target.checked?[...profile.analyzers,a]:profile.analyzers.filter(v=>v!==a)})}/>{a}</label>)}</fieldset>{(['files','fileBytes','totalBytes','nodes','links'] as const).map(k=><label key={k}>{k} acquisition budget<input aria-label={k+' acquisition budget'} type="number" min={k.endsWith('Bytes')?1024:1} max={{files:10000,fileBytes:1048576,totalBytes:67108864,nodes:10000,links:50000}[k]} value={profile.budgets[k]} onChange={e=>change({depth:'custom',budgets:{...profile.budgets,[k]:Number(e.target.value)}})}/></label>)}</div><label>Selected path prefixes<input aria-label="Analysis path prefixes" value={profile.scope.join(",")} onChange={e=>change({scope:e.target.value.split(",").map(s=>s.trim()).filter(Boolean)})}/></label><label>Import validated profile<input aria-label="Import validated analysis profile" type="file" accept="application/json,.json" onChange={e=>{void load(e.target.files?.[0]);e.target.value='';}}/></label><p>Autonomy: review required. No source read or execution occurs when changing a profile.</p></fieldset>;
}
