import {useEffect,useMemo,useState} from 'react';
import {ReactFlow,Background,Controls,MiniMap,Handle,Position,BaseEdge,EdgeLabelRenderer,getSmoothStepPath,MarkerType,applyNodeChanges,type Node,type NodeProps,type EdgeProps,type Edge,type Connection} from '@xyflow/react';
import {Button} from '@fluentui/react-components';
import {positionFor,traceNodes} from '../core/operations';
import type {Project,ProjectNode,ProjectView} from '../core/model';
import '@xyflow/react/dist/style.css';

type CanvasNode=Node<{item:ProjectNode;dimmed:boolean;motion:boolean;activate:()=>void},'component'>;
function ComponentNode({data,selected}:NodeProps<CanvasNode>){const n=data.item;return <div className={`component-node kind-${n.kind} ${selected?'chosen':''} ${data.dimmed?'dimmed':''}`}><Handle type="target" position={Position.Left}/><button className="node-button" onClick={data.activate} aria-label={`Explore ${n.label}`}><div className="node-top"><span className={`component-icon ${data.motion&&n.status==='running'?'activity':''}`}><NodeIcon node={n}/></span><span className="provider-name">{n.provider}</span><span className={`status-dot status-${n.status}`} title={`Illustrative status: ${n.status}`}/></div><strong>{n.label}</strong><span className="node-summary">{n.summary||n.kind}</span><span className="node-bottom">{n.childViewId?<><span className="drill-mark">↳</span> Explore subdiagram</>:n.blockIds.length?`${n.blockIds.length} evidence block${n.blockIds.length>1?'s':''}`:'Component details'}{n.visibility==='private'&&<span>Private</span>}</span></button><Handle type="source" position={Position.Right}/></div>;}
export function NodeIcon({node}:{node:Pick<ProjectNode,'kind'|'icon'|'provider'>}){if(node.icon==='fabric-lakehouse')return <img className="official-icon" src={`${import.meta.env.BASE_URL}icons/fabric-lakehouse.svg`} alt="Microsoft Fabric Lakehouse icon"/>;const kind=node.kind;return <svg viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="currentColor" strokeWidth="1.55" aria-hidden="true">{kind==='storage'||kind==='source'?<><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v13c0 4 16 4 16 0V5M4 11c0 4 16 4 16 0"/></>:kind==='table'||kind==='model'?<><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M9 9v11M15 9v11M3 14h18"/></>:kind==='report'?<><path d="M4 3v18h18M8 17v-5M13 17V6M18 17V9"/></>:kind==='control'?<><path d="M12 2l8 3v6c0 5-8 10-8 10S4 16 4 11V5zM8 11l3 3 5-6"/></>:kind==='function'?<><path d="M8 6L2 12l6 6M16 6l6 6-6 6M14 3l-4 18"/></>:kind==='physics'?<><path d="M3 7c3-5 5 5 9 0s6 5 9 0M3 13c3-5 5 5 9 0s6 5 9 0M3 19c3-5 5 5 9 0s6 5 9 0"/></>:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/><path d="M10 6h7v8M14 17H7v-7"/></>}</svg>;}
type FlowEdge=Edge<{kind:string;speed:string;motion:boolean;dimmed:boolean;highlighted:boolean},'dataflow'>;
function DataEdge(props:EdgeProps<FlowEdge>){const [path,x,y]=getSmoothStepPath({...props,borderRadius:14});const d=props.data;return <g className={`data-edge ${d?.motion?'moving':''} speed-${d?.speed??'medium'} ${d?.dimmed?'dimmed':''} ${d?.highlighted?'highlighted':''} ${props.selected?'edge-selected':''}`}><BaseEdge id={props.id} path={path} markerEnd={props.markerEnd} style={{stroke:d?.highlighted?'#2563eb':'#93a5be',strokeWidth:d?.highlighted?2.6:1.7,strokeDasharray:d?.kind==='control'?'5 5':undefined}}/>{d?.motion&&<path className="flow-dashes" d={path} fill="none" stroke="#4b78bf" strokeWidth="2" strokeDasharray="3 16" pointerEvents="none"/>}<EdgeLabelRenderer><span className="edge-label" style={{transform:`translate(-50%,-50%) translate(${x}px,${y}px)`,opacity:d?.dimmed?.25:1}}>{String(props.label??'')}</span></EdgeLabelRenderer></g>;}
const nodeTypes={component:ComponentNode},edgeTypes={dataflow:DataEdge};
export type Trace='none'|'upstream'|'downstream';
type Props={doc:Project;view:ProjectView;level:number;selected:string|null;selectedEdge:string|null;edit:boolean;motion:boolean;trace:Trace;highlights:string[];onSelect:(nodeId:string,viewId:string,level:number)=>void;onEdge:(edgeId:string,viewId:string)=>void;onMove:(nodeId:string,viewId:string,x:number,y:number)=>void;onConnect:(viewId:string,connection:Connection)=>void;onGrid:(viewId:string)=>void;onAdd:(viewId:string)=>void;onClose?:()=>void};
export function DiagramCanvas(p:Props){const traced=useMemo(()=>p.trace!=='none'&&p.selected&&p.view.nodeIds.includes(p.selected)?traceNodes(p.doc,p.view.id,p.selected,p.trace):null,[p.doc,p.view,p.selected,p.trace]);const original=useMemo<CanvasNode[]>(()=>p.doc.nodes.filter(n=>p.view.nodeIds.includes(n.id)).map(n=>({id:n.id,type:'component',position:positionFor(p.view,n.id),selected:p.selected===n.id,data:{item:n,dimmed:!!traced&&!traced.has(n.id),motion:p.motion,activate:()=>p.onSelect(n.id,p.view.id,p.level)}})),[p.doc,p.view,p.selected,p.motion,traced,p.level,p.onSelect]);const [nodes,setNodes]=useState(original);useEffect(()=>setNodes(original),[original]);
 const edges=useMemo<FlowEdge[]>(()=>p.doc.edges.filter(e=>p.view.edgeIds.includes(e.id)).map(e=>({id:e.id,type:'dataflow',source:e.source,target:e.target,label:e.label,selected:p.selectedEdge===e.id,markerEnd:{type:MarkerType.ArrowClosed,width:14,height:14,color:'#93a5be'},data:{kind:e.kind,speed:e.speed,motion:p.motion,dimmed:!!traced&&(!traced.has(e.source)||!traced.has(e.target)),highlighted:p.highlights.includes(e.id)||!!traced&&traced.has(e.source)&&traced.has(e.target)}})),[p.doc,p.view,p.motion,p.selectedEdge,p.highlights,traced]);
 return <section className="diagram-section" data-testid={`view-${p.view.id}`}><div className="view-heading"><div><div className="eyebrow">{p.level===0?'01 / ARCHITECTURE':`${String(p.level+1).padStart(2,'0')} / DRILLDOWN`}</div><h2>{p.view.title}</h2></div><div className="toolbar">{p.edit&&<><Button size="small" onClick={()=>p.onAdd(p.view.id)}>+ Component</Button><Button size="small" onClick={()=>p.onGrid(p.view.id)}>Grid layout</Button></>}{p.onClose&&<Button size="small" appearance="subtle" onClick={p.onClose}>Close level</Button>}</div></div><p className="view-description">{p.view.description}</p><div className="canvas-frame"><ReactFlow<CanvasNode,FlowEdge> nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} onNodesChange={changes=>setNodes(ns=>applyNodeChanges(changes,ns))} nodesDraggable={p.edit} nodesConnectable={p.edit} elementsSelectable onNodeDragStop={(_,n)=>p.onMove(n.id,p.view.id,n.position.x,n.position.y)} onConnect={c=>p.onConnect(p.view.id,c)} onEdgeClick={(_,e)=>p.onEdge(e.id,p.view.id)} fitView fitViewOptions={{padding:.22,minZoom:.25,maxZoom:1.05}} minZoom={.15} maxZoom={2} deleteKeyCode={null} selectionOnDrag={false} panOnScroll={false} zoomOnScroll={false} preventScrolling={false}><Background gap={22} size={1}/><Controls showInteractive={false}/><MiniMap nodeColor="#d8e5fa" maskColor="rgba(248,250,253,0.75)" pannable zoomable/></ReactFlow></div><div className="canvas-caption"><span>{p.view.nodeIds.length} components · {p.view.edgeIds.length} connections</span><span>{p.edit?'Drag cards · Connect the side handles':'Click a card to explore · Pinch or use controls to zoom'}</span></div></section>;
}
