import {useMemo,useState} from 'react';
import type {Project,ProjectDelivery} from '../core/model';
import {compareEnvironments,deliveryCoverageMatrix,deliveryGates,releaseChain,deliveryPublicationPatch,type DeliveryPublicationKind} from '../intelligence/delivery';
import {DELIVERY_PROFILES,deliveryFigure,deliveryHtml,type DeliveryProfile} from '../export/design/operations';
import {download} from '../export/browser';
const identity=(kind:string,value:string)=>{let h=2166136261;for(const c of value)h=Math.imul(h^c.charCodeAt(0),16777619);return kind+'-'+value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)+'-'+(h>>>0).toString(16);};
const initial=():ProjectDelivery=>({environments:[],artifacts:[],instances:[],promotions:[]});
/** Author declarations enter the standard review path. No runtime claim controls. */
export function DeliveryPanel({project,onDelivery,onOpen,onPatch}:{project:Project;onDelivery?:(input:unknown)=>void;onOpen?:(view:string,node?:string)=>void;onPatch?:(input:unknown)=>void}){
 const [component,setComponent]=useState(''),[environment,setEnvironment]=useState(''),[version,setVersion]=useState(''),[revision,setRevision]=useState(''),[digest,setDigest]=useState(''),[build,setBuild]=useState(''),[release,setRelease]=useState(''),[role,setRole]=useState(''),[lifecycle,setLifecycle]=useState<'ephemeral'|'persistent'|'unknown'>('unknown');
 const [sourceIds,setSourceIds]=useState<string[]>([]),[action,setAction]=useState<'instance'|'not-applicable'|'configuration'>('instance'),[reason,setReason]=useState(''),[configName,setConfigName]=useState(''),[configKind,setConfigKind]=useState<'flag'|'configuration'>('configuration'),[valueState,setValueState]=useState<'declared-enabled'|'declared-disabled'|'configured'|'unknown'>('unknown');
 const [facet,setFacet]=useState<NonNullable<ProjectDelivery['environments'][number]['bindings']>[number]['kind']>('region'),[facetLabel,setFacetLabel]=useState('');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[promotionArtifact,setPromotionArtifact]=useState(''),[gate,setGate]=useState(''),[gateObservation,setGateObservation]=useState(''),[age,setAge]=useState(24),[error,setError]=useState(''),[page,setPage]=useState(0),[search,setSearch]=useState('');
 const [profile,setProfile]=useState<DeliveryProfile>('environment'),[figurePage,setFigurePage]=useState(0),[environmentPage,setEnvironmentPage]=useState(0),[publicationKind,setPublicationKind]=useState<DeliveryPublicationKind>('environments'),[publicationId,setPublicationId]=useState(''),[publicationVisibility,setPublicationVisibility]=useState<'public'|'private'>('private'),[related,setRelated]=useState(false);
 const figure=useMemo(()=>deliveryFigure(project,profile,{page:figurePage,environmentPage,maxAgeHours:age}),[project,profile,figurePage,environmentPage,age]);
 const instances=new Set(project.delivery?.instances.map(i=>i.nodeId)),components=project.nodes.filter(n=>!n.childViewId&&!instances.has(n.id));
 const matrix=useMemo(()=>deliveryCoverageMatrix(project,{componentIds:components.map(n=>n.id),maxAgeHours:age}),[project,age]);
 const filtered=matrix.filter(r=>!search||[r.component,r.environment,r.state].join(' ').toLowerCase().includes(search.toLowerCase())),visible=filtered.slice(page*40,(page+1)*40),chains=releaseChain(project),gates=deliveryGates(project,{maxAgeHours:age});
 const comparison=from&&to?compareEnvironments(project,from,to,{maxAgeHours:age}):[];
 const review=(delivery:ProjectDelivery)=>onDelivery?.({format:'diagramcloud.delivery-brief',version:1,projectId:project.id,baseRevision:project.revision,delivery});
 const declare=()=>{setError('');try{
  if(!component||!environment.trim())throw new Error('Select a logical component and name an environment');const delivery=structuredClone(project.delivery??initial()),existing=delivery.environments.find(e=>e.label===environment.trim()),envId=existing?.id??identity('env',environment.trim());
  if(!existing)delivery.environments.push({id:envId,label:environment.trim(),description:'Author-declared environment; independent of branches and data-layer names',role:role||undefined,lifecycle,bindings:[],sourceIds,visibility:'private'});
  else {existing.role=role||existing.role;existing.lifecycle=lifecycle;existing.sourceIds=[...new Set([...existing.sourceIds,...sourceIds])];}
  const env=delivery.environments.find(e=>e.id===envId)!;
  if(facetLabel.trim()&&!env.bindings?.some(b=>b.kind===facet&&b.label===facetLabel.trim()))(env.bindings??=[]).push({kind:facet,label:facetLabel.trim(),sourceIds,visibility:'private'});
  if(action==='not-applicable'){
   if(delivery.instances.some(i=>i.componentId===component&&i.environmentId===envId))throw new Error('An instance is already declared for this cell; review its removal before declaring not applicable');
   if(!reason.trim())throw new Error('Not-applicable requires an explicit author reason');const item={id:identity('applicability',component+'/'+envId),componentId:component,environmentId:envId,state:'not-applicable' as const,reason:reason.trim(),sourceIds,visibility:'private' as const};const items=delivery.applicability??=[];const at=items.findIndex(i=>i.id===item.id);if(at<0)items.push(item);else items[at]=item;
  }else if(action==='configuration'){
   if(!configName.trim())throw new Error('Name the configuration or flag; no raw value is collected');const item={id:identity('config',component+'/'+envId+'/'+configKind+'/'+configName.trim()),componentId:component,environmentId:envId,kind:configKind,name:configName.trim(),valueState,sourceIds,visibility:'private' as const};const items=delivery.configurations??=[];const at=items.findIndex(i=>i.id===item.id);if(at<0)items.push(item);else items[at]=item;
  }else{
   if(delivery.applicability?.some(i=>i.componentId===component&&i.environmentId===envId))throw new Error('Cell is declared not applicable; review that declaration before adding an instance');
   if(digest&&!/^sha256:[a-f0-9]{64}$/.test(digest))throw new Error('Artifact digest must be sha256 followed by 64 lowercase hexadecimal characters');
   const artifactId=version.trim()?identity('artifact',component+'/'+version.trim()+'/'+digest+'/'+build.trim()+'/'+revision.trim()):undefined;
   if(artifactId&&!delivery.artifacts.some(a=>a.id===artifactId))delivery.artifacts.push({id:artifactId,label:'Author-declared build artifact',version:version.trim(),digest:digest||undefined,sourceRevision:revision.trim()||undefined,buildId:build.trim()||undefined,sourceIds,visibility:'private'});
   const releaseId=release.trim()?identity('release',release.trim()):undefined;
   if(releaseId){if(!artifactId)throw new Error('A release requires an independently identified artifact');const existingRelease=delivery.releases?.find(r=>r.id===releaseId);if(existingRelease)existingRelease.artifactIds=[...new Set([...existingRelease.artifactIds,artifactId])];else(delivery.releases??=[]).push({id:releaseId,label:release.trim(),artifactIds:[artifactId],sourceIds,visibility:'private'});}
   const previous=delivery.instances.find(i=>i.componentId===component&&i.environmentId===envId),instanceId=previous?.id??identity('deployment',component+'/'+envId),item={id:instanceId,nodeId:previous?.nodeId??identity('instance',component+'/'+envId),componentId:component,environmentId:envId,artifactId:artifactId??previous?.artifactId,releaseId:releaseId??previous?.releaseId,declaredRevision:revision.trim()||previous?.declaredRevision,sourceIds:[...new Set([...(previous?.sourceIds??[]),...sourceIds])],visibility:previous?.visibility??'private' as const};
   if(previous)Object.assign(previous,item);else delivery.instances.push(item);
  }
  review(delivery);
 }catch(e){setError(e instanceof Error?e.message:String(e));}};
 const promote=()=>{setError('');try{if(!from||!to||from===to)throw new Error('Select two distinct declared environments');const delivery=structuredClone(project.delivery??initial()),id=identity('promotion',from+'/'+to+'/'+promotionArtifact),gates=gate.trim()?[{id:identity('gate',gate.trim()),label:gate.trim(),observationId:gateObservation||undefined}]:[],row={id,fromEnvironmentId:from,toEnvironmentId:to,artifactId:promotionArtifact||undefined,gates,sourceIds,visibility:'private' as const},at=delivery.promotions.findIndex(p=>p.id===id);if(at<0)delivery.promotions.push(row);else delivery.promotions[at]=row;review(delivery);}catch(e){setError(e instanceof Error?e.message:String(e));}};
 return <details open={!!project.delivery?.instances.length} aria-label="Environments and delivery"><summary>Environments and delivery</summary><p>Declarations, reviewed external claims and applicability are separate. A branch, data layer or region is not an environment. Revision differences do not prove health or rollout.</p>
  <div className="pi-controls"><label>Delivery search<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><label>Evidence age policy (hours)<input aria-label="Evidence age policy (hours)" type="number" min="0" max="8760" value={age} onChange={e=>setAge(Math.max(0,Math.min(8760,Number(e.target.value))))}/></label></div><p>Age is compared with this device's clock under your selected policy; timestamps are not live monitoring. {filtered.length} component × environment cells.</p>
  <div className="graph-table-scroll"><table><caption>Declared versus reviewed external instance claims</caption><thead><tr><th>Logical component</th><th>Environment</th><th>State</th><th>Independent artifact / release</th><th>Declared revision</th><th>External claim and freshness</th><th>Comparison</th></tr></thead><tbody>{visible.map(r=><tr key={r.componentId+'/'+r.environmentId}><td>{onOpen?<button onClick={()=>{const v=project.views.find(v=>v.nodeIds.includes(r.componentId));if(v)onOpen(v.id,r.componentId);}}>{r.component}</button>:r.component}</td><td>{r.environment}</td><td>{r.state}{r.reason&&<p>{r.reason}</p>}</td><td>{r.instances.map(i=><p key={i.id}>{i.artifact?.version??'UNKNOWN'} / {i.release?.label??'UNKNOWN'}</p>)}</td><td>{r.instances.map(i=><p key={i.id}>{i.declaredRevision}</p>)}</td><td>{r.instances.map(i=><p key={i.id}>{i.observed?i.observed.claim+' at '+i.observed.capturedAt+' by '+i.observed.authority:'UNKNOWN'} · {i.freshness}</p>)}</td><td>{r.instances.map(i=><p key={i.id}>{i.drift}</p>)}</td></tr>)}</tbody></table></div><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous delivery cells</button><span> Page {page+1} </span><button disabled={(page+1)*40>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next delivery cells</button>
  <details><summary>Public delivery figures</summary><p>Public projection only. Select publication visibility below in Edit mode, then review the patch. Each flat figure keeps declared links separate from dated reviewed external claims. Pan inside the figure to read it at full size.</p><label>Delivery figure profile<select aria-label="Delivery figure profile" value={profile} onChange={e=>{setProfile(e.target.value as DeliveryProfile);setFigurePage(0);setEnvironmentPage(0);}}>{DELIVERY_PROFILES.map(p=><option key={p} value={p}>{p}</option>)}</select></label><div className="graph-table-scroll"><img alt={'Public delivery '+profile+' figure'} src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(figure.svg)} style={{width:1152,maxWidth:'none',height:'auto'}}/></div><p>Page {figure.page+1} of {figure.totalPages} · {figure.shown} of {figure.total} {profile==='environment'?'cells':'declarations'} shown. Full identities are in the SVG element titles. Capture time {figure.at}; age policy {figure.maxAgeHours} hours.</p><button disabled={!figure.page} onClick={()=>setFigurePage(figure.page-1)}>Previous delivery figure page</button><button disabled={figure.page+1>=figure.totalPages} onClick={()=>setFigurePage(figure.page+1)}>Next delivery figure page</button>{profile==='environment'&&<><button disabled={!figure.environmentPage} onClick={()=>setEnvironmentPage(figure.environmentPage-1)}>Previous environment figure page</button><button disabled={figure.environmentPage+1>=figure.totalEnvironmentPages} onClick={()=>setEnvironmentPage(figure.environmentPage+1)}>Next environment figure page</button><span> Environment page {figure.environmentPage+1} of {figure.totalEnvironmentPages}</span></>}<button onClick={()=>download(figure.svg,project.id+'.delivery-'+profile+'-'+(figure.page+1)+'.public.svg','image/svg+xml')}>Download delivery SVG</button><button onClick={()=>{try{download(deliveryHtml(project,{at:figure.at,maxAgeHours:age}),project.id+'.delivery.public.html','text/html');}catch(e){setError(e instanceof Error?e.message:String(e));}}}>Download offline delivery HTML</button></details>
  {onPatch&&project.delivery&&<details><summary>Delivery publication choices</summary><p>Choose one declaration's visibility. Optional related closure publishes its required environments, artifacts, releases, logical component and instance cards, generated delivery view, and cited sources. Nested environment bindings, configurations, evidence blocks, images and observation review/shareable flags keep their existing choices.</p><div className="pi-controls"><label>Delivery publication type<select aria-label="Delivery publication type" value={publicationKind} onChange={e=>{setPublicationKind(e.target.value as DeliveryPublicationKind);setPublicationId('');}}>{['environments','artifacts','releases','instances','promotions','applicability','configurations'].map(kind=><option key={kind}>{kind}</option>)}</select></label><label>Delivery publication object<select aria-label="Delivery publication object" value={publicationId} onChange={e=>{setPublicationId(e.target.value);setPublicationVisibility(project.delivery?.[publicationKind]?.find(r=>r.id===e.target.value)?.visibility??'private');}}><option value="">Choose existing declaration</option>{project.delivery[publicationKind]?.map(row=><option key={row.id} value={row.id}>{'label' in row?row.label:row.id} · {row.visibility}</option>)}</select></label><label>Delivery publication visibility<select aria-label="Delivery publication visibility" value={publicationVisibility} onChange={e=>setPublicationVisibility(e.target.value as 'public'|'private')}><option value="private">Private</option><option value="public">Public</option></select></label><label><input aria-label="Include required declaration context and cited sources" type="checkbox" checked={related} onChange={e=>setRelated(e.target.checked)}/>Include required declaration context and cited sources</label></div><button disabled={!publicationId} onClick={()=>{try{setError('');onPatch(deliveryPublicationPatch(project,publicationKind,publicationId,publicationVisibility,related));}catch(e){setError(e instanceof Error?e.message:String(e));}}}>Review delivery publication choice</button></details>}
  <details><summary>Source → build → artifact → release → instance</summary>{chains.length?<ol>{chains.map(c=><li key={c.artifact.id}><strong>{c.artifact.label} {c.artifact.version}</strong><p>Source repository {c.sourceRepositoryId} · revision {c.sourceRevision} → build {c.buildId} → digest {c.digest} → releases {c.releases.map(r=>r.label).join(', ')||'UNKNOWN'} → {c.instances.length} declared instances. {c.basis}. This chain does not prove a deployment.</p></li>)}</ol>:<p>No build artifacts declared.</p>}</details>
  <details><summary>Environment scopes and nonsecret configuration</summary><ul>{project.delivery?.environments.map(e=><li key={e.id}>{e.label} · role {e.role??'UNKNOWN'} · {e.lifecycle??'unknown'}<ul>{e.bindings?.map((b,i)=><li key={i}>{b.kind}: {b.label} · {b.sourceIds.length?'cited declaration':'author declaration'}</li>)}</ul></li>)}</ul><ul>{project.delivery?.configurations?.map(c=><li key={c.id}>{project.nodes.find(n=>n.id===c.componentId)?.label} / {project.delivery?.environments.find(e=>e.id===c.environmentId)?.label}: {c.kind} {c.name} · {c.valueState} · declaration. Values are not stored.</li>)}</ul></details>
  <details><summary>Promotion topology and environment comparison</summary><div className="pi-controls"><label>From environment<select aria-label="From environment" value={from} onChange={e=>setFrom(e.target.value)}><option value="">Select</option>{project.delivery?.environments.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></label><label>To environment<select aria-label="To environment" value={to} onChange={e=>setTo(e.target.value)}><option value="">Select</option>{project.delivery?.environments.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></label></div><ul>{comparison.map(c=><li key={c.componentId}>{c.component}: declarations {c.declaredComparison}; fresh reviewed external revisions {c.observedComparison}. No health verdict.</li>)}</ul><ol>{gates.map(p=><li key={p.id}>{project.delivery?.environments.find(e=>e.id===p.fromEnvironmentId)?.label} → {project.delivery?.environments.find(e=>e.id===p.toEnvironmentId)?.label} · declared promotion<ul>{p.gates.map(g=><li key={g.id}>{g.label}: {g.result?.claim??'UNKNOWN'} · {g.freshness} · {g.revisionMatch}{g.result&&' by '+g.result.authority+' at '+g.result.observedAt}. A linked claim is not an executed gate.</li>)}</ul></li>)}</ol>{onDelivery&&<fieldset><legend>Declare promotion and evidence gate</legend><label>Promotion artifact<select value={promotionArtifact} onChange={e=>setPromotionArtifact(e.target.value)}><option value="">Unknown</option>{project.delivery?.artifacts.map(a=><option key={a.id} value={a.id}>{a.label} {a.version}</option>)}</select></label><label>Gate label<input value={gate} maxLength={160} onChange={e=>setGate(e.target.value)}/></label><label>Existing reviewed gate evidence<select value={gateObservation} onChange={e=>setGateObservation(e.target.value)}><option value="">Unknown</option>{project.observations.filter(o=>o.reviewedAt).map(o=><option key={o.id} value={o.id}>{o.claim} · {o.authority} · {o.observedAt}</option>)}</select></label><button disabled={!from||!to||from===to} onClick={promote}>Review promotion declaration</button></fieldset>}</details>
  {onDelivery&&<fieldset><legend>Add an author declaration</legend><div className="pi-controls"><label>Deployment component<select aria-label="Deployment component" value={component} onChange={e=>setComponent(e.target.value)}><option value="">Select existing logical component</option>{components.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label>Environment name<input aria-label="Environment name" list="delivery-environments" value={environment} maxLength={160} onChange={e=>{setEnvironment(e.target.value);const existing=project.delivery?.environments.find(env=>env.label===e.target.value);if(existing){setRole(existing.role??'');setLifecycle(existing.lifecycle??'unknown');}}}/><datalist id="delivery-environments">{project.delivery?.environments.map(e=><option key={e.id}>{e.label}</option>)}</datalist></label><label>Environment role<input value={role} maxLength={80} onChange={e=>setRole(e.target.value)}/></label><label>Environment lifecycle<select value={lifecycle} onChange={e=>setLifecycle(e.target.value as typeof lifecycle)}><option value="unknown">Unknown</option><option value="persistent">Persistent</option><option value="ephemeral">Ephemeral</option></select></label><label>Declaration type<select aria-label="Declaration type" value={action} onChange={e=>setAction(e.target.value as typeof action)}><option value="instance">Deployment instance</option><option value="not-applicable">Not applicable</option><option value="configuration">Nonsecret configuration</option></select></label></div>
   {action==='instance'?<div className="pi-controls"><label>Artifact version (optional)<input aria-label="Artifact version" value={version} maxLength={160} onChange={e=>setVersion(e.target.value)}/></label><label>Declared source revision<input value={revision} maxLength={120} onChange={e=>setRevision(e.target.value)}/></label><label>Artifact SHA-256 digest<input value={digest} maxLength={71} onChange={e=>setDigest(e.target.value)}/></label><label>Build identity<input value={build} maxLength={160} onChange={e=>setBuild(e.target.value)}/></label><label>Release identity<input value={release} maxLength={160} onChange={e=>setRelease(e.target.value)}/></label></div>:action==='not-applicable'?<label>Applicability reason<textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></label>:<div className="pi-controls"><label>Configuration kind<select value={configKind} onChange={e=>setConfigKind(e.target.value as typeof configKind)}><option value="configuration">Configuration</option><option value="flag">Feature flag</option></select></label><label>Configuration name<input value={configName} maxLength={160} onChange={e=>setConfigName(e.target.value)}/></label><label>Declared configuration state<select aria-label="Declared configuration state" value={valueState} onChange={e=>setValueState(e.target.value as typeof valueState)}>{['unknown','configured','declared-enabled','declared-disabled'].map(s=><option key={s}>{s}</option>)}</select></label></div>}
   <details><summary>Optional typed environment facet and source citations</summary><div className="pi-controls"><label>Facet type<select value={facet} onChange={e=>setFacet(e.target.value as typeof facet)}>{['provider','tenant','scope','region','residency','backup','trust-boundary','owner'].map(s=><option key={s}>{s}</option>)}</select></label><label>Facet declaration<input value={facetLabel} maxLength={160} onChange={e=>setFacetLabel(e.target.value)}/></label><label>Declaration sources<select multiple value={sourceIds} onChange={e=>setSourceIds([...e.target.selectedOptions].map(o=>o.value))}>{project.sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label></div><p>Metadata only. No credential or raw configuration values. Backup and residency declarations do not establish recovery or compliance.</p></details><button disabled={!component||!environment.trim()} onClick={declare}>Review delivery declaration</button></fieldset>}{error&&<p role="alert">{error}</p>}
 </details>;
}
