import {Badge,Button} from '@fluentui/react-components';
import {useState} from 'react';
import type {EvidenceBlock,Project,ProjectNode} from '../core/model';
import {RealizationSection,type ObservationActions} from './Realization';
import {TRANSFORM_LABEL,TRANSFORM_NOTE,hasTransformation,transformationParts} from '../core/transform';

/** Input → logic → output side by side, then mappings and rules: an explanation, never an execution. */
function Transformation({blocks,doc}:{blocks:EvidenceBlock[];doc:Project}){const parts=transformationParts(blocks);return <section className="transformation" aria-label="Transformation"><div className="eyebrow">TRANSFORMATION</div><p className="micro">{TRANSFORM_NOTE}</p><div className="transform-flow">{(['input','logic','output'] as const).map((s,k)=><div key={s} className={`transform-step step-${s}`}><div className="transform-label">{k?<span aria-hidden="true">→ </span>:null}{TRANSFORM_LABEL[s]}</div>{(parts[s]??[]).map(b=><Evidence key={b.id} block={b} doc={doc}/>)}</div>)}</div>{(['mapping','rules'] as const).map(s=>(parts[s]??[]).map(b=><Evidence key={b.id} block={b} doc={doc}/>))}</section>;}
export function Evidence({block,doc}:{block:EvidenceBlock;doc:Project}){const [copied,setCopied]=useState(false);return <article className="evidence-block" data-testid={`block-${block.id}`}><div className="evidence-heading"><h3>{block.title}</h3><Badge appearance="tint" color={block.provenance==='synthetic'?'warning':'informative'} size="small">{block.provenance}</Badge></div>{block.type==='text'&&<p className="prose">{block.text}</p>}{block.type==='code'&&<><div className="code-toolbar"><span>{block.language.toUpperCase()} · display only</span><Button size="small" appearance="subtle" onClick={()=>{navigator.clipboard?.writeText(block.code).then(()=>setCopied(true)).catch(()=>setCopied(false));}}>{copied?'Copied':'Copy'}</Button></div><pre><code>{block.code}</code></pre></>}{block.type==='table'&&<div className="table-scroll"><table><thead><tr>{block.columns.map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{block.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell===null?'—':String(cell)}</td>)}</tr>)}</tbody></table><span className="micro">{block.rows.length} rows · example data is not executed or connected</span></div>}{block.type==='metrics'&&<div className="metrics">{block.items.map((i,index)=><div key={index}><strong>{i.value}</strong><span>{i.label}</span><small>{i.note}</small></div>)}</div>}{block.type==='image'&&(()=>{const asset=doc.assets.find(a=>a.id===block.assetId);return asset?<figure><img src={asset.data} alt={block.caption||block.title}/><figcaption>{block.caption}{asset.remote?.provider==='google-drive'&&<><br/><Badge appearance="tint" size="small">Drive-backed · cached locally</Badge></>}<br/><small>{asset.rights}</small></figcaption></figure>:null;})()}</article>;}
export function NodeEvidence({doc,node,actions}:{doc:Project;node:ProjectNode;actions?:ObservationActions}){const blocks=doc.blocks.filter(b=>node.blockIds.includes(b.id));const sources=new Set([...node.sourceIds,...blocks.flatMap(b=>b.sourceIds)]);return <>{node.role&&<section className="contribution"><div className="eyebrow">MY CONTRIBUTION</div><p>{node.role}</p></section>}{hasTransformation(blocks)&&<Transformation blocks={blocks.filter(b=>b.transform)} doc={doc}/>}{blocks.length?blocks.filter(b=>!hasTransformation(blocks)||!b.transform).map(b=><Evidence key={b.id} block={b} doc={doc}/>):<div className="empty-evidence"><span className="empty-glyph">↳</span><h3>{node.childViewId?'The work is one level deeper':'Make this component explainable'}</h3><p>{node.childViewId?'Explore its child diagram below. Select one of the tasks to see code, sample rows and implementation notes.':'This component has no evidence blocks yet. In Edit mode, attach an explanation, code, a table or an image.'}</p></div>}<RealizationSection doc={doc} node={node} actions={actions}/>{sources.size>0&&<section className="sources"><h3>Sources & provenance</h3>{doc.sources.filter(s=>sources.has(s.id)).map(s=><div key={s.id}>{s.url?<a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} ↗</a>:<strong>{s.title}</strong>}<p>{s.location}</p></div>)}</section>}</>;}
