import {useMemo,useState} from 'react';
import {parseDocument,type Project} from '../core/model';
import type {Patch} from '../core/patch';
import {evolutionSnapshot,compareEvolutionSnapshots,readEvolutionHistory,retainEvolutionSnapshotPatch,migrationPlanPatch,evolutionRecipes,type EvolutionSnapshot,type MigrationPlan} from '../intelligence/evolution';
import {secretFindings} from '../core/secrets';
import {download} from '../export/browser';
/** A transient comparison of a selected backup; never imports or rewrites facts. */
export function EvolutionPanel({project,onOpen,onPatch}:{project:Project;onOpen:(view:string,node?:string)=>void;onPatch?:(patch:Patch)=>void}){
 const history=useMemo(()=>readEvolutionHistory(project),[project]),current=useMemo(()=>evolutionSnapshot(project,{id:'current-revision-'+project.revision}),[project]);
 const [previous,setPrevious]=useState<EvolutionSnapshot>(),[beforeId,setBeforeId]=useState(''),[afterId,setAfterId]=useState('current'),[error,setError]=useState(''),[recipe,setRecipe]=useState('project'),[changeKind,setChangeKind]=useState(''),[snapshotLabel,setSnapshotLabel]=useState('');
 const [editingPlanId,setEditingPlanId]=useState<string>(),[planLabel,setPlanLabel]=useState('Migration plan'),[cutover,setCutover]=useState(''),[coexistence,setCoexistence]=useState(''),[rollback,setRollback]=useState(''),[phases,setPhases]=useState<MigrationPlan['phases']>(()=>['current','transition','target','rollback'].map(stage=>({id:stage,label:stage,stage:stage as MigrationPlan['phases'][number]['stage'],basis:'planned',nodeIds:[],sourceIds:[],note:''})));
 const before=beforeId?history.snapshots.find(s=>s.id===beforeId):previous,after=afterId==='current'?current:history.snapshots.find(s=>s.id===afterId)??current;
 const comparison=useMemo(()=>before?compareEvolutionSnapshots(before,after):undefined,[before,after]);
 const recipes=evolutionRecipes(after),members=new Set(recipes.find(r=>r.kind===recipe)?.entities.map(e=>e.id)),changes=comparison?.changes.filter(c=>(!changeKind||c.change===changeKind)&&(c.entity==='connection'||members.has(c.id)||(before?.nodes.find(n=>n.id===c.id)?.perspectives.some(p=>recipe==='data'?p==='data':recipe==='work'?p==='agents':recipe==='repository'?['code','git','cicd'].includes(p):recipe==='knowledge'?['decisions','evidence'].includes(p):['system','cloud'].includes(p)))))??[];
 const emit=(patch:Patch)=>{if(onPatch)onPatch(patch);else download(JSON.stringify(patch,null,2),project.id+'.evolution.patch.json','application/json');};
 const retain=(snapshot:EvolutionSnapshot)=>{setError('');try{emit(retainEvolutionSnapshotPatch(project,{...snapshot,id:'snapshot-'+crypto.randomUUID().slice(0,12),label:snapshotLabel.trim()||snapshot.label}));}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const plan=()=>{setError('');try{emit(migrationPlanPatch(project,{format:'diagramcloud.migration-plan/1',id:editingPlanId??'migration-'+planLabel.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,50),projectId:project.id,label:planLabel,phases,cutover:cutover||'UNKNOWN',coexistence:coexistence||'UNKNOWN',rollback:rollback||'UNKNOWN'}));}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const read=async(file?:File)=>{if(!file)return;setPrevious(undefined);setBeforeId('');setError('');try{
  if(file.size>12*1024*1024)throw new Error('Previous document exceeds 12 MiB');
  const before=parseDocument(await file.text());if(before.id!==project.id)throw new Error('Evolution requires versions of the same project');if(secretFindings(before).length)throw new Error('Sensitive previous document refused');
  setPrevious(evolutionSnapshot(before));
 }catch(e){setError(e instanceof Error?e.message:String(e));}};
 return <details aria-label="Project Evolution"><summary>Project Evolution · compare a previous backup</summary><p>Select a previous authoring JSON for this project. Comparison is local and does not import it. Missing components remain not-in-scope; reviewed external claims and presentation changes stay distinct. Retained snapshots are immutable private receipts, not a deployment timeline.</p><label>Previous project JSON<input aria-label="Previous project JSON" type="file" accept=".json,application/json" onChange={e=>{void read(e.target.files?.[0]);e.target.value='';}}/></label>
  <div className="pi-controls"><label>Before snapshot<select aria-label="Before snapshot" value={beforeId} onChange={e=>setBeforeId(e.target.value)}><option value="">Selected previous backup</option>{history.snapshots.map(s=><option key={s.id} value={s.id}>{s.label} · {s.capturedAt}</option>)}</select></label><label>After snapshot<select aria-label="After snapshot" value={afterId} onChange={e=>setAfterId(e.target.value)}><option value="current">Current document</option>{history.snapshots.map(s=><option key={s.id} value={s.id}>{s.label} · {s.capturedAt}</option>)}</select></label><label>Snapshot label<input value={snapshotLabel} maxLength={160} onChange={e=>setSnapshotLabel(e.target.value)}/></label><button onClick={()=>retain(current)}>Review retaining current snapshot</button>{previous&&<button onClick={()=>retain(previous)}>Review retaining selected previous snapshot</button>}</div><p>{history.snapshots.length} of 12 snapshots retained. Every receipt records source collection time, parser/profile and independent repository revisions. Retaining never imports components or reviews claims.</p>
  {error&&<p role="alert">{error}</p>}{comparison&&<><p>Document revision {comparison.before.documentRevision} → {comparison.after.documentRevision} · {comparison.state}</p><p>{comparison.before.label} at {comparison.before.capturedAt} → {comparison.after.label} at {comparison.after.capturedAt}. Analyzer {comparison.after.sourceIdentity.analyzerVersion}; profile {comparison.after.sourceIdentity.profile}.</p><ul>{comparison.after.revisionVector.map(r=><li key={r.id}>{r.id}: {r.revision} · collected {r.collectedAt??'UNKNOWN'} · {r.authority}</li>)}</ul><ul>{comparison.reasons.map(r=><li key={r}>{r}</li>)}</ul><div className="pi-controls"><label>Evolution scope<select value={recipe} onChange={e=>setRecipe(e.target.value)}>{recipes.map(r=><option key={r.kind}>{r.kind}</option>)}</select></label><label>Evolution change type<select value={changeKind} onChange={e=>setChangeKind(e.target.value)}><option value="">All changes</option>{['added','changed','removed','not-in-scope','moved','presentation','confidence','verification'].map(c=><option key={c}>{c}</option>)}</select></label></div><ol aria-label="Evolution diff rail">{changes.slice(0,500).map((c,i)=>{const node=project.nodes.find(n=>n.id===c.id),view=project.views.find(v=>v.nodeIds.includes(c.id));return <li key={c.id+'-'+c.change+'-'+i}><strong>{c.change} · {node?.label??c.id}</strong><p>{c.reason}{c.before||c.after?' · '+(c.before??'UNKNOWN')+' → '+(c.after??'UNKNOWN'):''}</p><ul>{c.sourceRefs.length?c.sourceRefs.map((r,j)=><li key={j}>{r}</li>):<li>Source UNKNOWN; authoring/planned context only</li>}</ul>{view&&<button onClick={()=>onOpen(view.id,c.id)}>Open current component</button>}</li>;})}{!changes.length&&<li>No changes in this selected scope. Missing evidence remains unknown.</li>}</ol>{changes.length>500&&<p>Display limited to 500 changes; the comparison JSON contains the complete result.</p>}<h4>Evidence freshness</h4><ul>{comparison.staleEvidence.map(c=><li key={c.nodeId+'/'+c.id}>{project.nodes.find(n=>n.id===c.nodeId)?.label??c.nodeId}: {c.claim} by {c.authority} at {c.observedAt}, source revision {c.sourceRevision} · {c.freshness}. This claim does not verify the selected source revision.</li>)}</ul><p>{comparison.note}.</p><button onClick={()=>download(JSON.stringify(comparison,null,2),project.id+'.evolution.private.json','application/json')}>Download private comparison JSON</button></>}
  <details><summary>Current → transition → target and rollback plan</summary><p>These phases are authored intent. Current is a planning baseline; none is labelled deployed. Component and source pointers use existing IDs.</p>{history.plans.map(p=><article key={p.id}><h4>{p.label}</h4><ol>{p.phases.map(f=><li key={f.id}>{f.stage} · {f.label} · {f.basis}<p>{f.note||'UNKNOWN'}</p><ul>{f.nodeIds.map(id=><li key={id}>{project.nodes.find(n=>n.id===id)?.label??id} · {project.nodes.some(n=>n.id===id)?'existing component':'not in current scope'}</li>)}</ul><p>Sources: {f.sourceIds.map(id=>project.sources.find(s=>s.id===id)?.location??'not in current scope').join('; ')||'UNKNOWN'}</p></li>)}</ol><p>Coexistence: {p.coexistence}. Cutover: {p.cutover}. Rollback: {p.rollback}.</p><button onClick={()=>{setEditingPlanId(p.id);setPlanLabel(p.label);setPhases(p.phases);setCutover(p.cutover);setCoexistence(p.coexistence);setRollback(p.rollback);}}>Edit plan declaration</button></article>)}<fieldset><legend>Author migration plan</legend>{editingPlanId&&<p>Editing stable plan ID {editingPlanId} <button onClick={()=>{setEditingPlanId(undefined);setPlanLabel('Migration plan');}}>Start another plan</button></p>}<label>Migration plan label<input value={planLabel} maxLength={160} onChange={e=>setPlanLabel(e.target.value)}/></label>{phases.map((phase,i)=><fieldset key={phase.id}><legend>{phase.stage} · planned/unknown</legend><label>Phase meaning<select value={phase.basis} onChange={e=>setPhases(p=>p.map((x,j)=>j===i?{...x,basis:e.target.value as 'planned'|'unknown'}:x))}><option value="planned">Planned</option><option value="unknown">Unknown</option></select></label><label>{phase.stage} components<select aria-label={phase.stage+" components"} multiple value={phase.nodeIds} onChange={e=>{const ids=[...e.target.selectedOptions].map(o=>o.value);setPhases(p=>p.map((x,j)=>j===i?{...x,nodeIds:ids}:x));}}>{project.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label>{phase.stage} sources<select aria-label={phase.stage+" sources"} multiple value={phase.sourceIds} onChange={e=>{const ids=[...e.target.selectedOptions].map(o=>o.value);setPhases(p=>p.map((x,j)=>j===i?{...x,sourceIds:ids}:x));}}>{project.sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>{phase.stage} contribution and constraints<textarea value={phase.note} maxLength={2000} onChange={e=>setPhases(p=>p.map((x,j)=>j===i?{...x,note:e.target.value}:x))}/></label></fieldset>)}<label>Coexistence intent<textarea value={coexistence} maxLength={2000} onChange={e=>setCoexistence(e.target.value)}/></label><label>Cutover intent<textarea value={cutover} maxLength={2000} onChange={e=>setCutover(e.target.value)}/></label><label>Rollback intent<textarea value={rollback} maxLength={2000} onChange={e=>setRollback(e.target.value)}/></label><button disabled={!planLabel.trim()} onClick={plan}>Review migration plan</button></fieldset></details>
 </details>;
}
