import {useMemo,useState} from 'react';
import type {Project} from '../core/model';
import {publicDocument} from '../core/operations';
import {renderPublicArtifact} from '../intelligence/context';
import {compareRenderCandidates} from '../intelligence/visualQuality';
type Quality={semantic:{state:string;checks:{id:string;state:string;reason:string}[]};viewId:string;checks:{svgDocument:boolean;accessibleTitle:boolean;offline:boolean};geometry:{failures:string[];texts:number;unresolved:number;components:number;unresolvedShapes:number};qualification:string;note:string};
export function FigureQualityPanel({project}:{project:Project}){
 const doc=useMemo(()=>publicDocument(project),[project]),[viewId,setViewId]=useState(''),[result,setResult]=useState<Quality>(),[error,setError]=useState(''),[comparison,setComparison]=useState<ReturnType<typeof compareRenderCandidates>>();
 const selected=doc.views.some(v=>v.id===viewId)?viewId:doc.rootViewId;
 const inspect=()=>{try{setResult(renderPublicArtifact(project,{kind:'quality',viewId:selected}) as Quality);setError('');}catch(e){setResult(undefined);setError(e instanceof Error?e.message:'Figure check failed');}};
 const compare=()=>{try{setComparison(compareRenderCandidates(project,selected));setError('');}catch(e){setComparison(undefined);setError(e instanceof Error?e.message:'Candidate comparison failed');}};
 const download=(proposal:unknown,id:string)=>{const u=URL.createObjectURL(new Blob([JSON.stringify(proposal,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=project.id+'.candidate-'+id+'.design-brief.json';a.click();URL.revokeObjectURL(u);};
 return <details><summary>Figure geometry and offline quality</summary><p>Check one selected public figure with the same text and shape budgets used by release tests. Checks never change semantics or imply human qualification.</p><label>Public quality view<select aria-label="Public quality view" value={selected} onChange={e=>{setViewId(e.target.value);setResult(undefined);setComparison(undefined);}}>{doc.views.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><button onClick={inspect}>Check selected figure geometry</button><button onClick={compare}>Compare render candidates A/B/C</button>{error&&<p role="alert">{error}</p>}{result&&<div aria-label="Figure quality result"><p>{result.qualification} · {result.geometry.texts} measured text boxes · {result.geometry.components} component shapes · {result.geometry.failures.length} defects · {result.geometry.unresolved+result.geometry.unresolvedShapes} unresolved transforms.</p><p>SVG {String(result.checks.svgDocument)} · accessible title {String(result.checks.accessibleTitle)} · offline {String(result.checks.offline)}. {result.note}</p><p>Semantic encoding: {result.semantic.state}.</p><ul>{result.semantic.checks.map(c=><li key={c.id}>{c.id}: {c.state}. {c.reason}</li>)}</ul><ul>{result.geometry.failures.slice(0,100).map((f,i)=><li key={i}>{f}</li>)}</ul>{result.geometry.failures.length>100&&<p>More than 100 defects; narrow the selected figure.</p>}</div>}{comparison&&<div aria-label="Render candidate comparison"><p>{comparison.note}</p><p>Penalties: semantic defect {comparison.weights.semanticDefect}, geometry defect {comparison.weights.geometricDefect}; unresolved transform, source-layout crossing and source-scene truncation each 1 (bounded penalties).</p><ol>{comparison.candidates.map(c=><li key={c.id}><strong>{c.id}: {c.figure}</strong> · score {c.score}/100 · suitability {c.suitability}/100. {c.reason}<img alt={"Candidate "+c.id+": "+c.figure+" public figure"} src={"data:image/svg+xml;charset=utf-8,"+encodeURIComponent(c.svg)} style={{width:"100%",height:"auto",maxHeight:420,objectFit:"contain"}}/><p>Geometry defects {c.metrics.geometricDefects}, semantic defects {c.metrics.semanticDefects}, unresolved transforms {c.metrics.unresolvedTransforms}, common source-layout crossings {c.metrics.sourceLayoutCrossings}, common scene truncations {c.metrics.sourceSceneTruncations}, SVG bytes {c.metrics.svgBytes}. {c.semantic.state}</p><ul>{c.semantic.checks.map(check=><li key={check.id}>{check.id}: {check.state}. {check.reason}</li>)}</ul><button onClick={()=>download(c.proposal,c.id)}>Download candidate {c.id} for author review</button></li>)}</ol></div>}</details>;
}

