import {useState} from 'react';
import type {Project} from '../core/model';
import {howItWorksFacts,howItWorksHtml,type HowItWorksOptions} from '../export/howItWorks';
import {download} from '../export/browser';
export function HowItWorksPanel({project,publicMode,onOpen}:{project:Project;publicMode:boolean;onOpen?:(view:string,node?:string)=>void}){
 const [options,setOptions]=useState<HowItWorksOptions>({mode:project.story.length?'story':'path',viewId:project.rootViewId});
 const availableView=project.views.find(v=>v.id===options.viewId),resolved={...options,viewId:availableView?.id??project.rootViewId,startNodeId:availableView?.nodeIds.includes(options.startNodeId??'')?options.startNodeId:undefined};
 const facts=howItWorksFacts(project,resolved,publicMode),view=facts.project.views.find(v=>v.id===resolved.viewId);
 return <details aria-label="How it works sheet"><summary>How it works · authored story or selected path</summary><div className="pi-controls"><label>Step source<select value={options.mode} onChange={e=>setOptions({...options,mode:e.target.value as HowItWorksOptions['mode']})}><option value="story">Authored story</option><option value="path">Selected connection path</option></select></label>{options.mode==='path'&&<><label>Path view<select value={resolved.viewId} onChange={e=>setOptions({...options,viewId:e.target.value,startNodeId:undefined})}>{facts.project.views.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><label>Path starting component<select value={resolved.startNodeId??''} onChange={e=>setOptions({...options,startNodeId:e.target.value||undefined})}><option value="">Use an unambiguous start</option>{view?.nodeIds.map(id=>facts.project.nodes.find(n=>n.id===id)!).map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label></>}</div><div className="pi-overview-grid">{facts.steps.map((step,i)=><article key={step.key} className="pi-component"><span className="pi-eyebrow">{i+1} · {step.basis}</span><h3>{step.title}</h3><p>{step.business}</p><p className="micro">{step.technical}</p><ul>{step.sourceIds.map(id=>facts.project.sources.find(s=>s.id===id)).filter(s=>!!s).map(s=><li key={s!.id}>{s!.title} · {s!.location}</li>)}</ul>{onOpen&&<button onClick={()=>onOpen(step.viewId,step.nodeId)}>Open supplied step</button>}</article>)}</div><ul>{facts.notes.map(note=><li key={note}>{note}</li>)}</ul><button onClick={()=>download(howItWorksHtml(project,resolved),project.id+'.how-it-works.html','text/html')}>Export public How it works sheet</button></details>;
}
