import {useMemo,useState} from 'react';
import type {Project} from '../core/model';
import {recommendRecipes,impactFacts,knowledgeFacts} from '../intelligence/recipes';
import {DEFAULT_OPTIONS,type AnalysisOptions} from '../intelligence/types';
import {environmentMatrix,deliveryGates} from '../intelligence/delivery';

export function IntelligenceInsights({project,onOpen,onDelivery}:{project:Project;onOpen:(view:string,node?:string)=>void;onDelivery?:(input:unknown)=>void}){
 const [options,setOptions]=useState<AnalysisOptions>({...DEFAULT_OPTIONS}),[subject,setSubject]=useState(''),[direction,setDirection]=useState<'upstream'|'downstream'>('downstream');
 const [component,setComponent]=useState(''),[environment,setEnvironment]=useState(''),[version,setVersion]=useState('');
 const recipes=useMemo(()=>recommendRecipes(project,options),[project,options]),knowledge=useMemo(()=>knowledgeFacts(project),[project]);
 const impact=useMemo(()=>subject&&project.nodes.some(n=>n.id===subject)?impactFacts(project,subject,{direction,includeInferred:options.includeInferred,limit:options.depth==='quick'?24:60}):null,[project,subject,direction,options.includeInferred,options.depth]);
 const matrix=environmentMatrix(project),gates=deliveryGates(project);
 const declare=()=>{if(!component||!environment.trim())return;const slug=environment.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,35);if(!slug)return;
  const envId='env-'+slug,instance='deployment-'+component+'-'+slug;
  const delivery=structuredClone(project.delivery??{environments:[],artifacts:[],instances:[],promotions:[]});
  if(!delivery.environments.some(e=>e.id===envId))delivery.environments.push({id:envId,label:environment.trim(),description:'Author-declared environment',sourceIds:[],visibility:'private'});
  const artifactId=version.trim()?'artifact-'+component+'-'+slug+'-'+version.trim().replace(/[^a-z0-9]+/gi,'-').slice(0,35):undefined;
  if(artifactId&&!delivery.artifacts.some(a=>a.id===artifactId))delivery.artifacts.push({id:artifactId,label:'Author-declared artifact',version:version.trim(),sourceIds:[],visibility:'private'});
  const row={id:instance,nodeId:instance,componentId:component,environmentId:envId,artifactId,sourceIds:[],visibility:'private' as const};
  const at=delivery.instances.findIndex(i=>i.id===instance);if(at<0)delivery.instances.push(row);else delivery.instances[at]=row;
  onDelivery?.({format:'diagramcloud.delivery-brief',version:1,projectId:project.id,baseRevision:project.revision,delivery});
 };
 return <section className="project-overview intelligence-insights" aria-label="Project intelligence workbench"><h2>Useful views and source questions</h2><div className="pi-controls"><label>View purpose<select aria-label="View purpose" value={options.purpose} onChange={e=>setOptions(o=>({...o,purpose:e.target.value as AnalysisOptions['purpose']}))}>{['understand','project','portfolio','presentation','audit'].map(p=><option key={p}>{p}</option>)}</select></label><label>View detail<select aria-label="View detail" value={options.depth} onChange={e=>setOptions(o=>({...o,depth:e.target.value as AnalysisOptions['depth']}))}><option value="quick">Quick · 24 components in impact and previews</option><option value="standard">Standard · 60 components per overview</option></select></label></div>
  <ul>{recipes.map(r=><li key={r.id}><strong>{r.title}</strong> · {r.availability} · {r.reason} · suggested {r.figure}. <details><summary>Preview matching components (up to {r.maxNodes})</summary><ul>{[...new Set(project.views.filter(v=>r.viewIds.includes(v.id)).flatMap(v=>v.nodeIds))].slice(0,r.maxNodes).map(id=><li key={id}>{project.nodes.find(n=>n.id===id)?.label}</li>)}</ul></details> {r.viewIds.length>0&&<button onClick={()=>onOpen(r.viewIds[0])}>Open existing view</button>}</li>)}</ul>
  <details><summary>Source-backed impact and check gaps</summary><div className="pi-controls"><label>Impact component<select aria-label="Impact component" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Select a component</option>{project.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label>Direction<select aria-label="Impact direction" value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="downstream">Downstream</option><option value="upstream">Upstream</option></select></label><label><input type="checkbox" checked={options.includeInferred} onChange={e=>setOptions(o=>({...o,includeInferred:e.target.checked}))}/> Include unknown basis</label></div>
   {impact&&<><p>{impact.nodes.length} reachable components · {impact.edges.length} supplied connections{impact.limited?' · bounded at '+(options.depth==='quick'?24:60)+' components':''}. Reachability is not causal impact or a coverage percentage.</p><ul>{impact.nodes.map(n=><li key={n.id}>{n.label} · {n.basis??'unknown'}</li>)}</ul><h4>Check evidence gaps</h4><ul>{impact.gaps.map(g=><li key={g.nodeId}>{project.nodes.find(n=>n.id===g.nodeId)?.label}: {g.reason}</li>)}</ul></>}
  </details>
  <details><summary>Knowledge and source library</summary><ul>{knowledge.documents.map(d=><li key={d.path}><code>{d.path}</code><ul>{d.headings.slice(0,20).map((h,i)=><li key={i}>line {h.line}: {h.title}</li>)}</ul></li>)}</ul><ul>{knowledge.links.map((l,i)=><li key={i}>{l.fromPath}:{l.fromLine} → {l.toPath}{l.toLine?':'+l.toLine:''} · explicit {l.kind}</li>)}</ul>{!knowledge.documents.length&&<p>No supported selected document map is attached in this projection.</p>}<p>{knowledge.limitations.join(' ')}</p></details>
  <details open={matrix.length>0}><summary>Environments and delivery</summary><p>Environment identities, source branches and repository revisions are separate. A declaration is not a live deployment; a revision difference does not prove unhealthy production.</p>
   <div className="graph-table-scroll"><table><caption>Declared versus reviewed external instance claims</caption><thead><tr><th>Component</th><th>Environment</th><th>Artifact</th><th>Declared revision</th><th>Observed claim</th><th>Comparison</th></tr></thead><tbody>{matrix.map(i=><tr key={i.id}><td>{i.component}</td><td>{i.environment}</td><td>{i.artifact?.version??'UNKNOWN'}</td><td>{i.declaredRevision}</td><td>{i.observed?i.observed.claim+' at '+i.observed.capturedAt+' by '+i.observed.authority:'UNKNOWN'}</td><td>{i.drift}</td></tr>)}</tbody></table></div>
   {gates.map(p=><p key={p.id}>{project.delivery?.environments.find(e=>e.id===p.fromEnvironmentId)?.label} → {project.delivery?.environments.find(e=>e.id===p.toEnvironmentId)?.label}: {p.gates.length?p.gates.map(g=>g.label+' ('+(g.result?.claim??'UNKNOWN')+')').join('; '):'No gate declared'}</p>)}
   {onDelivery&&<fieldset><legend>Add an author declaration</legend><div className="pi-controls"><label>Deployment component<select aria-label="Deployment component" value={component} onChange={e=>setComponent(e.target.value)}><option value="">Select existing component</option>{project.nodes.filter(n=>!n.childViewId).map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label>Environment name<input aria-label="Environment name" value={environment} maxLength={160} onChange={e=>setEnvironment(e.target.value)}/></label><label>Artifact version (optional)<input aria-label="Artifact version" value={version} maxLength={160} onChange={e=>setVersion(e.target.value)}/></label><button disabled={!component||!environment.trim()} onClick={declare}>Review delivery declaration</button></div></fieldset>}
  </details>
 </section>;
}
