import {useState} from 'react';
import type {Project} from '../core/model';
import {ICON_REGISTRY} from '../core/icons';
import {overviewProjection} from '../export/projectOverview';
import {download} from '../export/browser';
import {projectReadiness} from '../intelligence/readiness';
import {planAssets, assetChecklistCsv} from '../intelligence/assets';
import type {DocumentMap, Purpose} from '../intelligence/types';
import './project-intelligence.css';

export function ProjectContext({project, purpose = 'understand', publicMode = false, documents, onReviewedProposal}: {project: Project; purpose?: Purpose; publicMode?: boolean; documents?: DocumentMap; onReviewedProposal?: () => void}) {
  const [tab, setTab] = useState('evidence'), [message, setMessage] = useState('');
  const p = overviewProjection(project, publicMode), report = projectReadiness(p, {purpose}), assets = planAssets(p, ICON_REGISTRY);
  const docs = publicMode ? undefined : documents;
  const copy = async () => {try {await navigator.clipboard.writeText(JSON.stringify({project: p, readiness: report, assets}, null, 2));setMessage('Context copied. Manual assistance: proposals still require review.');} catch {setMessage('Clipboard unavailable. Download context instead.');}};
  return <aside className="project-context" aria-label="Project context" data-testid="project-context"><div className="pi-tabs" role="tablist" aria-label="Context scope">{['evidence','gaps','assets'].map(t => <button type="button" id={`context-tab-${t}`} role="tab" aria-controls="project-context-panel" aria-selected={tab === t} key={t} onClick={() => setTab(t)}>{t[0].toUpperCase() + t.slice(1)}</button>)}</div><div id="project-context-panel" role="tabpanel" aria-labelledby={`context-tab-${tab}`}><p className="micro">{publicMode ? 'Public projection' : 'Private authoring context'} · revision {p.revision}</p>
    {tab === 'evidence' && <><h3>Source provenance</h3><p className="micro">{p.provenance || 'Provenance not supplied.'}</p><ul>{p.sources.map(s => <li key={s.id}><strong>{s.title}</strong><small>{s.location}</small></li>)}</ul>{!p.sources.length && <p>No source references in this projection.</p>}<h3>Evidence</h3><ul>{p.blocks.slice(0,20).map(b => <li key={b.id}>{b.title}<small>{b.provenance} · {b.visibility}</small></li>)}</ul>{docs && <><h3>Selected documents</h3><ul>{docs.documents.map(d => <li key={d.path}><code>{d.path}</code><small>{d.kind} · {d.headings.length} headings · {d.records.length} records</small>{d.headings.slice(0,6).map(h => <small key={`${h.line}-${h.title}`}>:{h.line} {h.title}</small>)}</li>)}</ul><h4>Exact provenance links</h4><ul>{docs.links.slice(0,40).map((l,i) => <li key={i}><code>{l.fromPath}:{l.fromLine} → {l.toPath}{l.toLine ? `:${l.toLine}` : ''}</code><small>{l.kind}; locator only, no file/network fetch</small></li>)}</ul><p className="micro">Omitted: {docs.omitted.documents} documents; {docs.omitted.links} links.</p></>}<details><summary>Manual assistance</summary><p className="micro">Copy this projection for an external assistant. Nothing executes here; review every proposed change.</p><button type="button" onClick={() => void copy()}>Copy context</button><button type="button" onClick={() => download(JSON.stringify({project: p, readiness: report, assets}, null,2), `${p.id}.context.json`, 'application/json')}>Download context</button>{onReviewedProposal && <button type="button" onClick={onReviewedProposal}>Import reviewed proposal</button>}{message && <p role="status">{message}</p>}</details></>}
    {tab === 'gaps' && <><h3>Information gaps</h3>{report.gaps.length ? <ul>{report.gaps.map(g => <li key={g.id}><strong>{g.title}</strong><small>{g.state}</small><p>{g.reason}</p><p className="micro">{g.resolution}</p></li>)}</ul> : <p>No contextual gap detected by these limited rules.</p>}{docs && <><h3>Document diagnostics</h3><ul>{docs.diagnostics.map((d,i) => <li key={i}><code>{d.path}{d.line ? `:${d.line}` : ''}</code><small>{d.code}</small><p>{d.message}</p></li>)}</ul>{docs.limitations.map(l => <p className="micro" key={l}>{l}</p>)}</>}<p className="micro">Missing information is distinct from missing artwork. No runtime or completeness certificate is inferred.</p></>}
    {tab === 'assets' && <><h3>Graphics checklist</h3><p className="micro">Generic symbols render immediately. No downloads, generation or uploads.</p><ul>{assets.requirements.map(a => <li key={a.id}><strong>{a.label}</strong><small>{a.requestedIcon} → {a.resolvedIcon} · {a.status}</small><p className="micro">{a.reason}</p></li>)}</ul><button type="button" onClick={() => download(JSON.stringify(assets,null,2), `${p.id}.asset-plan.json`, 'application/json')}>Download asset plan JSON</button><button type="button" onClick={() => download(assetChecklistCsv(assets), `${p.id}.asset-checklist.csv`, 'text/csv;charset=utf-8')}>Download asset checklist CSV</button><p className="micro">Original symbols and provider artwork have distinct registry origins and terms. Suggested official artwork needs exact-product review.</p></>}
  </div></aside>;
}
