import {useMemo,useState,type KeyboardEvent} from 'react';
import type {Project} from '../core/model';
import {ICON_REGISTRY} from '../core/icons';
import {perspectivesFor,PERSPECTIVE_LABEL} from '../core/viewspec';
import {overviewProjection} from '../export/projectOverview';
import {download} from '../export/browser';
import {projectReadiness} from '../intelligence/readiness';
import {planAssets,assetChecklistCsv} from '../intelligence/assets';
import {selectionContext,projectNavigation} from '../intelligence/navigation';
import type {DocumentMap,Purpose} from '../intelligence/types';
import './project-intelligence.css';

export function ProjectContext({project,purpose='understand',publicMode=false,documents,onReviewedProposal,selectedViewId,selectedNodeId,onView,onNode}:{project:Project;purpose?:Purpose;publicMode?:boolean;documents?:DocumentMap;onReviewedProposal?:()=>void;selectedViewId?:string;selectedNodeId?:string;onView?:(id:string,nodeId?:string)=>void;onNode?:(id:string)=>void}){
 const [tab,setTab]=useState('details'),[message,setMessage]=useState('');
 const p=useMemo(()=>overviewProjection(project,publicMode),[project,publicMode]);
 const report=useMemo(()=>projectReadiness(p,{purpose}),[p,purpose]),context=useMemo(()=>selectionContext(p,{nodeId:selectedNodeId,viewId:selectedViewId}),[p,selectedNodeId,selectedViewId]);
 const allAssets=useMemo(()=>planAssets(p,ICON_REGISTRY,{viewId:context.node?undefined:context.view?.id}),[p,context.node,context.view?.id]),assets=context.node?{...allAssets,requirements:allAssets.requirements.filter(a=>a.nodeId===context.node!.id)}:allAssets;
 const docs=publicMode?undefined:documents,alternatives=context.node?perspectivesFor(p,context.node.id):[],mappings=projectNavigation(p).crosswalk.filter(m=>m.logicalId===context.node?.id||m.physicalId===context.node?.id);
 const manual={format:'diagramcloud.selected-context/1',projectId:p.id,projectRevision:p.revision,scope:context.scope,selection:context.selection,components:context.components,sources:context.sources,evidence:context.blocks,connections:context.relations,observations:context.observations,readiness:report,assets,note:'Source-qualified author context. Imported proposals require review; this object is not an authoring document.'};
 const copy=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(manual,null,2));setMessage('Selected context copied. Proposals still require review.');}catch{setMessage('Clipboard unavailable. Download context instead.');}};
 const tabs=['details','evidence','gaps','alternatives','assets'];
 const moveTab=(e:KeyboardEvent<HTMLButtonElement>)=>{const index=tabs.indexOf(tab),next=e.key==='ArrowRight'?(index+1)%tabs.length:e.key==='ArrowLeft'?(index+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:-1;if(next<0)return;e.preventDefault();setTab(tabs[next]);e.currentTarget.parentElement?.querySelector<HTMLButtonElement>(`#context-tab-${tabs[next]}`)?.focus();};
 return <aside className="project-context" aria-label="Project context" data-testid="project-context"><div className="pi-tabs" role="tablist" aria-label="Context scope">{tabs.map(t=><button type="button" id={`context-tab-${t}`} style={{flex:"1 1 85px"}} role="tab" tabIndex={tab===t?0:-1} onKeyDown={moveTab} aria-controls="project-context-panel" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div><div id="project-context-panel" role="tabpanel" aria-labelledby={`context-tab-${tab}`}><p className="micro">{publicMode?'Public projection':'Private authoring context'} · revision {p.revision} · {purpose}</p><p className="micro">Selection: {context.node?.label??context.view?.title??p.title} · {context.scope}</p>
 {tab==='details'&&<><h3>Selection details</h3>{context.node?<><h4>{context.node.label}</h4><code>{context.node.id}</code><p>{context.node.summary||'Description not supplied.'}</p><p>{context.node.kind} · basis {context.node.basis??'unknown'} · designed status {context.node.status}. Designed status does not establish a runtime result.</p><p>Role / contribution: {context.node.role||'Unknown'}</p>{context.repository&&<p>Physical repository: {context.repository.title} · {context.repository.revision??'revision UNKNOWN'} · {context.repository.scanStatus}</p>}{context.node.childViewId&&onView&&<button type="button" onClick={()=>onView(context.node!.childViewId!)}>Open selected child view</button>}<h4>Explicit implementation mappings</h4><ul>{mappings.map(m=><li key={m.id}>{m.logicalLabel} → {m.physicalLabel}<small>{m.origin} · {m.assertion} · sources {m.sourceIds.join(', ')||'not attached'}</small>{onNode&&<button onClick={()=>onNode(m.logicalId===context.node!.id?m.physicalId:m.logicalId)}>Open mapped component</button>}</li>)}</ul>{!mappings.length&&<p className="micro">No explicit logical/physical mapping supplied for this component.</p>}</>:<><p>{context.view?.description||p.summary||'Purpose and scope not supplied.'}</p><p>{context.components.length} components · {context.relations.length} supplied connections touching this scope · {context.sources.length} cited sources.</p></>}<h4>Dated external claims</h4><ul>{context.observations.map(o=><li key={o.id}>{o.claim} · {o.sourceApp}<small>{o.observedAt} · source revision {o.sourceRevision} · {o.reviewedAt?'author reviewed':'awaiting author review'}</small><p>{o.summary}</p>{o.caveat&&<p>{o.caveat}</p>}</li>)}</ul>{!context.observations.length&&<p className="micro">No dated external observation in this selected projection.</p>}</>}
 {tab==='evidence'&&<><h3>Source provenance</h3><p className="micro">{p.provenance||'Provenance not supplied.'}</p><ul>{context.sources.map(s=><li key={s.id}><strong>{s.title}</strong><small>{s.location}</small><code>{s.id}</code></li>)}</ul>{!context.sources.length&&<p>No source references attached to this selected scope.</p>}<h3>Evidence</h3><ul>{context.blocks.slice(0,20).map(b=><li key={b.id}>{b.title}<small>{b.provenance} · {b.visibility}</small></li>)}</ul>{context.blocks.length>20&&<p>{context.blocks.length-20} additional blocks omitted from preview.</p>}{docs&&<details><summary>Selected source document map</summary><p className="micro">Acquisition-wide file map; exact selected component citations are listed above.</p><ul>{docs.documents.map(d=><li key={d.path}><code>{d.path}</code><small>{d.kind} · {d.headings.length} headings · {d.records.length} records</small>{d.headings.slice(0,6).map(h=><small key={`${h.line}-${h.title}`}>:{h.line} {h.title}</small>)}</li>)}</ul><h4>Exact provenance links</h4><ul>{docs.links.slice(0,40).map((l,i)=><li key={i}><code>{l.fromPath}:{l.fromLine} → {l.toPath}{l.toLine?`:${l.toLine}`:''}</code><small>{l.kind}; locator only, no file/network fetch</small></li>)}</ul><p className="micro">Omitted: {docs.omitted.documents} documents; {docs.omitted.links} links.</p></details>}<details><summary>Manual assistance</summary><p className="micro">Copy the selected context for an external assistant. Nothing executes here; review every proposed change.</p><button type="button" onClick={()=>void copy()}>Copy context</button><button type="button" onClick={()=>download(JSON.stringify(manual,null,2),`${p.id}.context.json`,'application/json')}>Download context</button>{onReviewedProposal&&<button type="button" onClick={onReviewedProposal}>Import reviewed proposal</button>}{message&&<p role="status">{message}</p>}</details></>}
 {tab==='gaps'&&<><h3>Information gaps</h3><p className="micro">Project-wide purpose/readiness rules plus the selected component's cited evidence. Missing information does not establish absence.</p>{context.node&&!context.node.sourceIds.length&&<p>Selected component has no attached source citations.</p>}{report.gaps.length?<ul>{report.gaps.filter(g=>!g.subjectId||!context.repository||g.subjectId===context.repository.id).map(g=><li key={g.id}><strong>{g.title}</strong><small>{g.state}</small><p>{g.reason}</p><p className="micro">{g.resolution}</p></li>)}</ul>:<p>No contextual gap detected by these limited rules.</p>}{docs&&<><h3>Document diagnostics</h3><ul>{docs.diagnostics.map((d,i)=><li key={i}><code>{d.path}{d.line?`:${d.line}`:''}</code><small>{d.code}</small><p>{d.message}</p></li>)}</ul>{docs.limitations.map(l=><p className="micro" key={l}>{l}</p>)}</>}<p className="micro">Missing information is distinct from missing artwork. No runtime or completeness certificate is inferred.</p></>}
 {tab==='alternatives'&&<><h3>Other perspectives for this selection</h3><p className="micro">Available means the same stable component ID appears in that view. Partial means related parent/child context exists. Unknown and unsupported do not create a view.</p>{context.node?<ul>{alternatives.map(a=><li key={a.perspective}><strong>{PERSPECTIVE_LABEL[a.perspective]}</strong> · {a.state}{a.views.map(v=><button key={v.viewId} type="button" onClick={()=>onView?.(v.viewId,context.node!.id)} disabled={!onView}>{v.title}</button>)}</li>)}</ul>:<p>Select a component to inspect its existing perspective alternatives.</p>}</>}
 {tab==='assets'&&<><h3>Graphics checklist</h3><p className="micro">Selected scope only. Generic symbols render immediately. No downloads, generation or uploads.</p><ul>{assets.requirements.map(a=><li key={a.id}><strong>{a.label}</strong><small>{a.requestedIcon} → {a.resolvedIcon} · {a.status}</small><p className="micro">{a.reason}</p></li>)}</ul><button type="button" onClick={()=>download(JSON.stringify(assets,null,2),`${p.id}.asset-plan.json`,'application/json')}>Download asset plan JSON</button><button type="button" onClick={()=>download(assetChecklistCsv(assets),`${p.id}.asset-checklist.csv`,'text/csv;charset=utf-8')}>Download asset checklist CSV</button><p className="micro">Original symbols and provider artwork have distinct registry origins and terms. Suggested official artwork needs exact-product review.</p></>}
 </div></aside>;
}
