import type {Project} from '../core/model';
import {overviewFacts, projectOverviewHtml} from '../export/projectOverview';
import {download} from '../export/browser';
import './project-intelligence.css';

export function ProjectOverview({project, publicMode = false, onNode, onWorkspace}: {project: Project; publicMode?: boolean; onNode?: (id: string) => void; onWorkspace?: (id: string) => void}) {
  const {project: p, components, omitted, report} = overviewFacts(project, publicMode);
  return <section className="project-overview" data-testid="project-overview"><div className="pi-heading"><div><span className="pi-eyebrow">{publicMode ? 'Public projection' : 'Private preview'} · Project Overview</span><h1>{p.title}</h1></div><button type="button" onClick={() => download(projectOverviewHtml(project), `${p.id}.overview.html`, 'text/html;charset=utf-8')}>Export public overview HTML</button></div>
    <h2>Purpose and scope</h2><p>{p.summary || 'Purpose has not been supplied.'}</p><h2>Steps and components</h2><div className="pi-overview-grid">{components.map((n,i) => <article className="pi-component" key={n.id}><span className="pi-eyebrow">{i + 1} · {n.basis || 'unknown basis'}</span><h3>{onNode ? <button type="button" className="pi-text-button" onClick={() => onNode(n.id)}>{n.label}</button> : n.label}</h3><p>{n.summary || 'Contribution and scope not supplied.'}</p><p className="micro">Stated role / owner: {n.role || 'Unknown'}</p><p className="micro">Designed status: {n.status}. Runtime outcome not inferred.</p>{n.experienceWorkspaceId && onWorkspace && <button type="button" onClick={() => onWorkspace(n.experienceWorkspaceId!)}>Open task workspace</button>}</article>)}</div>{!components.length && <p>No components in this projection. Review visibility in Edit mode for a public deliverable.</p>}{omitted > 0 && <p className="micro">{omitted} additional components remain in the diagram.</p>}
    <h2>Evidence and provenance</h2><p>{p.provenance || 'Provenance not supplied.'}</p>{p.blocks.length ? <ul>{p.blocks.slice(0, 12).map(b => <li key={b.id}>{b.title} · {b.provenance}</li>)}</ul> : <p>No evidence attached in this projection.</p>}<ul>{p.sources.map(s => <li key={s.id}>{s.title}<span className="micro"> · {s.location}</span></li>)}</ul><h2>Caveats</h2><ul>{report.gaps.map(g => <li key={g.id}><strong>{g.title}</strong> · {g.resolution}</li>)}</ul><p className="micro">Declarations and static findings are not observed runtime results. Synthetic evidence stays synthetic. Public export filters visibility before building this sheet.</p>
  </section>;
}
