import {useMemo,useState} from 'react';
import type {Project} from '../core/model';
import {contextualRecipes,classifyPatterns,learningPath,architectureAudit,repositoryOutputFacts} from '../intelligence/recipes';
import {analysisProfile,type AnalysisProfile} from '../intelligence/profile';
import {DEFAULT_OPTIONS,PURPOSES,type AnalysisOptions,type Purpose} from '../intelligence/types';
import {AnalysisProfilePanel} from './AnalysisProfilePanel';
import {ICON_REGISTRY} from '../core/icons';
import {planAssets,assetChecklistCsv} from '../intelligence/assets';
export function RecipeWorkbench({project,onOpen,initialPurpose=DEFAULT_OPTIONS.purpose}:{project:Project;onOpen:(view:string,node?:string)=>void;initialPurpose?:Purpose}){
 const [options,setOptions]=useState<AnalysisOptions>({...DEFAULT_OPTIONS,purpose:initialPurpose}),[depth,setDepth]=useState<AnalysisProfile['depth']>('standard'),[audience,setAudience]=useState<AnalysisProfile['audience']>('mixed'),[archetypes,setArchetypes]=useState<AnalysisProfile['archetypes']>([]),[scope,setScope]=useState(''),[environment,setEnvironment]=useState(''),[revision,setRevision]=useState('current'),[maxNodes,setMaxNodes]=useState(60);
 const recipes=useMemo(()=>contextualRecipes(project,options,{archetypes,repositoryId:scope||undefined,environmentId:environment||undefined}),[project,options,archetypes,scope,environment]),patterns=useMemo(()=>classifyPatterns(project),[project]),learning=useMemo(()=>learningPath(project),[project]),audit=useMemo(()=>architectureAudit(project),[project]);
 const [customProfile,setCustomProfile]=useState<AnalysisProfile>();
 const profile=useMemo(()=>analysisProfile(depth,{purpose:options.purpose,audience,archetypes,repositoryIds:customProfile?.repositoryIds[0]===scope?customProfile.repositoryIds:scope?[scope]:[],scope:customProfile?.scope??[],includeInferred:options.includeInferred,...(customProfile?{analyzers:customProfile.analyzers.filter(a=>a!=="tree-sitter"||depth==="deep"||depth==="custom")}:{ }),...(customProfile?.depth===depth?{budgets:customProfile.budgets}:depth==='custom'?{budgets:{nodes:maxNodes}}:{})}),[depth,options,audience,archetypes,scope,maxNodes,customProfile]);
 const scopedIds=useMemo(()=>new Set(repositoryOutputFacts(project,scope||undefined).nodes.map(n=>n.id)),[project,scope]);
 const setProfile=(p:AnalysisProfile)=>{setCustomProfile(p);setDepth(p.depth);setAudience(p.audience);setArchetypes(p.archetypes);setScope(p.repositoryIds[0]??'');setMaxNodes(Math.min(100,p.budgets.nodes));setOptions({purpose:p.purpose,depth:p.depth==='quick'?'quick':'standard',includeInferred:p.includeInferred});};
 const previewLimit=depth==='quick'?24:depth==='standard'?60:depth==='deep'?100:maxNodes;
 const download=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(profile,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=project.id+'.analysis-profile.json';a.click();URL.revokeObjectURL(u);};
 const downloadAssets=(recipeId:string,csv:boolean)=>{const plan=planAssets(project,ICON_REGISTRY,{recipeId,analysis:options,context:{archetypes,repositoryId:scope||undefined,environmentId:environment||undefined}}),u=URL.createObjectURL(new Blob([csv?assetChecklistCsv(plan):JSON.stringify(plan,null,2)],{type:csv?'text/csv':'application/json'})),a=document.createElement('a');a.href=u;a.download=project.id+'.'+recipeId+'.private-assets.'+(csv?'csv':'json');a.click();URL.revokeObjectURL(u);};
 const recipeRows=recipes.map(r=>{const ids=[...new Set(project.views.filter(v=>r.viewIds.includes(v.id)).flatMap(v=>v.nodeIds))].filter(id=>{const n=project.nodes.find(n=>n.id===id)!;return scopedIds.has(id)&&(options.includeInferred||n.basis!=='unknown')&&(!environment||project.delivery?.instances.some(i=>i.environmentId===environment&&(i.nodeId===id||i.componentId===id)));});return <li key={r.id}><strong>{r.title}</strong> · {r.state} · {r.availability}<p>{r.question} {r.reason} Suggested {r.figure}.</p><details><summary>Why this view? Preview requirements and up to {previewLimit} components</summary><p>Perspectives: {r.requirements.perspectives.join(', ')}. Tags: {r.requirements.tags.join(', ')||'none required'}. Relationships: {r.requirements.relationships?'needed for complete view':'optional'}. Missing facts stay unknown.</p><ul>{ids.slice(0,previewLimit).map(id=><li key={id}>{project.nodes.find(n=>n.id===id)?.label}</li>)}</ul>{ids.length>previewLimit&&<p>{ids.length-previewLimit} components omitted from preview.</p>}</details>{r.viewIds.length>0&&<button onClick={()=>onOpen(r.viewIds[0])}>Open existing view</button>}<p>Recipe asset downloads are private authoring checklists; inspect before sharing.</p><button onClick={()=>downloadAssets(r.id,false)}>Download recipe asset plan</button><button onClick={()=>downloadAssets(r.id,true)}>Download recipe asset checklist</button></li>;});
 return <section aria-label="Recipe and pattern workbench"><h3>Questions and useful views</h3><div className="pi-controls"><label>View purpose<select aria-label="View purpose" value={options.purpose} onChange={e=>setOptions(o=>({...o,purpose:e.target.value as AnalysisOptions['purpose']}))}>{PURPOSES.map(p=><option key={p}>{p}</option>)}</select></label><label>View detail<select aria-label="View detail" value={depth} onChange={e=>{const d=e.target.value as typeof depth;setDepth(d);setOptions(o=>({...o,depth:d==='quick'?'quick':'standard'}));}}><option value="quick">Quick · 24 components</option><option value="standard">Standard · 60 components</option><option value="deep">Deep · 100 components in preview</option><option value="custom">Custom</option></select></label></div>
 <details><summary>Advanced analysis parameters</summary><p>These settings define a review-required analysis profile and transient preview. They never rewrite source facts or authoring data.</p><div className="pi-controls"><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value as typeof audience)}><option>mixed</option><option>technical</option><option>business</option></select></label><fieldset><legend>Archetype hints (multiple allowed)</legend>{(['application','data','cloud','library','documents'] as const).map(a=><label key={a}><input type="checkbox" checked={archetypes.includes(a)} onChange={e=>setArchetypes(old=>e.target.checked?[...old,a]:old.filter(x=>x!==a))}/>{a}</label>)}</fieldset><label>Repository scope<select value={scope} onChange={e=>{const value=e.target.value;setScope(value);setCustomProfile(p=>p?{...p,repositoryIds:value?[value]:[]}:p);}}><option value="">Current project</option>{project.atlas?.snapshots.find(s=>s.id===project.atlas?.activeSnapshotId)?.repositories.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Environment preview<select value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="">All declared environments</option>{project.delivery?.environments.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></label><label>Revision context<select value={revision} onChange={e=>setRevision(e.target.value)}><option value="current">Current document revision {project.revision}</option>{project.atlas?.snapshots.map(s=><option key={s.id} value={s.id}>{s.label??s.id} · {s.capturedAt}</option>)}</select></label><label><input type="checkbox" checked={options.includeInferred} onChange={e=>setOptions(o=>({...o,includeInferred:e.target.checked}))}/>Include unknown basis in preview</label>{depth==='custom'&&<label>Preview component budget<input type="number" min={1} max={100} value={maxNodes} onChange={e=>setMaxNodes(Math.max(1,Math.min(100,Number(e.target.value)||1)))}/></label>}</div><AnalysisProfilePanel profile={profile} onChange={setProfile}/><p>Profile repository IDs: {profile.repositoryIds.join(", ")||"current selected source"}. The recipe preview uses the first selected repository; imported multi-repository profile scope is retained for analysis.</p><p>Granularity: {previewLimit} components · perspective: selected recipe · assets: existing registered icons · autonomy: author review. Snapshot {revision} is a context pointer; selecting it never rolls back the current source facts.</p><button onClick={download}>Download validated analysis profile</button></details>
 <ul>{recipeRows.slice(0,3)}</ul><details><summary>More view recipes and unavailable capabilities</summary><ul>{recipeRows.slice(3)}</ul></details>
 <details><summary>Learning path · start here and read next</summary><ol>{learning.map(step=><li key={step.viewId}><button onClick={()=>onOpen(step.viewId,step.nodeId)}>{step.title}</button> {step.reason} Sources: {step.sourceIds.join(', ')||'not attached'}.</li>)}</ol></details>
 <details><summary>Illustrative architecture pattern catalog</summary><p>Pattern recognition proposes comparisons. Names such as Bronze, Silver and Gold never prove a deployed medallion pipeline.</p><ul>{patterns.map(p=><li key={p.id}><strong>{p.title}</strong> · version {p.version} · {p.state}. {p.reason}<p>{p.matchReasons.join("; ")} Citations: {p.sourceIds.join(", ")||"not attached"}; relationship IDs: {p.relationshipIds.join(", ")||"none"}.</p><p>Evidence required: {p.gaps.join('; ')}.</p></li>)}</ul></details>
 <details><summary>Architecture and evidence audit</summary><p>{audit.note}</p><ul>{audit.missingSources.map(g=><li key={g.nodeId}>{g.nodeId}: {g.reason}</li>)}{audit.unreviewed.map(g=><li key={g.id}>{g.nodeId}: external observation requires author review.</li>)}{audit.stale.map(g=><li key={g.id}>{g.nodeId}: {g.reason} {g.sourceRevision} → {g.currentSourceRevision}.</li>)}{audit.conflicts.map((g,i)=><li key={i}>{g.nodeId}: {g.reason} Claim IDs {g.observationIds.join(", ")}.</li>)}{audit.repositories.map(r=><li key={r.id}>{r.id}: {r.state}. {r.reason}</li>)}{audit.unsupported.map((d,i)=><li key={i}>{d.path}:{d.line??'?'} {d.code} · {d.message}</li>)}</ul></details></section>;
}


