import {useMemo,useState} from 'react';
import type {Project} from '../core/model';
import {proposeVerificationSpec,stageVerificationReceipt,stageCockpitSnapshot,verificationGaps,testCoverageGaps,workVerificationBrief,operationalSourceLinks,trustBoundaryHooks,validateVerificationSpec,type VerificationSpec} from '../intelligence/verification';
import {stageEntityProposal} from '../intelligence/entityProposal';
export function WorkVerificationPanel({project,onPatch}:{project:Project;onPatch?:(patch:unknown)=>void}){
 const [spec,setSpec]=useState<VerificationSpec>(),[error,setError]=useState(''),[repo,setRepo]=useState(''),[commit,setCommit]=useState(''),[subject,setSubject]=useState(''),[question,setQuestion]=useState('test'),[runner,setRunner]=useState(''),[runId,setRunId]=useState('');
 const [sourceId,setSourceId]=useState(''),[sourceText,setSourceText]=useState(''),[selectedSources,setSelectedSources]=useState<Record<string,string>>({}),[entityInput,setEntityInput]=useState('');
 const gaps=useMemo(()=>{try{return spec?verificationGaps(project,spec):[];}catch{return [];}},[project,spec]),links=useMemo(()=>operationalSourceLinks(project),[project]),trust=useMemo(()=>trustBoundaryHooks(project),[project]);
 const coverage=useMemo(()=>{try{return spec?testCoverageGaps(project,spec):undefined;}catch{return undefined;}},[project,spec]); const brief=workVerificationBrief(project,spec?.projectRevision===project.revision?spec:undefined,subject&&project.nodes.some(n=>n.id===subject)?{summary:'Selected component for a proposed external check.',nodeIds:[subject]}:undefined);const handle=(fn:()=>void)=>{try{setError('');fn();}catch(e){setError(e instanceof Error?e.message:'Review proposal failed');}};
 const propose=()=>handle(()=>setSpec(proposeVerificationSpec(project,{id:'selected-checks',repositories:[{id:'selected-repository',repository:repo,commit}],checks:[{id:question,nodeId:subject,repositoryId:'selected-repository',question:'Does the external '+question+' check pass at the requested source commit?',expected:'External runner supplies its exact result, run identity and non-synthetic evidence references.',kind:question==='build'?'build':'test'}]})));
 const file=async(f:File|undefined,kind:'spec'|'receipt'|'cockpit')=>{if(!f)return;try{setError('');if(f.size>2*1024*1024)throw new Error('Verification input exceeds 2 MiB');const raw=JSON.parse(await f.text());if(kind==='spec'){setSpec(validateVerificationSpec(raw,project));}else if(kind==='cockpit')onPatch?.(stageCockpitSnapshot(project,raw).patch);else{if(!spec)throw new Error('Select a proposed spec first');onPatch?.(stageVerificationReceipt(project,spec,raw,{name:runner,runId}).patch);}}catch(e){setError(e instanceof Error?e.message:'Verification input refused');}};
 return <details><summary>Work and verification brief · external check review</summary><p>{brief.nextGate} {brief.note}</p><p>Change: {brief.change.summary} Impact: {brief.impact.nodeIds.length} supplied reachable components, {brief.impact.viewIds.length} existing views. {brief.impact.note}</p>{brief.affectedCheckIds.length>0&&<p>Explicitly mapped affected check IDs: {brief.affectedCheckIds.join(", ")}. Requested checks remain NOT_RUN until an external receipt is reviewed.</p>}{error&&<p role="alert">{error}</p>}<fieldset><legend>Propose a check (not run)</legend><div className="pi-controls"><label>Exact repository identity<input aria-label="Exact verification repository" value={repo} maxLength={200} onChange={e=>setRepo(e.target.value)}/></label><label>Full 40-character source commit<input aria-label="Verification source commit" value={commit} maxLength={40} onChange={e=>setCommit(e.target.value)}/></label><label>Check component<select aria-label="Verification component" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Choose a component</option>{project.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label>External check ID<input aria-label="External check ID" value={question} maxLength={64} onChange={e=>setQuestion(e.target.value)}/></label><button disabled={!repo||!subject||!commit} onClick={propose}>Propose NOT_RUN check</button></div></fieldset>
 <label>Select verification spec<input aria-label="Select verification spec" type="file" accept="application/json,.json" onChange={e=>{void file(e.target.files?.[0],'spec');e.target.value='';}}/></label>
 {spec&&<><p>Spec {spec.id} · PROPOSED · document revision {spec.projectRevision}. {spec.checks.length} requested checks. No execution.</p><button onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(spec,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=project.id+'.verification-spec.json';a.click();URL.revokeObjectURL(u);}}>Download proposed verification spec</button><ul>{gaps.map(g=><li key={g.checkId}>{g.checkId} · {g.state} · {g.revision}. {g.reason}</li>)}</ul></>}
 {onPatch&&<><div className="pi-controls"><label>External runner name<input aria-label="External runner name" value={runner} onChange={e=>setRunner(e.target.value)}/></label><label>External run identity<input aria-label="External run identity" value={runId} onChange={e=>setRunId(e.target.value)}/></label><label>Select Galaxy verification receipt<input aria-label="Select Galaxy verification receipt" type="file" accept="application/json,.json" disabled={!spec||!runner||!runId} onChange={e=>{void file(e.target.files?.[0],'receipt');e.target.value='';}}/></label></div><label>Select host-fed cockpit snapshot<input aria-label="Select host-fed cockpit snapshot" type="file" accept="application/json,.json" onChange={e=>{void file(e.target.files?.[0],'cockpit');e.target.value='';}}/></label><p>Inputs become revision-guarded review patches. Observations arrive private, unreviewed and unshareable; snapshot permissions and timestamps are required.</p></>}
 {onPatch&&<details><summary>Source-cited agent extraction candidates</summary><p>Select the source registry identity and supply only the authorized text. An agent proposal must cite exact quotes and line ranges; candidate entities and relations remain unknown and private until reviewed.</p><label>Candidate citation source<select aria-label="Candidate citation source" value={sourceId} onChange={e=>{setSourceId(e.target.value);setSourceText(selectedSources[e.target.value]??'');}}><option value="">Choose a registered source</option>{project.sources.map(s=><option key={s.id} value={s.id}>{s.title} ({s.id})</option>)}</select></label><label>Authorized citation text<textarea aria-label="Authorized citation text" value={sourceText} maxLength={131072} onChange={e=>setSourceText(e.target.value)}/></label><button disabled={!sourceId||!sourceText} onClick={()=>handle(()=>{if(new TextEncoder().encode(sourceText).byteLength>131072)throw new Error('Citation text exceeds 128 KiB');setSelectedSources(s=>({...s,[sourceId]:sourceText}));})}>Select citation text</button><p>Selected source IDs: {Object.keys(selectedSources).join(', ')||'none'}</p><label>Agent entity proposal JSON<textarea aria-label="Agent entity proposal JSON" value={entityInput} maxLength={524288} onChange={e=>setEntityInput(e.target.value)}/></label><button disabled={!entityInput||!Object.keys(selectedSources).length} onClick={()=>handle(()=>onPatch(stageEntityProposal(project,JSON.parse(entityInput),selectedSources).patch))}>Review source-cited candidates</button></details>}
 {coverage&&<details><summary>Component and connection check mapping gaps</summary><p>{coverage.note}</p><ul>{coverage.components.map(g=><li key={g.nodeId}>{g.nodeId}: {g.reason}</li>)}{coverage.connections.map(g=><li key={g.edgeId}>{g.edgeId}: {g.reason}</li>)}</ul></details>}<h4>Optional operational source links</h4><ul>{links.map((l,i)=><li key={i}>{l.nodeId}: {l.title} · {l.scope} · health UNKNOWN. {l.note}</li>)}</ul>{!links.length&&<p>No selected logs, metrics, traces or runbook source links.</p>}<h4>Trust and policy concepts</h4><ul>{trust.map(t=><li key={t.nodeId}>{t.nodeId}: {t.state}. {t.note}</li>)}</ul>{!trust.length&&<p>Policy/trust boundaries UNKNOWN; no explicit cited concepts.</p>}</details>;
}



