import {validateDocument,type Project} from '../core/model';
import {applyDocumentPatch,type Patch} from '../core/patch';
import {validateAnalysisBundle,type AnalysisBundle} from './profile';
/** Bounded explicitly selected syntax projection in the existing Project. Nothing
 * executes or reviews observations; canonical IDs and author edits are preserved. */
export function deepAnalysisPatch(current:Project,input:AnalysisBundle,selected:string[]):Patch{
 const project=validateDocument(current),bundle=validateAnalysisBundle(input),wanted=new Set(selected);
 if(!selected.length||selected.length>60||wanted.size!==selected.length)throw new Error('Select 1–60 unique deep analysis items');
 if(!bundle.parserVersion.startsWith('diagramcloud-tree-sitter/'))throw new Error('Only the actual Tree-sitter bundle is accepted here');
 const items=bundle.items.filter(i=>wanted.has(i.id));if(items.length!==selected.length)throw new Error('Unknown selected deep analysis item');
 const edges=bundle.links.filter(l=>wanted.has(l.from)&&wanted.has(l.to)).slice(0,150),sourceIds=new Set([...items,...edges].flatMap(i=>i.sourceIds)),sources=bundle.sources.filter(s=>sourceIds.has(s.id));
 const vector=bundle.revisions[0],viewId='deep-view-'+vector.contentDigest.slice(0,20),navId=viewId+'-nav';
 if(project.nodes.length+items.length+1>500||project.edges.length+edges.length>1500||project.views.length>=80||project.blocks.length+items.length>1500||project.sources.length+sources.length>200)throw new Error('Selected syntax projection exceeds remaining Project limits; choose fewer items');
 if(project.views.some(v=>v.id===viewId)||project.nodes.some(n=>n.id===navId)||items.some(i=>project.nodes.some(n=>n.id===i.id)||project.blocks.some(b=>b.id===i.id+'-syntax'))||sources.some(s=>project.sources.some(old=>old.id===s.id)))throw new Error('Selected syntax identity already exists; authored entities are not overwritten');
 if(project.atlas){const snapshot=project.atlas.snapshots.find(s=>s.id===project.atlas!.activeSnapshotId)!;for(const r of bundle.revisions){const repo=snapshot.repositories.find(member=>member.id===r.repositoryId);if(!repo||repo.revision!==r.revision)throw new Error('Deep bundle repository identity/revision is not the current declared atlas member');}}
 const operations:Patch['operations']=sources.map(s=>({op:'add',path:'/sources/-',value:{id:s.id,title:(s.repositoryId+' '+s.path).slice(0,160),location:s.repositoryId+'@'+s.revision+':'+s.path+':'+s.line+'–'+(s.endLine??s.line)+' sha256:'+s.contentDigest,visibility:'private'}}));
 for(const item of items){const blockId=item.id+'-syntax';operations.push({op:'add',path:'/blocks/-',value:{id:blockId,title:'Tree-sitter static syntax evidence',type:'text',text:item.kind+' · '+item.confidence+' syntax\n'+item.sourceIds.map(id=>{const s=sources.find(s=>s.id===id)!;return s.repositoryId+'@'+s.revision+' '+s.path+':'+s.line+'–'+(s.endLine??s.line)+' SHA-256 '+s.contentDigest;}).join('\n')+'\n'+edges.filter(e=>e.from===item.id||e.to===item.id).map(e=>e.kind+' · '+e.confidence+' · '+e.from+' → '+e.to).join('\n')+'\nNo code executed. Call-site syntax does not prove dispatch or runtime traffic.',provenance:'source-derived',sourceIds:item.sourceIds,visibility:'private'}},{op:'add',path:'/nodes/-',value:{id:item.id,label:item.label,kind:item.kind==='source-file'||item.kind==='import-declaration'?'source':item.kind==='type-declaration'?'model':'function',provider:'Generic',icon:'generic-function',summary:'Selected '+item.kind+' from actual Tree-sitter parsing; runtime UNKNOWN.',role:'',status:'idle',blockIds:[blockId],sourceIds:item.sourceIds,tags:['Tree-sitter','Confidence: '+item.confidence],basis:'static-source',visibility:'private'}});}
 for(const edge of edges)operations.push({op:'add',path:'/edges/-',value:{id:edge.id,source:edge.from,target:edge.to,label:edge.kind+(edge.confidence==='confirmed'?'':' ('+edge.confidence+')'),kind:'dependency',speed:'medium',basis:edge.confidence==='confirmed'?'static-source':'unknown',visibility:'private'}});
 const root=project.views.find(v=>v.id===project.rootViewId)!;operations.push({op:'add',path:'/views/-',value:{id:viewId,title:'Selected source syntax',description:bundle.parserVersion+'; bounded selected projection. Compiler binding and runtime calls UNKNOWN.',nodeIds:items.map(i=>i.id),edgeIds:edges.map(e=>e.id),positions:Object.fromEntries(items.map((i,n)=>[i.id,{x:n%3*300,y:Math.floor(n/3)*180}])),perspective:'code',visibility:'private'}},{op:'add',path:'/nodes/-',value:{id:navId,label:'Selected source syntax',kind:'control',provider:'Generic',icon:'generic-control',summary:'Explicitly selected Tree-sitter syntax; not runtime observations.',role:'',status:'idle',blockIds:[],sourceIds:[],tags:['Tree-sitter'],basis:'static-source',visibility:'private',childViewId:viewId}},{op:'add',path:'/views/@'+root.id+'/nodeIds/-',value:navId},{op:'add',path:'/views/@'+root.id+'/positions/'+navId,value:{x:root.nodeIds.length%3*300,y:Math.floor(root.nodeIds.length/3)*180}});
 const patch:Patch={format:'diagramcloud.patch',version:1,target:'project',targetId:project.id,baseRevision:project.revision,summary:'Review '+items.length+' selected source syntax items and '+edges.length+' source-cited connections; no runtime claims',operations};applyDocumentPatch(project,patch);return patch;
}
