import {z} from 'zod';
import {validateDocument,type Project} from '../core/model';
import {applyDocumentPatch,type Patch} from '../core/patch';
import {secretFindings} from '../core/secrets';
import {readAcquisitionAnalysis} from './materialize';
import {readGraphHistory,compareGraphGenerations,generationReceiptSchema} from './graphSnapshot';
const PREFIX='analysis-evolution-';
const short=z.string().max(160),id=z.string().regex(/^[a-z][a-z0-9_.-]{0,79}$/),instant=z.string().datetime({offset:true});
const canonical=(v:unknown):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical((v as Record<string,unknown>)[k])).join(',')+'}':JSON.stringify(v);
const claimSchema=z.object({id,claim:z.enum(['observed','verified','partial','not-observed']),sourceApp:short,authority:short,sourceRevision:short,observedAt:instant,freshness:z.enum(['exact-revision','stale-revision','unmatched']),summary:z.string().max(500)}).strict();
const entitySchema=z.object({id,label:short,semantic:z.string().max(150000),presentation:z.string().max(20000),sourceRefs:z.array(z.string().max(50000)).max(1000),evidenceIds:z.array(id).max(1000),confidence:z.array(z.enum(['confirmed','inferred','possible'])).max(3),claims:z.array(claimSchema).max(500),perspectives:z.array(short).max(9)}).strict();
const snapshotSchema=z.object({format:z.literal('diagramcloud.evolution-snapshot/1'),id,projectId:id,label:short,capturedAt:instant,documentRevision:z.number().int().nonnegative(),parserVersion:z.literal('diagramcloud-evolution/2'),graphGeneration:generationReceiptSchema.optional(),scope:z.object({identity:z.string().max(1000),analyzerVersion:short,profile:short,complete:z.boolean(),sourceDigest:short.optional()}).strict(),revisionVector:z.array(z.object({id:short,revision:short,collectedAt:instant.optional(),authority:short}).strict()).max(60),nodes:z.array(entitySchema).max(500),edges:z.array(entitySchema).max(1500),evidence:z.array(z.object({id,signature:z.string().max(24*1024*1024)}).strict()).max(1500)}).strict();
export type EvolutionSnapshot=z.infer<typeof snapshotSchema>;
/** A receipt of inspected facts. Signatures cannot be imported as an authoring graph. */
export function evolutionSnapshot(doc:Project,options:{id?:string;label?:string;capturedAt?:string}={}):EvolutionSnapshot{
 validateDocument(doc);const a=readAcquisitionAnalysis(doc),atlas=doc.atlas?.snapshots.find(s=>s.id===doc.atlas?.activeSnapshotId),graph=readGraphHistory(doc).at(-1);
 const vector=graph?.sourceVector.map(r=>({id:r.repo_id,revision:r.revision,collectedAt:graph.capturedAt,authority:'selected GraphSnapshot producer'}))??atlas?.repositories.map(r=>({id:r.id,revision:r.revision??'UNKNOWN',collectedAt:r.scannedAt,authority:r.authority}))??(a?[{id:a.sourceIdentity.selectedRoot,revision:a.sourceIdentity.sourceRevision??'UNKNOWN',collectedAt:a.sourceIdentity.observedAt,authority:'selected source'}]:[]);
 const sources=new Map(doc.sources.map(s=>[s.id,s.location])),blocks=new Map(doc.blocks.map(b=>[b.id,b]));
 const nodes=doc.nodes.map(n=>{
  const refs=n.sourceIds.map(i=>sources.get(i)??'UNKNOWN').sort(),evidence=n.blockIds.map(i=>blocks.get(i)).filter(b=>b&&!b.id.startsWith('analysis-'));
  const owners=atlas?.repositories.filter(r=>n.id===r.nodeId||n.id.startsWith(r.id+'.'))??[],revisions=owners.length?owners.map(r=>r.revision).filter(Boolean):!atlas&&a?.sourceIdentity.sourceRevision?[a.sourceIdentity.sourceRevision]:[];
  const claims=doc.observations.filter(o=>o.nodeId===n.id&&o.reviewedAt).map(o=>({id:o.id,claim:o.claim,sourceApp:o.sourceApp,authority:o.authority,sourceRevision:o.sourceRevision,observedAt:o.observedAt,summary:o.summary,freshness:!revisions.length?'unmatched' as const:revisions.includes(o.sourceRevision)?'exact-revision' as const:'stale-revision' as const})).sort((x,y)=>x.id.localeCompare(y.id));
  const confidence=[...new Set(n.tags.filter((t):t is 'confirmed'|'inferred'|'possible'=>['confirmed','inferred','possible'].includes(t)))].sort();
  return {id:n.id,label:n.label,semantic:canonical({label:n.label,kind:n.kind,summary:n.summary,role:n.role,provider:n.provider,basis:n.basis??'unknown',sourceIds:n.sourceIds.slice().sort()}),presentation:canonical({icon:n.icon,...(n.customIconAssetId?{customIconAssetId:n.customIconAssetId}:{}),status:n.status,visibility:n.visibility,positions:doc.views.filter(v=>v.nodeIds.includes(n.id)).map(v=>({id:v.id,position:v.positions[n.id]??null})).sort((x,y)=>x.id.localeCompare(y.id))}),sourceRefs:refs,evidenceIds:evidence.map(b=>b!.id).sort(),confidence,claims,perspectives:[...new Set(doc.views.filter(v=>v.nodeIds.includes(n.id)).map(v=>v.perspective??'system'))].sort()};
 });
 const lookup=new Map(nodes.map(n=>[n.id,n]));
 const edges=doc.edges.map(e=>({id:e.id,label:e.label,semantic:canonical({source:e.source,target:e.target,label:e.label,kind:e.kind,basis:e.basis??'unknown',quantity:e.quantity}),presentation:canonical({speed:e.speed,visibility:e.visibility}),sourceRefs:[...new Set([...(lookup.get(e.source)?.sourceRefs??[]),...(lookup.get(e.target)?.sourceRefs??[])])].sort(),evidenceIds:[],confidence:[] as ('confirmed'|'inferred'|'possible')[],claims:[],perspectives:[...new Set(doc.views.filter(v=>v.edgeIds.includes(e.id)).map(v=>v.perspective??'system'))].sort()}));
 const usedEvidence=new Set(nodes.flatMap(n=>n.evidenceIds)),evidence=doc.blocks.filter(b=>usedEvidence.has(b.id)).map(b=>({id:b.id,signature:canonical(b)}));
 return snapshotSchema.parse({format:'diagramcloud.evolution-snapshot/1',id:options.id??'revision-'+doc.revision,projectId:doc.id,label:options.label??'Document revision '+doc.revision,capturedAt:options.capturedAt??atlas?.capturedAt??a?.sourceIdentity.observedAt??new Date().toISOString(),documentRevision:doc.revision,parserVersion:'diagramcloud-evolution/2',...(graph?{graphGeneration:graph}:{}),scope:{identity:graph?'graph:'+graph.graphId:a?.sourceIdentity.selectedRoot??(atlas?'atlas:'+atlas.repositories.map(r=>r.id).sort().join(','):'authoring:'+doc.id),analyzerVersion:graph?.parserVersion??a?.sourceIdentity.analyzerVersion??'document/1',profile:graph?'graph/'+graph.minor:a?.sourceIdentity.profile??'authoring',complete:graph?.complete??a?.sourceIdentity.scopeComplete??false,sourceDigest:a?.sourceIdentity.contentDigest},revisionVector:vector,nodes,edges,evidence});
}
export type EvolutionChange={id:string;entity:'component'|'connection';change:'added'|'changed'|'removed'|'not-in-scope'|'moved'|'presentation'|'confidence'|'verification';reason:string;sourceRefs:string[];before?:string;after?:string};
function presentationParts(signature:string){try{const value=JSON.parse(signature);if(value&&typeof value==='object'&&!Array.isArray(value)){const {positions,...other}=value;return {positions,other};}}catch{/* Older/imported opaque signatures remain presentation differences. */}return {positions:undefined,other:signature};}
export function compareEvolutionSnapshots(a:EvolutionSnapshot,b:EvolutionSnapshot){
 snapshotSchema.parse(a);snapshotSchema.parse(b);if(a.projectId!==b.projectId)throw new Error('Evolution requires versions of the same project');const reasons:string[]=[];
 if(a.parserVersion!==b.parserVersion||a.scope.identity!==b.scope.identity||a.scope.analyzerVersion!==b.scope.analyzerVersion||a.scope.profile!==b.scope.profile)reasons.push('Different acquisition source, parser or profile');
 if(canonical(a.revisionVector.map(r=>r.id).sort())!==canonical(b.revisionVector.map(r=>r.id).sort()))reasons.push('Different explicit repository membership');
 let state: 'incomparable'|'comparable'|'partial'=reasons.length?'incomparable':a.scope.complete&&b.scope.complete?'comparable':'partial';if(state==='partial')reasons.push('Completeness not established for both selected source scopes');
 if(Date.parse(b.capturedAt)<Date.parse(a.capturedAt))reasons.push('Comparison selection runs backwards in capture time; no rollout order inferred');
 const graphDelta=a.graphGeneration&&b.graphGeneration?compareGraphGenerations(a.graphGeneration,b.graphGeneration):undefined;
 if(graphDelta?.state==='incomparable'){state='incomparable';reasons.push(...graphDelta.reasons.map(r=>'Graph source: '+r));}
 const sourceTombstones=new Set(graphDelta?.state==='comparable'?graphDelta.changes.filter(c=>c.kind==='assertion'&&c.change==='tombstone').map(c=>c.localId):[]);
 const changes:EvolutionChange[]=[],oldEvidence=new Map(a.evidence.map(e=>[e.id,e.signature])),nextEvidence=new Map(b.evidence.map(e=>[e.id,e.signature]));
 if(state!=='incomparable')for(const [entity,prior,next] of [['component',a.nodes,b.nodes],['connection',a.edges,b.edges]] as const){
  const old=new Map(prior.map(n=>[n.id,n])),ids=new Set(next.map(n=>n.id));
  for(const n of next){const p=old.get(n.id),sourceRefs=[...new Set([...(p?.sourceRefs??[]),...n.sourceRefs])].sort();
   if(!p){changes.push({id:n.id,entity,change:'added',reason:'New stable identity; '+(sourceRefs.length?'cited source scope':'planned / unknown source'),sourceRefs,after:n.label});continue;}
   if(p.semantic!==n.semantic||canonical(p.sourceRefs)!==canonical(n.sourceRefs)||canonical(p.evidenceIds)!==canonical(n.evidenceIds)||n.evidenceIds.some(id=>oldEvidence.get(id)!==nextEvidence.get(id)))changes.push({id:n.id,entity,change:'changed',reason:'Meaning or source-qualified evidence differs; stable ID retained',sourceRefs,before:p.label,after:n.label});
   if(p.presentation!==n.presentation){const prior=presentationParts(p.presentation),next=presentationParts(n.presentation);if(canonical(prior.positions)!==canonical(next.positions))changes.push({id:n.id,entity,change:'moved',reason:'Authored view position or membership changed; no runtime transition inferred',sourceRefs});if(canonical(prior.other)!==canonical(next.other))changes.push({id:n.id,entity,change:'presentation',reason:'Artwork, visibility, designed status or illustrative connection speed changed; no runtime transition inferred',sourceRefs});}
   if(canonical(p.confidence)!==canonical(n.confidence))changes.push({id:n.id,entity,change:'confidence',reason:'Explicit source confidence changed; absence is unknown, not a lower measured score',sourceRefs,before:p.confidence.join(', ')||'unknown',after:n.confidence.join(', ')||'unknown'});
   if(canonical(p.claims)!==canonical(n.claims))changes.push({id:n.id,entity,change:'verification',reason:'Reviewed external evidence changed; only exact source-revision claims are current',sourceRefs,before:p.claims.map(c=>c.claim+' '+c.sourceRevision+' '+c.freshness).join('; ')||'unknown',after:n.claims.map(c=>c.claim+' '+c.sourceRevision+' '+c.freshness).join('; ')||'unknown'});
  }
  for(const n of prior)if(!ids.has(n.id)){const removed=entity==='connection'&&sourceTombstones.has(n.id);changes.push({id:n.id,entity,change:removed?'removed':'not-in-scope',reason:removed?'Author-reviewed assertion removal backed by an explicit complete-scope GraphSnapshot predecessor tombstone; source receipts and authored evidence retained':'Absent from this scope; removal is not established without an explicit source tombstone',sourceRefs:n.sourceRefs,before:n.label});}
 }
 return {format:'diagramcloud.semantic-evolution/1',projectId:a.projectId,state,reasons,changes,before:{snapshotId:a.id,label:a.label,capturedAt:a.capturedAt,documentRevision:a.documentRevision,sourceIdentity:a.scope,revisionVector:a.revisionVector},after:{snapshotId:b.id,label:b.label,capturedAt:b.capturedAt,documentRevision:b.documentRevision,sourceIdentity:b.scope,revisionVector:b.revisionVector},staleEvidence:b.nodes.flatMap(n=>n.claims.filter(c=>c.freshness!=='exact-revision').map(c=>({nodeId:n.id,...c}))),note:'No single project revision, deployment order, causal effect, downtime or productivity is inferred'};
}
export function semanticEvolution(before:Project,after:Project){return compareEvolutionSnapshots(evolutionSnapshot(before),evolutionSnapshot(after));}
const phaseSchema=z.object({id,label:short,stage:z.enum(['current','transition','target','rollback']),basis:z.enum(['planned','unknown']),nodeIds:z.array(id).max(500),sourceIds:z.array(id).max(200),note:z.string().max(2000)}).strict();
export const migrationPlanSchema=z.object({format:z.literal('diagramcloud.migration-plan/1'),id,projectId:id,label:short,phases:z.array(phaseSchema).min(1).max(20),cutover:z.string().max(2000).default('UNKNOWN'),coexistence:z.string().max(2000).default('UNKNOWN'),rollback:z.string().max(2000).default('UNKNOWN')}).strict();
export type MigrationPlan=z.infer<typeof migrationPlanSchema>;
const historySchema=z.object({format:z.literal('diagramcloud.evolution-history/1'),projectId:id,snapshots:z.array(snapshotSchema).max(12),plans:z.array(migrationPlanSchema).max(10)}).strict();
export type EvolutionHistory=z.infer<typeof historySchema>;
export function readEvolutionHistory(doc:Project,strict=false):EvolutionHistory{
 const empty:EvolutionHistory={format:'diagramcloud.evolution-history/1',projectId:doc.id,snapshots:[],plans:[]},parts=doc.blocks.filter(b=>b.id.startsWith(PREFIX)).sort((a,b)=>Number(a.id.slice(PREFIX.length))-Number(b.id.slice(PREFIX.length)));
 if(!parts.length)return empty;try{if(parts.length>24||parts.some((b,i)=>b.type!=='code'||b.id!==PREFIX+i))throw new Error('Invalid receipt chunks');const text=parts.map(b=>b.type==='code'?b.code:'').join('');if(text.length>1000000)throw new Error('Receipt limit exceeded');const h=historySchema.parse(JSON.parse(text));if(h.projectId!==doc.id||new Set(h.snapshots.map(s=>s.id)).size!==h.snapshots.length||new Set(h.plans.map(p=>p.id)).size!==h.plans.length)throw new Error('Receipt identity conflict');return h;}catch{if(strict)throw new Error('Retained evolution receipts are invalid; download an authoring backup and repair them before changing history');return empty;}
}
/** Retention is a private evidence patch; it never rewrites inspected facts. */
function historyPatch(doc:Project,history:EvolutionHistory):Patch{
 validateDocument(doc);historySchema.parse(history);if(secretFindings(history).length)throw new Error('Sensitive evolution context refused');const root=doc.nodes.find(n=>doc.views.find(v=>v.id===doc.rootViewId)?.nodeIds.includes(n.id));if(!root)throw new Error('An existing root component is required to retain evolution receipts');
 const raw=JSON.stringify(history);if(raw.length>1000000)throw new Error('Evolution history exceeds 1 MiB; retain fewer snapshots');const blocks=doc.blocks.filter(b=>!b.id.startsWith(PREFIX)),nodes=structuredClone(doc.nodes);for(const n of nodes)n.blockIds=n.blockIds.filter(i=>!i.startsWith(PREFIX));
 for(const [index,code] of (raw.match(/[\s\S]{1,44000}/g)??[]).entries()){const id=PREFIX+index;blocks.push({id,title:'Private evolution receipt '+(index+1),type:'code',language:'json',code,visibility:'private',sourceIds:[],provenance:'author'});nodes.find(n=>n.id===root.id)!.blockIds.push(id);}
 const patch:Patch={format:'diagramcloud.patch',version:1,target:'project',targetId:doc.id,baseRevision:doc.revision,summary:'Retain private source-qualified evolution receipts and planned migration context; no runtime claims changed',operations:[{op:'replace',path:'/blocks',value:blocks},{op:'replace',path:'/nodes',value:nodes}]};applyDocumentPatch(doc,patch);return patch;
}
export function retainEvolutionSnapshotPatch(doc:Project,input:EvolutionSnapshot):Patch{
 const s=snapshotSchema.parse(input);if(s.projectId!==doc.id)throw new Error('Snapshot belongs to another project');const h=readEvolutionHistory(doc,true),prior=h.snapshots.find(x=>x.id===s.id);if(prior&&canonical(prior)!==canonical(s))throw new Error('Immutable snapshot identity conflict; choose a new snapshot ID');if(!prior){if(h.snapshots.length===12)throw new Error('History limit is 12 immutable snapshots; download a backup before selecting a narrower history');h.snapshots.push(s);}return historyPatch(doc,h);
}
export function migrationPlanPatch(doc:Project,input:unknown):Patch{
 const plan=migrationPlanSchema.parse(input);if(plan.projectId!==doc.id)throw new Error('Migration plan belongs to another project');for(const phase of plan.phases){if(new Set(phase.nodeIds).size!==phase.nodeIds.length||new Set(phase.sourceIds).size!==phase.sourceIds.length)throw new Error('Duplicate migration references');for(const n of phase.nodeIds)if(!doc.nodes.some(x=>x.id===n))throw new Error('Unknown migration component '+n);for(const s of phase.sourceIds)if(!doc.sources.some(x=>x.id===s))throw new Error('Unknown migration source '+s);}if(new Set(plan.phases.map(p=>p.id)).size!==plan.phases.length)throw new Error('Duplicate migration phase identity');const h=readEvolutionHistory(doc,true),at=h.plans.findIndex(p=>p.id===plan.id);if(at<0)h.plans.push(plan);else h.plans[at]=plan;return historyPatch(doc,h);
}
export function evolutionRecipes(s:EvolutionSnapshot){return ([['project',['system','cloud']],['repository',['code','git','cicd']],['work',['agents']],['knowledge',['decisions','evidence']],['data',['data']]] as const).map(([kind,perspectives])=>({kind,entities:s.nodes.filter(n=>n.perspectives.some(p=>(perspectives as readonly string[]).includes(p))).map(n=>({id:n.id,label:n.label,sourceRefs:n.sourceRefs,capturedAt:s.capturedAt,basis:n.sourceRefs.length?'static-source':'planned / unknown'}))}));}
