import type {ScanFile} from '../core/scan/scanner';
import {SECRET_FILE,IGNORED_DIR,outsideNestedRepositories} from '../core/scan/scanner';
import {GENERATED_PATH,GENERATED_HEADER,VENDOR_PATH} from '../core/scan/inventory';
import {secretInText} from '../core/secrets';
import {analyzeDomainFiles,type Domain} from './domainAdapters';
import {buildDocumentAnalysisBundle} from './documentBundle';
import {deepAnalyze,type DeepRuntime,DEEP_PARSER_VERSION} from './deepAnalysis';
import {validateAnalysisProfile,validateAnalysisBundle,sha256,canonicalJson,type AnalysisProfile,type AnalysisBundle} from './profile';

export const SOURCE_BUNDLE_PARSER='diagramcloud-source/1;domain/3;docs/1;imports/1';
const abort=(signal?:AbortSignal)=>{if(signal?.aborted)throw new DOMException('Selected source analysis cancelled','AbortError');};
const turn=()=>new Promise<void>(resolve=>setTimeout(resolve,0));
export const sourceSelectionPathAllowed=(path:string)=>!!path&&path.length<=500&&!/^(?:\/|[a-z]:)/i.test(path)&&!/[\\\u0000-\u001f]/.test(path)&&!path.split('/').some(s=>!s||s==='.'||s==='..')&&!SECRET_FILE.test(path)&&!VENDOR_PATH.test(path)&&((!IGNORED_DIR.test(path)&&!GENERATED_PATH.test(path))||/(^|\/)target\/manifest\.json$/i.test(path))&&!secretInText(path);
/** Genuine configured analysis over only supplied selected bytes. Lexical imports
 * are explicitly inferred; native declarations are static-source, not execution.
 * An optional deep runtime is supplied by the authorized caller, never initialized here. */
export async function buildSourceAnalysisBundle(input:readonly ScanFile[],identity:{repositoryId:string;revision:string},profileInput:AnalysisProfile,options:{signal?:AbortSignal;runtime?:DeepRuntime;onProgress?:(p:{read:number;total:number;path:string})=>void}={}):Promise<AnalysisBundle>{
 const profile=validateAnalysisProfile(profileInput);if(!/^[a-z][a-z0-9_.-]{0,79}$/.test(identity.repositoryId)||!identity.revision||identity.revision.length>120||secretInText(identity.revision))throw new Error('Invalid explicit repository identity/revision');if(profile.repositoryIds.length&&!profile.repositoryIds.includes(identity.repositoryId))throw new Error('Selected repository is outside the profile repository scope');
 if(!Array.isArray(input)||input.length>20000||input.some(f=>!f||typeof f.path!=='string'||typeof f.text!=='string'))throw new Error('Selected input must contain at most 20,000 explicit path/text files');
 const outside=new Set(outsideNestedRepositories([...input]).map(f=>f.path)),seen=new Set<string>(),files:ScanFile[]=[],diagnostics:string[]=[],omitted={items:0,links:0,sources:0};let bytes=0;
 const diag=(text:string)=>{if(diagnostics.length<2000)diagnostics.push(text.slice(0,1000));};
 for(const f of [...input].sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0)){abort(options.signal);if(seen.has(f.path))throw new Error('Duplicate selected source paths refused');seen.add(f.path);const size=new TextEncoder().encode(f.text).byteLength,inScope=!profile.scope.length||profile.scope.some(s=>f.path===s||f.path.startsWith(s.replace(/\/$/,'')+'/'));
  if(!inScope||!outside.has(f.path)||!sourceSelectionPathAllowed(f.path)||GENERATED_HEADER.test(f.text.slice(0,2048))||secretInText(f.text)||files.length>=profile.budgets.files||size>profile.budgets.fileBytes||bytes+size>profile.budgets.totalBytes){omitted.sources++;continue;}files.push({...f});bytes+=size;if(files.length%32===0)await turn();
 }
 if(omitted.sources)diag(omitted.sources+' selected inputs omitted by scope, nested repository/vendor/generated/secret safety or file/byte budgets; missing selection is not absent implementation.');
 const digests=new Map<string,string>();for(const [i,f] of files.entries()){abort(options.signal);digests.set(f.path,await sha256(f.text));options.onProgress?.({read:i+1,total:files.length,path:f.path});if(i%32===0)await turn();}
 const contentDigest=await sha256(canonicalJson([...digests])),items:AnalysisBundle['items']=[],links:AnalysisBundle['links']=[],sources:AnalysisBundle['sources']=[],itemIds=new Set<string>(),linkIds=new Set<string>(),sourceMap=new Map<string,string>(),fileMap=new Map(files.map(f=>[f.path,f]));
 const stable=async(prefix:string,key:string)=>prefix+'-'+(await sha256(identity.repositoryId+'\0'+key)).slice(0,32);
 const source=async(path:string,line:number,endLine=line)=>{const f=fileMap.get(path);if(!f||!Number.isInteger(line)||!Number.isInteger(endLine)||line<1||endLine<line||endLine>f.text.split('\n').length){omitted.sources++;diag('An analyzer supplied an unavailable selected-file line range; finding refused.');return undefined;}const key=path+':'+line+':'+endLine;if(sourceMap.has(key))return sourceMap.get(key);if(sources.length>=20000){omitted.sources++;return undefined;}const id=await stable('s',key+':'+identity.revision+':'+digests.get(path));sourceMap.set(key,id);sources.push({id,path,line,endLine,...identity,contentDigest:digests.get(path)!});return id;};
 const add=async(id:string,label:string,kind:string,refs:(string|undefined)[],confidence:AnalysisBundle['items'][number]['confidence'])=>{if(itemIds.has(id))return id;if(!refs.some(Boolean)||(!profile.includeInferred&&confidence!=='confirmed')||items.length>=profile.budgets.nodes){omitted.items++;return undefined;}itemIds.add(id);items.push({id,label:label.slice(0,160),kind,sourceIds:[...new Set(refs.filter((r):r is string=>!!r))].slice(0,100),confidence});return id;};
 const link=async(from:string|undefined,to:string|undefined,kind:string,refs:(string|undefined)[],confidence:AnalysisBundle['links'][number]['confidence'])=>{if(!from||!to||!itemIds.has(from)||!itemIds.has(to)||!refs.some(Boolean)||(!profile.includeInferred&&confidence!=='confirmed')||links.length>=profile.budgets.links){omitted.links++;return;}const sourceIds=[...new Set(refs.filter((r):r is string=>!!r))].slice(0,100),id=await stable('l',canonicalJson([from,to,kind,sourceIds]));if(linkIds.has(id))return;linkIds.add(id);links.push({id,from,to,kind,sourceIds,confidence});};
 const merge=async(bundle:AnalysisBundle)=>{const refs=new Map<string,string|undefined>(),ids=new Map<string,string|undefined>();for(const s of bundle.sources)refs.set(s.id,await source(s.path,s.line,s.endLine));for(const row of bundle.items)ids.set(row.id,await add(row.id,row.label,row.kind,row.sourceIds.map(id=>refs.get(id)),row.confidence));for(const row of bundle.links)await link(ids.get(row.from),ids.get(row.to),row.kind,row.sourceIds.map(id=>refs.get(id)),row.confidence);bundle.diagnostics.forEach(diag);omitted.items+=bundle.omitted.items;omitted.links+=bundle.omitted.links;omitted.sources+=bundle.omitted.sources;};
 if(profile.analyzers.includes('documents')){abort(options.signal);await merge(await buildDocumentAnalysisBundle(files,identity,profile));await turn();}
 const domains:Domain[]=profile.analyzers.filter(a=>['dbt','fabric','databricks','azure','dotnet'].includes(a)).map(a=>a as Domain);if(profile.analyzers.includes('imports'))domains.push('packages');
 if(domains.length){abort(options.signal);const native=analyzeDomainFiles(files,{domains}),ids=new Map<string,string|undefined>();for(const fact of native.facts)ids.set(fact.key,await add(await stable('n',fact.key),fact.label,'native-'+fact.domain+'-'+fact.kind,[await source(fact.path,fact.line)],'confirmed'));for(const edge of native.links)await link(ids.get(edge.from),ids.get(edge.to),'native-reference',[await source(edge.path,edge.line)],'confirmed');native.diagnostics.forEach(diag);diag('Selected native domains: '+domains.join(', ')+'. Native analyzer bounds '+native.limits.facts+' facts / '+native.limits.links+' links; their reported truncation remains diagnostic, never completeness.');await turn();}
 const fileIds=new Map<string,string|undefined>();if(profile.analyzers.includes('inventory')||profile.analyzers.includes('imports'))for(const f of files){abort(options.signal);fileIds.set(f.path,await add(await stable('f',f.path),f.path,'selected-source-file',[await source(f.path,1)],'confirmed'));}
 if(profile.analyzers.includes('imports')){
  let unresolved=0;for(const f of files.filter(f=>/\.(?:[cm]?[jt]sx?|py)$/i.test(f.path))){abort(options.signal);const python=/\.py$/i.test(f.path),matches=[...f.text.matchAll(python?/^[\t ]*from\s+(\.+[\w.]*)\s+import\s+/gm:/^[\t ]*(?:import\s+(?:[^'";\n]*\s+from\s*)?|export\s+[^'";\n]*\s+from\s*)['"]([^'"\n]+)['"]/gm)];
   for(const match of matches){const ref=match[1];if(!ref.startsWith('.')){unresolved++;continue;}const parent=f.path.split('/').slice(0,-1),raw=python?ref.replace(/^(\.+)(.*)$/,(_,dots:string,rest:string)=>'../'.repeat(dots.length-1)+'./'+rest.replace(/\./g,'/')):ref;let escaped=false;for(const part of raw.split('/')){if(!part||part==='.')continue;if(part==='..'){if(!parent.length){escaped=true;break;}parent.pop();}else parent.push(part);}if(escaped){unresolved++;continue;}const base=parent.join('/'),candidates=python?[base+'.py',base+'/__init__.py']:[base,...['.ts','.tsx','.js','.jsx','.mjs'].map(ext=>base+ext),base+'/index.ts',base+'/index.tsx',base+'/index.js'],targets=candidates.filter(path=>fileMap.has(path));if(targets.length!==1){unresolved++;continue;}await link(fileIds.get(f.path),fileIds.get(targets[0]),'lexical-relative-import',[await source(f.path,f.text.slice(0,match.index).split('\n').length)],'inferred');}
  }diag('Relative import candidates are lexical/inferred; no compiler binding, runtime call graph, alias configuration or external packages inferred. '+unresolved+' unresolved/external/ambiguous import candidates.');
 }
 if(profile.analyzers.includes('tree-sitter')){if(options.runtime){abort(options.signal);await merge(await deepAnalyze(files,profile,options.runtime,{...identity,signal:options.signal,onProgress:options.onProgress}));}else diag('Tree-sitter selected but no explicit runtime supplied: syntax analysis NOT_RUN. Native/documents/inventory output does not substitute for syntax analysis.');}
 abort(options.signal);const used=new Set([...items,...links].flatMap(row=>row.sourceIds));return validateAnalysisBundle({format:'diagramcloud.analysis-bundle',version:1,parserVersion:SOURCE_BUNDLE_PARSER+(profile.analyzers.includes('tree-sitter')&&options.runtime?';'+DEEP_PARSER_VERSION.replace('diagramcloud-','').replace('grammars-',''):''),profile,revisions:[{...identity,contentDigest}],items,links,sources:sources.filter(s=>used.has(s.id)),diagnostics,omitted});
}
