import {validateDocument,type Project} from '../core/model';
import {applyDocumentPatch,type Patch} from '../core/patch';
import {validateAnalysisBundle,type AnalysisBundle} from './profile';
import {SOURCE_BUNDLE_PARSER} from './sourceBundle';
/** Explicit author-selected bounded projection; never an observation or an apply. */
export function sourceBundlePatch(current:Project,input:AnalysisBundle,selected:string[]):Patch{
 const project=validateDocument(current),bundle=validateAnalysisBundle(input),wanted=new Set(selected);if(!selected.length||selected.length>60||wanted.size!==selected.length)throw new Error('Select 1–60 unique source analysis items');if(!bundle.parserVersion.startsWith(SOURCE_BUNDLE_PARSER))throw new Error('Only configured selected-source analysis is accepted');
 const items=bundle.items.filter(i=>wanted.has(i.id));if(items.length!==selected.length)throw new Error('Unknown selected source analysis item');const edges=bundle.links.filter(l=>wanted.has(l.from)&&wanted.has(l.to)).slice(0,150),sourceIds=new Set([...items,...edges].flatMap(i=>i.sourceIds)),sources=bundle.sources.filter(s=>sourceIds.has(s.id)),vector=bundle.revisions[0];if(!vector)throw new Error('Missing selected source revision identity');
 const viewId='analysis-view-'+vector.contentDigest.slice(0,20),navId=viewId+'-nav';if(project.nodes.length+items.length+1>500||project.edges.length+edges.length>1500||project.views.length>=80||project.blocks.length+items.length>1500||project.sources.length+sources.length>200)throw new Error('Selected source projection exceeds remaining Project limits');if(project.views.some(v=>v.id===viewId)||project.nodes.some(n=>n.id===navId)||items.some(i=>project.nodes.some(n=>n.id===i.id)||project.blocks.some(b=>b.id===i.id+'-analysis'))||sources.some(s=>project.sources.some(old=>old.id===s.id)))throw new Error('Selected source identity already exists; authored entities are not overwritten');if(project.atlas)for(const revision of bundle.revisions){const repo=project.atlas.snapshots.find(s=>s.id===project.atlas!.activeSnapshotId)!.repositories.find(r=>r.id===revision.repositoryId);if(!repo||repo.revision!==revision.revision)throw new Error('Source bundle is not the current declared atlas member revision');}
 const operations:Patch['operations']=sources.map(s=>({op:'add',path:'/sources/-',value:{id:s.id,title:(s.repositoryId+' '+s.path).slice(0,160),location:s.repositoryId+'@'+s.revision+':'+s.path+':'+s.line+'–'+(s.endLine??s.line)+' sha256:'+s.contentDigest,visibility:'private'}}));
 for(const item of items){const blockId=item.id+'-analysis';operations.push({op:'add',path:'/blocks/-',value:{id:blockId,title:'Configured selected-source analysis evidence',type:'text',text:bundle.parserVersion+'\n'+item.kind+' · '+item.confidence+'\n'+item.sourceIds.map(id=>{const s=sources.find(s=>s.id===id)!;return s.repositoryId+'@'+s.revision+' '+s.path+':'+s.line+'–'+(s.endLine??s.line)+' SHA-256 '+s.contentDigest;}).join('\n')+'\nNo code executed. Native declarations, document records and lexical candidates do not prove deployed or observed behavior.',provenance:'source-derived',sourceIds:item.sourceIds,visibility:'private'}},{op:'add',path:'/nodes/-',value:{id:item.id,label:item.label,kind:'source',provider:'Generic',icon:'generic',summary:'Selected '+item.kind+'; '+item.confidence+' static-source analysis. Runtime UNKNOWN.',blockIds:[blockId],sourceIds:item.sourceIds,tags:['Configured source analysis','Confidence: '+item.confidence],basis:item.confidence==='confirmed'?'static-source':'unknown',visibility:'private'}});}
 for(const edge of edges)operations.push({op:'add',path:'/edges/-',value:{id:edge.id,source:edge.from,target:edge.to,label:edge.kind+(edge.confidence==='confirmed'?'':' ('+edge.confidence+')'),kind:'dependency',basis:edge.confidence==='confirmed'?'static-source':'unknown',visibility:'private'}});
 const root=project.views.find(v=>v.id===project.rootViewId)!;operations.push({op:'add',path:'/views/-',value:{id:viewId,title:'Selected source analysis',description:bundle.parserVersion+'; bounded selected projection. Runtime and coverage UNKNOWN.',nodeIds:items.map(i=>i.id),edgeIds:edges.map(e=>e.id),positions:Object.fromEntries(items.map((i,n)=>[i.id,{x:n%3*300,y:Math.floor(n/3)*180}])),perspective:'code',visibility:'private'}},{op:'add',path:'/nodes/-',value:{id:navId,label:'Selected source analysis',kind:'control',icon:'generic',summary:'Explicit configured source analysis; not runtime observations.',basis:'static-source',visibility:'private',childViewId:viewId}},{op:'add',path:'/views/@'+root.id+'/nodeIds/-',value:navId},{op:'add',path:'/views/@'+root.id+'/positions/'+navId,value:{x:root.nodeIds.length%3*300,y:Math.floor(root.nodeIds.length/3)*180}});
 const patch:Patch={format:'diagramcloud.patch',version:1,target:'project',targetId:project.id,baseRevision:project.revision,summary:'Review '+items.length+' selected static analysis items and '+edges.length+' source-cited relationships. '+(bundle.links.filter(l=>wanted.has(l.from)&&wanted.has(l.to)).length-edges.length)+' selected relationships omitted by the 150-edge projection limit; original generated bundle remains complete within its declared budgets.',operations};applyDocumentPatch(project,patch);return patch;
}
