import {DESIGN_TYPES,validateDocument,type DesignType,type Project} from '../core/model';
import {publicDocument} from '../core/operations';
import {viewSpec} from '../core/viewspec';
import {parseXml,type XmlElement} from '../core/interchange/xml';
import {designSvg} from '../export/design';
import {designContext} from '../export/design/context';
import {chartableTable} from '../export/design/chart';
import {heatmapColumns} from '../export/design/heatmap';
import {treemapHierarchy} from '../export/design/treemap';
import {sankeyUnit} from '../export/design/sankey';
import {waterfallTable,waterfallValues} from '../export/design/waterfall';
import {recommendFigures} from '../export/design/recommend';
import {defects} from '../export/design/quality';
import {buildScene} from '../export/scene';
import {layoutCrossings} from '../core/layout';
type Check={id:string;state:'passed'|'failed'|'unknown'|'not-applicable';reason:string};
const flatten=(node:XmlElement):XmlElement[]=>[node,...node.children.flatMap(flatten)];
/** Semantic encoding QA over public facts and actual generated figure metadata.
 * Unsupported figures remain unsupported; no quantity or timeline is invented. */
export function semanticVisualQuality(input:Project,viewId:string,figure:string,svgInput?:string){
 const doc=publicDocument(validateDocument(input));if(!doc.views.some(v=>v.id===viewId))throw new Error('Quality view is unavailable in public projection');
 if(!DESIGN_TYPES.includes(figure as DesignType)||figure==='auto')return {format:'diagramcloud.semantic-visual-quality/1',viewId,figure,state:'UNSUPPORTED',checks:[{id:'figure',state:'unknown',reason:'No supported renderer or semantic encoding contract for this figure.'}] as Check[]};
 const type=figure as Exclude<DesignType,'auto'>,svg=svgInput??designSvg(doc,viewId,{type,now:new Date('2000-01-01T00:00:00Z')}),elements=flatten(parseXml(svg)),text=elements.map(e=>e.text).join(' '),checks:Check[]=[];
 const check=(id:string,condition:boolean,reason:string)=>checks.push({id,state:condition?'passed':'failed',reason});
 const spec=viewSpec(doc,viewId),root=elements.find(e=>e.name==='svg');check('figure-identity',root?.attrs['data-design-type']===type,'Actual figure metadata must match the chosen encoding.');
 check('offline',!/<(?:script|foreignObject)\b|(?:href|src)="https?:/i.test(svg),'Only generated offline content is accepted.');
 if(type==='sankey'){
  const unit=sankeyUnit(spec.edges),bands=elements.filter(e=>e.attrs['data-dd-edge']&&Object.hasOwn(e.attrs,'data-dd-value'));
  const expected=spec.edges.filter(e=>e.quantity&&e.quantity.unit===unit&&e.from!==e.to);
  check('sankey-source-quantities',bands.length===expected.length&&new Set(bands.map(e=>e.attrs['data-dd-edge'])).size===expected.length&&bands.every(e=>{const edge=expected.find(x=>x.id===e.attrs['data-dd-edge']);return edge&&Number(e.attrs['data-dd-value'])===edge.quantity!.value&&e.attrs['data-dd-unit']===unit&&e.attrs['data-dd-provenance']===edge.quantity!.provenance;}),'Every band must preserve its exact supplied amount, unit and provenance; other units are never summed.');
  check('sankey-synthetic',!expected.some(e=>e.quantity!.provenance==='synthetic')||/synthetic/i.test(text),'Synthetic quantities must remain visibly labelled.');
  check('sankey-order',!bands.length||/not timing/i.test(text),'Connection-derived columns must not claim measured timing.');
  if(bands.length){const largest=[...bands].sort((a,b)=>Number(b.attrs['data-dd-value'])-Number(a.attrs['data-dd-value']))[0],scale=Number(largest.attrs['data-dd-value'])>0?Number(largest.attrs['data-dd-thickness'])/Number(largest.attrs['data-dd-value']):0;
   check('sankey-proportional-widths',Number.isFinite(scale)&&bands.every(b=>{const h=Number(b.attrs['data-dd-thickness']),coordinates=b.attrs.d?.match(/[-+]?(?:\d*\.)?\d+/g)?.map(Number);return Math.abs(h-Math.max(1,Number(b.attrs['data-dd-value'])*scale))<.03&&!!coordinates&&Math.abs(coordinates[9]-coordinates[7]-h)<.03;}),'Actual band thickness and path geometry must share a linear quantity scale, with the documented one-pixel floor.');
   for(const n of spec.nodes){const incoming=expected.filter(e=>e.to===n.id).reduce((s,e)=>s+e.quantity!.value,0),outgoing=expected.filter(e=>e.from===n.id).reduce((s,e)=>s+e.quantity!.value,0);if(expected.some(e=>e.from===n.id||e.to===n.id))checks.push({id:'sankey-balance:'+n.id,state:'unknown',reason:`${n.id}: ${incoming} ${unit} incoming; ${outgoing} ${unit} outgoing; difference ${incoming-outgoing} ${unit}. Conservation applicability UNKNOWN: no supplied closed-flow assumption; boundary inputs, storage or transformation may explain differences. Only selected quantified connections in this unit are counted.`});}
  }
 }else if(type==='waterfall'){
  const found=waterfallTable(designContext(doc,viewId,type));if(!found)checks.push({id:'waterfall-unavailable',state:'unknown',reason:'No public numeric column supports a signed increment interpretation; no values are invented.'});else{const values=waterfallValues(found),bars=elements.filter(e=>e.attrs['data-waterfall-row']!==undefined),plot=elements.find(e=>e.attrs['data-waterfall-plot']!==undefined);check('waterfall-provenance',elements.some(e=>e.attrs['data-provenance']===found.block.provenance)&&(found.block.provenance!=='synthetic'||/synthetic/i.test(text)),'Supplied table provenance remains visible; synthetic increments never become measured totals.');check('waterfall-derived-sum',/derived/i.test(text)&&/not supplied observed totals, causal effects or timing/i.test(text),'Running sums are derived over the shown numeric increments, never observations, causality or timing.');
   if(!values.finite){check('waterfall-numeric-limit',bars.length===0&&/exceeds finite numeric limits/i.test(text),'Non-finite derived arithmetic must refuse the plot.');checks.push({id:'waterfall-partial-arithmetic',state:'unknown',reason:'Supplied values cannot produce a finite displayed running sum.'});}else{const expected=values.rows.filter(r=>r.value!==null),nums=[0,...values.rows.flatMap(r=>[r.start,r.end])],magnitude=Math.max(1,...nums.map(Math.abs)),low=Math.min(...nums)/magnitude,high=Math.max(...nums)/magnitude,lo=low===high?-1:low,hi=low===high?1:high;
    check('waterfall-source-increments',bars.length===expected.length&&new Set(bars.map(e=>e.attrs['data-waterfall-row'])).size===expected.length&&bars.every(b=>{const row=expected.find(r=>String(r.index)===b.attrs['data-waterfall-row']);return row&&Number(b.attrs['data-delta'])===row.value&&Number(b.attrs['data-start'])===row.start&&Number(b.attrs['data-end'])===row.end&&b.children.find(e=>e.name==='title')?.text===row.label+' · '+found.block.columns[found.column]+': '+row.value+'; derived sum '+row.start+' → '+row.end;}),'Every supplied signed increment, row label and derived start/end must match the selected public evidence.');
    const py=Number(plot?.attrs['data-plot-y']),ph=Number(plot?.attrs['data-plot-height']),Y=(v:number)=>py+ph-(v/magnitude-lo)/(hi-lo)*ph;
    check('waterfall-geometric-encoding',!!plot&&Number(plot.attrs['data-scale-magnitude'])===magnitude&&Number(plot.attrs['data-scale-low'])===lo&&Number(plot.attrs['data-scale-high'])===hi&&Number.isFinite(py)&&ph>0&&bars.every(b=>{const row=expected.find(r=>String(r.index)===b.attrs['data-waterfall-row']);return row&&Math.abs(Number(b.attrs.y)-Math.min(Y(row.start),Y(row.end)))<.03&&Math.abs(Number(b.attrs.height)-Math.max(.5,Math.abs(Y(row.end)-Y(row.start))))<.03&&Number(b.attrs.width)>0;})&&elements.some(e=>e.attrs['data-waterfall-zero']!==undefined&&Math.abs(Number(e.attrs.y1)-Y(0))<.03&&Math.abs(Number(e.attrs.y2)-Y(0))<.03),'Actual rectangle positions and heights encode signed start/end on one linear zero-referenced scale; tiny/zero increments use a half-pixel visibility floor.');
    check('waterfall-connectors',elements.filter(e=>e.attrs['data-waterfall-connector']!==undefined).length===expected.filter(r=>r.index<values.rows.length-1).length&&elements.filter(e=>e.attrs['data-waterfall-connector']!==undefined).every(e=>{const row=values.rows.find(r=>String(r.index)===e.attrs['data-waterfall-connector']);return row&&Math.abs(Number(e.attrs.y1)-Y(row.end))<.03&&Math.abs(Number(e.attrs.y2)-Y(row.end))<.03;}),'Connectors align with the preceding derived cumulative endpoint, never a separate measured value.');
    if(values.omitted){check('waterfall-omission-ledger',text.includes(values.omitted+' further source row(s) not drawn'),'Excluded source rows are visibly counted and excluded from the displayed sum.');checks.push({id:'waterfall-bounded-projection',state:'unknown',reason:values.omitted+' rows remain in the source evidence but are excluded from this bounded readable presentation and its displayed derived sum.'});}if(values.missing)checks.push({id:'waterfall-missing-values',state:'unknown',reason:values.missing+' missing supplied values are visible gaps and excluded from the partial displayed sum; never zero-filled.'});if(!found.incrementLabel)checks.push({id:'waterfall-increment-interpretation',state:'unknown',reason:'The supplied numeric column does not explicitly label deltas; the chosen figure interprets it as increments.'});
   }
  }
 }else if(['chart','line','heatmap'].includes(type)){
  const found=chartableTable(designContext(doc,viewId,type));if(found){check('table-provenance',elements.some(e=>e.attrs['data-provenance']===found.block.provenance),'Printed provenance must match the selected public table block.');check('table-synthetic',found.block.provenance!=='synthetic'||/synthetic/i.test(text),'Synthetic numeric values are never measured or verified results.');
   const rows=found.block.rows.slice(0,24),columns=type==='heatmap'?heatmapColumns(found.block):found.series,marks=elements.filter(e=>e.attrs['data-value']!==undefined);
   const expected=rows.flatMap((row,i)=>columns.flatMap(k=>typeof row[k]==='number'?[`${String(row[found.category]??i+1)} · ${found.block.columns[k]}: ${row[k]}`]:[])).sort(),actual=marks.map(e=>e.children.find(c=>c.name==='title')?.text??'').sort();
   check('table-values-and-labels',JSON.stringify(actual)===JSON.stringify(expected)&&marks.every(e=>e.children.find(c=>c.name==='title')?.text.endsWith(': '+Number(e.attrs['data-value']))),'Each rendered mark must preserve the supplied numeric value, category and series, within the explicit 24-row limit.');
   if(type==='heatmap')check('heatmap-column-scale',marks.every(e=>{const k=found.block.columns.indexOf(e.attrs['data-column']),values=rows.flatMap(r=>typeof r[k]==='number'?[r[k] as number]:[]),lo=Math.min(...values),hi=Math.max(...values),value=Number(e.attrs['data-value']),norm=hi===lo?.5:(value-lo)/(hi-lo);return k>=0&&Math.abs(Number(e.attrs['data-norm'])-norm)<.006&&Math.abs(Number(e.attrs['fill-opacity'])-(.06+.8*norm))<.006;}),'Heatmap shading must normalize independently within each numeric column; constant columns use the midpoint.');
   if(type==='chart'&&marks.some(e=>Math.abs(Number(e.attrs['data-value']))>0)){const largest=[...marks].sort((a,b)=>Math.abs(Number(b.attrs['data-value']))-Math.abs(Number(a.attrs['data-value'])))[0],scale=Number(largest.attrs.height)/Math.abs(Number(largest.attrs['data-value']));check('bar-magnitude-scale',marks.every(e=>Math.abs(Number(e.attrs.height)-Math.max(.5,Math.abs(Number(e.attrs['data-value']))*scale))<.03),'Bar magnitudes share one zero-based linear scale, including negative values; zero/tiny bars use only the documented half-pixel floor.');}
  }else checks.push({id:'table-unavailable',state:'unknown',reason:'No public numeric table supports the selected encoding; the figure must remain an empty explanation.'});
 }else if(type==='treemap'){
  check('treemap-area',/area is proportional to components/i.test(text)&&/placement/i.test(text),'Area counts component placements through the public view hierarchy; it is not cost, performance or productivity.');
  const hierarchy=treemapHierarchy(doc),weights=new Map<string,number>();const walk=(n:typeof hierarchy.root)=>{weights.set(n.viewId,n.total);n.children.forEach(walk);};walk(hierarchy.root);
  const tiles=elements.filter(e=>e.attrs['data-view-ref']);check('treemap-source-weights',tiles.every(e=>weights.get(e.attrs['data-view-ref'])===Number(e.attrs['data-weight']))&&new Set(tiles.map(e=>e.attrs['data-view-ref'])).size===tiles.length,'Every displayed tile weight must equal public component placements in its bounded view hierarchy; omitted tiny/deep tiles do not invent another measure.');
 }
 else if(type==='sequence')check('sequence-order',/order/i.test(text)&&/not (?:from )?timing|not measured/i.test(text),'Sequence order is derived from connections and must not assert timing.');
 else if(type==='status')check('status-designed',/designed status/i.test(text)&&/not an observation/i.test(text),'Status columns reflect designed status, never observed deployment.');
 else if(type==='atlas'){if(doc.atlas)check('atlas-revisions',/no single project revision/i.test(text),'An atlas must keep repository revisions independent.');else checks.push({id:'atlas-unavailable',state:'unknown',reason:'No atlas snapshot is supplied; repository revisions remain unknown.'});}
 else if(type==='timeline')check('timeline-story',/story/i.test(text),'Timeline uses selected story steps; it does not invent external event dates.');
 else checks.push({id:'public-view-contract',state:'passed',reason:'This categorical architecture encoding consumes the public ViewSpec; no magnitude, timing or observed state is inferred.'});
 return {format:'diagramcloud.semantic-visual-quality/1',viewId,figure:type,state:checks.some(c=>c.state==='failed')?'DEFECTS_FOUND':checks.some(c=>c.state==='unknown')?'PARTIAL':'SEMANTICS_CHECKED',checks};
}
/** Three reasoned render choices of the same facts. Scores are transparent local
 * ranking heuristics, never release qualification or calibrated probabilities. */
export function compareRenderCandidates(input:Project,viewId:string){const doc=publicDocument(validateDocument(input)),view=doc.views.find(v=>v.id===viewId);if(!view)throw new Error('Candidate comparison requires a public view');if(view.nodeIds.length>100||view.edgeIds.length>300)throw new Error('Candidate comparison exceeds 100 components / 300 connections; choose a narrower view');
 const scene=buildScene(doc,view),crossings=layoutCrossings(doc.edges.filter(e=>view.edgeIds.includes(e.id)).map(e=>({from:e.source,to:e.target})),Object.fromEntries(scene.nodes.map(n=>[n.id,{x:n.x,y:n.y}]))),sceneTruncations=scene.nodes.reduce((sum,n)=>sum+[n.label,n.provider,n.summary,n.footer].filter(t=>t.truncated).length,0)+scene.edges.filter(e=>e.label?.truncated).length;
 const weights={semanticDefect:20,geometricDefect:5,unresolvedTransform:1,sourceLayoutCrossing:1,sceneTruncation:1};
 const candidates=recommendFigures(doc,viewId).slice(0,3).map((r,i)=>{const svg=designSvg(doc,viewId,{type:r.type,now:new Date('2000-01-01T00:00:00Z')}),geometry=defects(svg,r.type),semantic=semanticVisualQuality(doc,viewId,r.type,svg),semanticFailures=semantic.checks.filter(c=>c.state==='failed').length;
  const metrics={geometricDefects:geometry.failures.length,textBoxes:geometry.texts,componentShapes:geometry.components,unresolvedTransforms:geometry.unresolved+geometry.unresolvedShapes,semanticDefects:semanticFailures,sourceLayoutCrossings:crossings,sourceSceneTruncations:sceneTruncations,svgBytes:new TextEncoder().encode(svg).byteLength};
  const score=Math.max(0,100-semanticFailures*weights.semanticDefect-geometry.failures.length*weights.geometricDefect-Math.min(20,metrics.unresolvedTransforms)-Math.min(20,crossings)-Math.min(10,sceneTruncations));
  return {id:['A','B','C'][i],figure:r.type,suitability:r.score,reason:r.reason,score,metrics,geometry,semantic,svg,proposal:{format:'diagramcloud.design-brief',version:1,projectId:doc.id,views:[{viewId,type:r.type,why:r.reason}]},state:'REQUIRES_AUTHOR_REVIEW'};});
 return {format:'diagramcloud.render-candidate-comparison/1',projectId:doc.id,projectRevision:doc.revision,viewId,weights,candidates,note:'Scores subtract stated defect penalties from 100. Source-layout crossings/truncations describe the common authored scene, not every specialized figure route. Comparison never applies a choice or changes facts.'};}
