import {assetFidelity} from '../export/assetFidelity';
import type {Project} from '../core/model';
import {publicDocument} from '../core/operations';
import {download,pngFromSvg} from '../export/browser';
import {loadBrowserIcons} from '../export/iconData';
import {vendorIconsIn} from '../core/icons';
import {portfolioHtml} from '../export/html';
import {svgDiagram,mermaidDiagram} from '../export/diagram';
import {projectOverviewHtml} from '../export/projectOverview';
import {styledSvg} from '../export/styled';
import {designSvg} from '../export/design';
import {designBookHtml} from '../export/design/book';
import {technicalManualHtml} from '../export/manual';
import {conceptSpec} from '../export/concept';
import {viewSpec} from '../core/viewspec';
import {atlasnoteCheatsheetJson} from '../export/atlasnote';
import {drawioDiagram} from '../export/drawio';
import {portfolioIndexJson,indexSummary} from '../export/portfolioIndex';
export async function exportProject(project:Project,activeView:string,format:string,setMessage:(message:string)=>void){const safe=publicDocument(project),viewId=safe.views.some(v=>v.id===activeView)?activeView:safe.rootViewId,icons=await loadBrowserIcons(vendorIconsIn(safe),import.meta.env.BASE_URL);if(format==='asset-fidelity'){download(JSON.stringify(['classic','powerpoint','design','blueprint','editorial'].map(renderer=>assetFidelity(project,viewId,renderer as 'classic',icons)),null,2),project.id+'.'+viewId+'.asset-fidelity.json','application/json');setMessage('Public artwork fidelity exported for all renderer families.');return;}if(format==='overview-html')download(projectOverviewHtml(project),`${project.id}.overview.html`,'text/html;charset=utf-8');if(format==='json')download(JSON.stringify(safe,null,2),`${project.id}.public.json`,'application/json');if(format==='authoring')download(JSON.stringify(project,null,2),`${project.id}.authoring.json`,'application/json');if(format==='svg')download(svgDiagram(project,viewId,true,icons),`${project.id}-${viewId}.svg`,'image/svg+xml');if(format==='png')download(await pngFromSvg(svgDiagram(project,viewId,false,icons)),`${project.id}-${viewId}.png`);if(format==='html')download(portfolioHtml(project,icons),`${project.id}.html`,'text/html');if(format==='mermaid')download(mermaidDiagram(project,viewId),`${project.id}-${viewId}.mmd`);if(format==='blueprint'||format==='editorial'){download(styledSvg(project,viewId,format),`${project.id}.${viewId}.${format}.svg`,'image/svg+xml');setMessage(format==='blueprint'?'Blueprint drawing created: the current public view with grid, zone references, typed lines, legend and a title block (project, view, revisions, date, provenance).':'Editorial figure created: the current public view with numbered callouts and a key.');return;}
  if(format==='design-deck'){const {downloadDesignDeck}=await import('../export/design/slides');const toUrl=(b:Blob)=>new Promise<string>((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(String(fr.result));fr.onerror=()=>no(new Error('PNG export failed'));fr.readAsDataURL(b);});const n=await downloadDesignDeck(project,`${project.id}.figures.pptx`,{raster:async svg=>toUrl(await pngFromSvg(svg))});setMessage(`Diagram Design deck created: ${n} slides, a cover and every public view as its figure (pictures with alt text).`);return;}
  if(format==='design-book'){download(designBookHtml(project),`${project.id}.figures.html`,'text/html');setMessage('Figure book exported: every public view as its Diagram Design figure on one offline page.');return;}
  if(format==='design'){download(designSvg(project,viewId),`${project.id}.${viewId}.design.svg`,'image/svg+xml');setMessage('Diagram Design figure created: the current public view with the figure type, focal components and theme stored on the view (Architecture and light by default). Use Diagram Design mode to try other figures.');return;}
  if(format==='manual'){download(technicalManualHtml(project),`${project.id}.manual.html`,'text/html');setMessage('Technical manual exported: one static page per view with the snapshot, revision vector, provenance and omissions on its cover. Open it and print to PDF for a paper copy.');return;}
  if(format==='concept'){const {spec,report}=conceptSpec(project,viewId);download(JSON.stringify(spec,null,2)+'\n',`${project.id}.${viewId}.concept.json`,'application/json');setMessage(`MosaicStudio concept spec exported (datapass.concept-spec 1.0.0): ${report.kept.join(' ')} Not carried: ${report.lost.slice(0,4).join(' ')}${report.lost.length>4?` … and ${report.lost.length-4} more.`:''}`);return;}
  if(format==='viewspec'){download(JSON.stringify(viewSpec(project,viewId),null,2),`${project.id}.${viewId}.viewspec.json`,'application/json');setMessage('View spec exported: the current public view as renderer-neutral JSON (nodes, typed edges, basis, confidence, evidence references, drilldown path, revision vector).');return;}
  if(format==='atlasnote'){download(atlasnoteCheatsheetJson(project),`${project.id}.atlasnote.json`,'application/json');setMessage('AtlasNote cheatsheet created: one page per public view with its diagram and component table. In AtlasNote, open Cheatsheet source, load the file, validate and save.');return;}
  if(format==='drawio'){download(drawioDiagram(project),`${project.id}.drawio`,'application/xml');setMessage('draw.io file created: every public view is a page, with drilldown links between pages. Open it in diagrams.net or the draw.io VS Code extension.');return;}if(format==='pptx'){const {exportPptx}=await import('../export/pptx');await exportPptx(project,icons);}if(format==='index'){download(portfolioIndexJson(project),`${project.id}.portfolio-index.json`,'application/json');setMessage(`Portfolio index exported (${indexSummary(project)}). Storing it in DATAPASSCONTROL for Mongoku is a separate, operator-reviewed step.`);return;}if(format==='deck'){const {downloadDeck,projectPlan}=await import('../export/deck');const slides=await downloadDeck(projectPlan(project),`${project.id}.deck.pptx`,icons);setMessage(`Project deck created: ${slides} slides (architecture and every public task screen). Private and draft content is left out.`);return;}setMessage(`${format.toUpperCase()} export created${format==='authoring'?' · includes private fields':''}.`);}
