import {validateDocument,type Project} from '../../core/model';
import {publicDocument} from '../../core/operations';
import {deliveryCoverageMatrix,deliveryGates,releaseChain,evidenceFreshness} from '../../intelligence/delivery';
import {measureLines} from '../measure';
import {xml} from '../diagram';
export const DELIVERY_PROFILES=['environment','release-chain','promotion'] as const;
export type DeliveryProfile=typeof DELIVERY_PROFILES[number];
export type DeliveryFigureOptions={page?:number;environmentPage?:number;at?:string;maxAgeHours?:number};
const TITLE:Record<DeliveryProfile,string>={environment:'Environment matrix','release-chain':'Source → build → artifact → release → instance',promotion:'Promotion topology and declared gates'};
const W=1152,M=36,INK='#20344f',MUTED='#526782',RULE='#cbd6e4',BLUE='#285d9a';
const text=(value:string,x:number,y:number,width:number,size=12,max=2,bold=false)=>measureLines(value,width,{size,bold},max).lines.map((line,i)=>`<text x="${x}" y="${y+i*(size+5)}" font-size="${size}" fill="${bold?INK:MUTED}"${bold?' font-weight="600"':''}>${xml(line)}</text>`).join('');
const chip=(value:string,x:number,y:number,kind='declared')=>`<g data-delivery-chip="${xml(kind)}"><title>${xml(value)}</title><rect x="${x}" y="${y}" width="152" height="22" rx="4" fill="${kind==='reviewed'?'#e9f1fc':'#eef1f5'}" stroke="${RULE}"/>${text(kind==='reviewed'?'REVIEWED CLAIM':value,x+8,y+15,136,10,1,true)}</g>`;
function card(id:string,label:string,lines:string[],x:number,y:number,width=166,height=154,kind='declared'){
 return `<g data-node-id="${xml(id)}"><title>${xml([label,...lines].join('\n'))}</title><rect x="${x}" y="${y}" width="${width}" height="${height}" rx="8" fill="#fff" stroke="${RULE}"/>${text(label,x+12,y+23,width-24,13,2,true)}${chip(kind==='reviewed'?'REVIEWED EXTERNAL CLAIM':kind==='unknown'?'UNKNOWN':kind==='not-applicable'?'NOT APPLICABLE':'DECLARED',x+7,y+50,kind)}${lines.slice(0,3).map((line,i)=>text(line,x+12,y+92+i*21,width-24,10,1)).join('')}</g>`;
}
/** Public static projection of canonical delivery metadata, never an editable graph or a runtime verdict. */
export function deliveryFigure(input:Project,profile:DeliveryProfile,options:DeliveryFigureOptions={}){
 const p=publicDocument(validateDocument(input)),at=options.at??new Date().toISOString(),maxAgeHours=options.maxAgeHours??24;
 if(!Number.isFinite(Date.parse(at))||!Number.isFinite(maxAgeHours)||maxAgeHours<0)throw new Error('Choose a valid delivery capture time and evidence age policy');
 let page=Math.max(0,Math.floor(options.page??0)),environmentPage=Math.max(0,Math.floor(options.environmentPage??0));
 if(!Number.isFinite(page)||!Number.isFinite(environmentPage))throw new Error('Invalid delivery figure page');
 const instanceNodes=new Set(p.delivery?.instances.map(i=>i.nodeId)),componentIds=p.delivery?.environments.length?p.nodes.filter(n=>!n.childViewId&&!instanceNodes.has(n.id)).map(n=>n.id):[];
 let body='',bottom=180,totalPages=1,totalEnvironmentPages=1,shown=0,total=0;
 const omission={environments:0,promotions:0,reason:''};
 if(profile==='environment'){
  const environments=p.delivery?.environments??[];total=componentIds.length*environments.length;totalPages=Math.max(1,Math.ceil(componentIds.length/6));totalEnvironmentPages=Math.max(1,Math.ceil(environments.length/4));page=Math.min(page,totalPages-1);environmentPage=Math.min(environmentPage,totalEnvironmentPages-1);
  const envs=environments.slice(environmentPage*4,environmentPage*4+4),components=componentIds.slice(page*6,page*6+6),cells=deliveryCoverageMatrix(p,{componentIds:components,at,maxAgeHours});
  envs.forEach((e,i)=>{body+=text(e.label,M+200+i*220,158,206,14,2,true)+text((e.sourceIds.length?'Cited':'Author')+' declaration · '+(e.role??'role UNKNOWN'),M+200+i*220,197,206,10,1);});
  components.forEach((id,row)=>{const node=p.nodes.find(n=>n.id===id)!,y=226+row*178;body+=text(node.label,M,y+28,176,13,3,true);envs.forEach((e,col)=>{const cell=cells.find(c=>c.componentId===id&&c.environmentId===e.id)!,claim=cell.instances.find(i=>i.observed),lines=cell.state==='not-applicable'?[cell.reason??'Author exclusion']:cell.instances.length?[cell.instances.map(i=>i.artifact?.version??'artifact UNKNOWN').join(', '),claim?.observed?claim.observed.claim+' · '+claim.observed.capturedAt:'Runtime UNKNOWN',claim?claim.freshness+' · '+claim.observed?.authority:'No reviewed external claim']:['No public instance declaration','Runtime UNKNOWN'];body+=card('cell-'+id+'-'+e.id,cell.state==='reviewed-claim'?'Declared instance + claim':cell.state==='declared'?'Declared instance':cell.state,lines,M+200+col*220,y,208,154,cell.state==='reviewed-claim'?'reviewed':cell.state==='declared'?'declared':cell.state==='not-applicable'?'not-applicable':'unknown');shown++;});bottom=y+164;});
 }else if(profile==='release-chain'){
  const chains=releaseChain(p);total=chains.length;totalPages=Math.max(1,Math.ceil(total/5));page=Math.min(page,totalPages-1);chains.slice(page*5,page*5+5).forEach((chain,row)=>{const y=156+row*194,claims=chain.instances.flatMap(i=>p.observations.filter(o=>o.nodeId===i.nodeId&&o.reviewedAt));
   const stages=[['Source',[chain.sourceRepositoryId,chain.sourceRevision,chain.basis]],['Build',[chain.buildId,'Independent build identity']],['Artifact',[chain.artifact.label,chain.artifact.version,chain.digest]],['Release',[chain.releases.map(r=>r.label).join(', ')||'UNKNOWN','Independent release identity']],['Instance',[chain.instances.map(i=>p.nodes.find(n=>n.id===i.nodeId)?.label??i.id).join(', ')||'UNKNOWN',chain.instances.map(i=>p.delivery?.environments.find(e=>e.id===i.environmentId)?.label).join(', ')||'Environment UNKNOWN',claims.length?claims.map(o=>o.claim+' at '+o.observedAt+' · '+evidenceFreshness(o.observedAt,{at,maxAgeHours})+' · claim source '+o.sourceRevision+' by '+o.authority).join('; '):'Runtime UNKNOWN']]];
   stages.forEach(([label,lines],i)=>{const x=M+i*220;body+=card(chain.artifact.id+'-stage-'+i,label as string,lines as string[],x,y,198,154,i===4&&claims.length?'reviewed':'declared');if(i<4)body+=`<path d="M ${x+198} ${y+77} H ${x+217}" stroke="${BLUE}" stroke-width="1.5" marker-end="url(#delivery-arrow)"/>`;});bottom=y+164;shown++;
  });
 }else{
  const citedEnvironments=new Set(p.delivery?.environments.filter(e=>e.sourceIds.length).map(e=>e.id)),allPromotions=deliveryGates(p,{at,maxAgeHours}),promotions=allPromotions.filter(row=>citedEnvironments.has(row.fromEnvironmentId)&&citedEnvironments.has(row.toEnvironmentId));
  omission.environments=(p.delivery?.environments.length??0)-citedEnvironments.size;omission.promotions=allPromotions.length-promotions.length;omission.reason='Promotion figures require public source citations on both environment declarations. Uncited author declarations remain valid in the matrix/release profiles; missing citations do not prove undeployed environments.';
  total=promotions.length;totalPages=Math.max(1,Math.ceil(total/5));page=Math.min(page,totalPages-1);promotions.slice(page*5,page*5+5).forEach((promotion,row)=>{const y=156+row*216,from=p.delivery!.environments.find(e=>e.id===promotion.fromEnvironmentId)!,to=p.delivery!.environments.find(e=>e.id===promotion.toEnvironmentId)!,artifact=p.delivery!.artifacts.find(a=>a.id===promotion.artifactId),release=p.delivery!.releases?.find(r=>r.id===promotion.releaseId);
   body+=card(promotion.id+'-from',from.label,[from.sourceIds.length?'Cited environment declaration':'Author environment declaration',from.role??'role UNKNOWN'],M,y,220,154);
   body+=card(promotion.id+'-gate','Declared gates',[promotion.gates.map(g=>g.label).join(', ')||'No declared gates',artifact?'Artifact '+artifact.version:'Artifact UNKNOWN',release?'Release '+release.label:'Release UNKNOWN'],M+330,y,330,154,promotion.gates.some(g=>g.result)?'reviewed':'declared');
   body+=card(promotion.id+'-to',to.label,[to.sourceIds.length?'Cited environment declaration':'Author environment declaration',to.role??'role UNKNOWN'],M+770,y,310,154);
   body+=`<path d="M ${M+220} ${y+77} H ${M+327}" stroke="${BLUE}" stroke-width="1.5" marker-end="url(#delivery-arrow)"/><path d="M ${M+660} ${y+77} H ${M+767}" stroke="${BLUE}" stroke-width="1.5" marker-end="url(#delivery-arrow)"/>`;
   body+=text(promotion.gates.map(g=>g.result?g.result.claim+' by '+g.result.authority+' at '+g.result.observedAt+' · '+g.freshness+' · '+g.revisionMatch:g.label+': external evidence UNKNOWN').join('; ')||'No external gate evidence. Promotion not executed by this figure.',M,y+183,W-2*M,11,1);bottom=y+194;shown++;
  });
 }
 if(!shown)body+=text('No eligible public declarations in this selected page. Missing publication or citation scope does not prove absence of deployment.',M,164,W-2*M,13,2);
 if(profile==='promotion'&&(omission.environments||omission.promotions)){bottom+=42;body+=text(`${omission.environments} public environment declarations and ${omission.promotions} promotion paths excluded here: missing public environment source citations. Matrix/release profiles retain author declarations.`,M,bottom,W-2*M,11,2);}
 const footer=bottom+34,height=footer+95,note='Declared links explain topology. Reviewed external claims retain dates; no health, rollout order, cause or executed approval is inferred.';
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${height}" viewBox="0 0 ${W} ${height}" role="img" aria-label="${xml(TITLE[profile])}" data-delivery-profile="${profile}"><title>${xml(p.title+' · '+TITLE[profile])}</title><desc>${xml(note)}</desc><defs><marker id="delivery-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="${BLUE}"/></marker></defs><rect width="100%" height="100%" fill="#f5f7fb"/><g font-family="Arial, Helvetica, sans-serif">${text(TITLE[profile],M,45,W-2*M,22,1,true)}${text(p.title+' · document revision '+p.revision+' · public projection',M,76,W-2*M,13,1)}${text('Captured '+at+' · evidence age policy '+maxAgeHours+' h · page '+(page+1)+' / '+totalPages+(profile==='environment'?' · environment page '+(environmentPage+1)+' / '+totalEnvironmentPages:''),M,104,W-2*M,11,1)}${body}${text(note,M,footer,W-2*M,12,2)}${text('UNKNOWN is not undeployed. NOT APPLICABLE is an explicit authored exclusion. SOURCE SHA ≠ BUILD ≠ ARTIFACT ≠ RELEASE.',M,footer+44,W-2*M,10,2)}</g></svg>`;
 return {svg,profile,page,totalPages,environmentPage,totalEnvironmentPages,shown,total,at,maxAgeHours,omission};
}
export function deliverySvg(input:Project,profile:DeliveryProfile,options:DeliveryFigureOptions={}){return deliveryFigure(input,profile,options).svg;}
/** Offline publication of all paged delivery figures. Contains only the public projection and escaped labels. */
export function deliveryHtml(input:Project,options:DeliveryFigureOptions={}){
 const p=publicDocument(validateDocument(input)),at=options.at??new Date().toISOString(),figures:string[]=[];
 for(const profile of DELIVERY_PROFILES){const first=deliveryFigure(p,profile,{...options,at,page:0,environmentPage:0});if(figures.length+first.totalPages*first.totalEnvironmentPages>300)throw new Error('Delivery publication exceeds 300 figures; select a narrower public scope');for(let ep=0;ep<first.totalEnvironmentPages;ep++)for(let page=0;page<first.totalPages;page++)figures.push(`<section>${deliverySvg(p,profile,{...options,at,page,environmentPage:ep})}</section>`);}
 if(figures.length>300)throw new Error('Delivery publication exceeds 300 figures; select a narrower public scope');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>${xml(p.title)} · Delivery figures</title><style>body{font:16px/1.6 Arial,sans-serif;margin:0;color:#20344f}main{padding:24px;max-width:1280px;margin:auto}section{overflow:auto;margin:24px 0;break-inside:avoid}svg{width:1152px;max-width:none;height:auto}@media print{main{padding:0}svg{width:100%;}section{overflow:visible;break-before:page}}</style></head><body><main><h1>${xml(p.title)} · Delivery figures</h1><p>Public, offline publication. Declared topology and dated reviewed evidence remain separate. No tests or promotions were executed.</p>${figures.join('')}</main></body></html>`;
}
