import type {EvidenceBlock,Project} from '../../core/model';
import {designContext,eyebrowOf,footerParts,type DesignContext,type DesignOptions} from './context';
import {summaryCards} from './architecture';
import {clipMono,footerLine,header,legendStrip,lines,monoWidth,MONO,sansLines,svgDocument,txt} from './kit';
import {xml} from '../diagram';
type Table=Extract<EvidenceBlock,{type:'table'}>;
const M=48,MAX_ROWS=8;
const precise=(n:number)=>String(Math.round(n*1000)/1000);
/** A single supplied numeric column. No sums between different columns/units. */
export function waterfallTable(c:DesignContext):{block:Table;column:number;category:number;numeric:number[];incrementLabel:boolean}|undefined{
 for(const id of c.spec.nodes.flatMap(n=>n.evidenceRefs)){const b=c.doc.blocks.find(b=>b.id===id);if(!b||b.type!=='table'||!b.rows.length)continue;const numeric=b.columns.flatMap((_,k)=>b.rows.every(r=>r[k]===null||typeof r[k]==='number')&&b.rows.some(r=>typeof r[k]==='number')?[k]:[]);if(!numeric.length)continue;const named=numeric.find(k=>/\b(?:delta|increment|change|contribution|difference)\b/i.test(b.columns[k])),column=named??numeric[0],category=b.columns.findIndex((_,k)=>!numeric.includes(k));return {block:b,column,category,numeric,incrementLabel:named!==undefined};}return undefined;
}
/** Running sums are derived from the displayed signed values in table order.
 * Null is missing, never a zero. Non-finite derived arithmetic refuses the plot. */
export function waterfallValues(found:NonNullable<ReturnType<typeof waterfallTable>>){let cumulative=0;const rows=found.block.rows.slice(0,MAX_ROWS).map((row,index)=>{const value=typeof row[found.column]==='number'?row[found.column] as number:null,start=cumulative;if(value!==null)cumulative+=value;return {index,label:found.category>=0?String(row[found.category]??index+1):'Row '+(index+1),value,start,end:cumulative};});return {rows,finite:rows.every(r=>Number.isFinite(r.start)&&Number.isFinite(r.end)),omitted:found.block.rows.length-rows.length,missing:rows.filter(r=>r.value===null).length};}
const PROVENANCE:Record<EvidenceBlock['provenance'],string>={synthetic:'SYNTHETIC DATA', 'source-derived':'SOURCE-DERIVED', reference:'REFERENCE DATA',author:'AUTHOR-PROVIDED'};
const fmt=(v:number)=>Math.abs(v)>=1e6?Number(v.toPrecision(3)).toExponential(1):String(+v.toFixed(2));
export function waterfallSvg(input:Project,viewId:string,options:DesignOptions={}):string{
 const c=designContext(input,viewId,'waterfall',options),{spec,t}=c,found=waterfallTable(c),values=found?waterfallValues(found):undefined,contentW=960;
 const hdr=header(eyebrowOf(c,'Waterfall'),found?found.block.title:spec.title,found?`Supplied signed ${found.block.columns[found.column]} values, accumulated in table order from zero.`:'No public numeric table supports this figure. Attach supplied signed increments; no values are invented.',M,M,contentW,t,c.editorial),out:string[]=[];let bottom=M+hdr.height+24;
 if(found&&values){const top=M+hdr.height+28,tag=PROVENANCE[found.block.provenance],tw=Math.ceil(monoWidth(tag,8,.12))+14,note=found.block.provenance==='synthetic'?'Illustrative values, not measured or verified.':'Supplied values retain their evidence provenance; not independently verified.',noteLs=sansLines(note,contentW-tw-10,10,2);
  out.push(`<g data-provenance="${found.block.provenance}"><rect x="${M}" y="${top}" width="${tw}" height="16" rx="2" fill="${t.accentTint}" stroke="${t.accent}"/>${txt(tag,M+7,top+11.5,{size:8,fill:t.accent,font:MONO,tracking:.12})}${lines(noteLs,M+tw+10,top+12,13,{size:10,fill:t.muted,italic:true})}</g>`);
  if(values.finite){const nums=[0,...values.rows.flatMap(r=>[r.start,r.end])],magnitude=Math.max(1,...nums.map(Math.abs)),low=Math.min(...nums)/magnitude,high=Math.max(...nums)/magnitude,lo=low===high?-1:low,hi=low===high?1:high,px=M+56,pw=contentW-56,py=top+28+noteLs.length*13,ph=200,Y=(v:number)=>py+ph-(v/magnitude-lo)/(hi-lo)*ph,slot=pw/values.rows.length,bw=Math.min(48,slot-16);
   out.push(`<g data-waterfall-plot="" data-scale-magnitude="${magnitude}" data-scale-low="${lo}" data-scale-high="${hi}" data-plot-y="${py}" data-plot-height="${ph}">`);
   for(let i=0;i<=4;i++){const normalized=lo+(hi-lo)*i/4,y=Y(normalized*magnitude);out.push(`<line x1="${px}" y1="${precise(y)}" x2="${px+pw}" y2="${precise(y)}" stroke="${t.rule}"/>`,txt(fmt(normalized*magnitude),px-8,y+3,{size:11,fill:t.soft,font:MONO,anchor:'end'}));}
   out.push(`<line data-waterfall-zero="" x1="${px}" y1="${precise(Y(0))}" x2="${px+pw}" y2="${precise(Y(0))}" stroke="${t.ruleSolid}"/>`);
   values.rows.forEach(r=>{const x=px+r.index*slot+(slot-bw)/2;if(r.value!==null){const y=Math.min(Y(r.start),Y(r.end)),h=Math.max(.5,Math.abs(Y(r.end)-Y(r.start)));out.push(`<rect data-waterfall-row="${r.index}" data-delta="${r.value}" data-start="${r.start}" data-end="${r.end}" x="${precise(x)}" y="${precise(y)}" width="${precise(bw)}" height="${precise(h)}" fill="${r.value<0?t.muted:t.accent}" fill-opacity="0.85"><title>${xml(r.label+' · '+found.block.columns[found.column]+': '+r.value+'; derived sum '+r.start+' → '+r.end)}</title></rect>`);if(r.index<values.rows.length-1)out.push(`<line data-waterfall-connector="${r.index}" x1="${precise(x+bw)}" y1="${precise(Y(r.end))}" x2="${precise(px+(r.index+1)*slot+(slot-bw)/2)}" y2="${precise(Y(r.end))}" stroke="${t.ruleSolid}" stroke-dasharray="3,3"/>`);}else out.push(txt('—',x+bw/2,Y(0)-8,{size:8,fill:t.soft,font:MONO,anchor:'middle'}));out.push(txt(clipMono((monoWidth(r.label,11)>slot-6?'['+(r.index+1)+'] ':'')+r.label,slot-6,11),px+(r.index+.5)*slot,py+ph+18,{size:11,fill:t.muted,font:MONO,anchor:'middle'}),txt(r.value===null?'Missing':(r.value>0?'+':'')+fmt(r.value),px+(r.index+.5)*slot,py+ph+36,{size:11,fill:t.ink,font:MONO,anchor:'middle'}));});out.push('</g>');bottom=py+ph+54;
  }else{out.push(lines(sansLines('Derived sum exceeds finite numeric limits: no bars drawn. Supply bounded signed increments.',contentW,11,2),M,top+48,16,{size:11,fill:t.muted}));bottom=top+88;}
  const notes=['Running sums are derived arithmetic over shown numeric increments, not supplied observed totals, causal effects or timing.','Only '+found.block.columns[found.column]+' is accumulated; other numeric columns are not summed together.',...(values.rows.some(r=>monoWidth(r.label,11)>(contentW-56)/values.rows.length-6)?['Long labels are shortened and keyed by their source row number; full labels remain in the source table.']:[]),...(!found.incrementLabel?['This chosen figure interprets the selected numeric column as increments; the source does not explicitly label them as deltas.']:[]),...(values.missing?[values.missing+' missing value(s) shown as gaps, excluded from the partial derived sum; never replaced with zero.']:[]),...(values.omitted?[values.omitted+' further source row(s) not drawn or included in the displayed running sum (8-row readability limit; the full source table is retained in evidence).']:[])];
  for(const note of notes){const ls=sansLines(note,contentW,10,3);out.push(lines(ls,M,bottom+12,14,{size:10,fill:t.muted,italic:true}));bottom+=ls.length*14+6;}
  const legend=legendStrip([{kind:'swatch',fill:t.accent,label:'Positive/zero increment'},{kind:'swatch',fill:t.muted,label:'Negative increment'},{kind:'line',stroke:'muted',dashed:true,label:'Derived sum connector'}],M,bottom+12,contentW,t);out.push(legend.svg);bottom+=legend.height+20;const sources=found.block.sourceIds.map(id=>c.doc.sources.find(s=>s.id===id)?.title).filter(Boolean);if(sources.length){out.push(lines(sansLines('Sources: '+sources.join('; '),contentW,10,2),M,bottom+12,14,{size:10,fill:t.muted}));bottom+=34;}
 }else{const ls=sansLines('No supplied increments available. Attach a public table to an existing component, then choose the column interpretation for this presentation. No bars or running sums have been invented.',contentW-32,11,4);out.push(`<g data-dd-empty=""><rect x="${M}" y="${bottom}" width="${contentW}" height="${ls.length*16+28}" rx="6" fill="${t.paper2}" stroke="${t.rule}"/>${lines(ls,M+16,bottom+22,16,{size:11,fill:t.muted})}</g>`);bottom+=ls.length*16+40;}
 let y=bottom+12;const cards=c.editorial?summaryCards(c,M,y+8,contentW):undefined;if(cards)y+=cards.height+24;return svgDocument({slug:c.slug,width:contentW+2*M,height:y+M,title:(found?.block.title??spec.title)+' · waterfall',desc:'Public supplied signed increments in table order; cumulative sums are derived, not observed totals. '+(found?PROVENANCE[found.block.provenance]:'No numeric evidence.'),t,theme:c.theme,type:'waterfall',viewId:spec.viewId,defs:'',body:hdr.svg+out.join('')+(cards?.svg??'')+footerLine(footerParts(c),M,y+12,contentW,t)});
}
