import {clone,validateDocument,type Project,type ProjectView} from './model';
export function positionFor(view:ProjectView,nodeId:string){const i=Math.max(0,view.nodeIds.indexOf(nodeId));return view.positions[nodeId]??{x:(i%3)*290,y:Math.floor(i/3)*170};}
export function traceNodes(doc:Project,viewId:string,start:string,direction:'upstream'|'downstream'):Set<string>{const view=doc.views.find(v=>v.id===viewId),edges=doc.edges.filter(e=>view?.edgeIds.includes(e.id)),seen=new Set([start]),queue=[start];while(queue.length){const current=queue.shift();for(const e of edges){const next=direction==='downstream'?(e.source===current?e.target:null):(e.target===current?e.source:null);if(next&&!seen.has(next)){seen.add(next);queue.push(next);}}}return seen;}
export function pathToView(doc:Project,target:string):string[]{function visit(viewId:string,path:string[]):string[]|null{if(viewId===target)return[...path,viewId];if(path.includes(viewId))return null;const v=doc.views.find(v=>v.id===viewId);for(const n of doc.nodes.filter(n=>v?.nodeIds.includes(n.id)))if(n.childViewId){const result=visit(n.childViewId,[...path,viewId]);if(result)return result;}return null;}return visit(doc.rootViewId,[])??[target];}
export function removeNode(input:Project,nodeId:string):Project{const d=clone(input),removedEdges=new Set(d.edges.filter(e=>e.source===nodeId||e.target===nodeId).map(e=>e.id));d.nodes=d.nodes.filter(n=>n.id!==nodeId);d.edges=d.edges.filter(e=>!removedEdges.has(e.id));for(const v of d.views){v.nodeIds=v.nodeIds.filter(id=>id!==nodeId);v.edgeIds=v.edgeIds.filter(id=>!removedEdges.has(id));delete v.positions[nodeId];}d.story=d.story.filter(s=>s.nodeId!==nodeId).map(s=>({...s,highlightEdgeIds:s.highlightEdgeIds.filter(id=>!removedEdges.has(id))}));return validateDocument(d);}
/** Remove private and unreachable content, rather than hiding it with CSS. */
export function publicDocument(input:Project):Project{
 const d=clone(input);delete d.privateNotes;
 const publicViews=new Set(d.views.filter(v=>v.visibility==='public').map(v=>v.id)),keptViews=new Set<string>(),keptNodes=new Set<string>();
 function walk(viewId:string){if(keptViews.has(viewId)||!publicViews.has(viewId))return;keptViews.add(viewId);const v=d.views.find(v=>v.id===viewId)!;for(const n of d.nodes.filter(n=>n.visibility==='public'&&v.nodeIds.includes(n.id))){keptNodes.add(n.id);if(n.childViewId)walk(n.childViewId);}}
 walk(d.rootViewId);d.nodes=d.nodes.filter(n=>keptNodes.has(n.id));for(const n of d.nodes)if(n.childViewId&&!keptViews.has(n.childViewId))delete n.childViewId;
 d.views=d.views.filter(v=>keptViews.has(v.id));const membership=new Set(d.views.flatMap(v=>v.edgeIds));d.edges=d.edges.filter(e=>e.visibility==='public'&&keptNodes.has(e.source)&&keptNodes.has(e.target)&&membership.has(e.id));const edges=new Set(d.edges.map(e=>e.id));
 for(const v of d.views){v.nodeIds=v.nodeIds.filter(id=>keptNodes.has(id));v.edgeIds=v.edgeIds.filter(id=>edges.has(id));v.positions=Object.fromEntries(Object.entries(v.positions).filter(([id])=>v.nodeIds.includes(id)));}
 const blockRefs=new Set(d.nodes.flatMap(n=>n.blockIds)),publicAssets=new Set(d.assets.filter(a=>a.visibility==='public').map(a=>a.id));d.blocks=d.blocks.filter(b=>b.visibility==='public'&&blockRefs.has(b.id)&&(b.type!=='image'||publicAssets.has(b.assetId)));
 const blocks=new Set(d.blocks.map(b=>b.id));d.nodes.forEach(n=>n.blockIds=n.blockIds.filter(id=>blocks.has(id)));const assetRefs=new Set(d.blocks.flatMap(b=>b.type==='image'?[b.assetId]:[]));d.assets=d.assets.filter(a=>assetRefs.has(a.id));
 const sourceRefs=new Set([...d.nodes.flatMap(n=>n.sourceIds),...d.blocks.flatMap(b=>b.sourceIds)]);d.sources=d.sources.filter(s=>s.visibility==='public'&&sourceRefs.has(s.id));const sources=new Set(d.sources.map(s=>s.id));[...d.nodes,...d.blocks].forEach(item=>item.sourceIds=item.sourceIds.filter(id=>sources.has(id)));
 d.story=d.story.filter(s=>keptViews.has(s.viewId)&&(!s.nodeId||keptNodes.has(s.nodeId))).map(s=>({...s,highlightEdgeIds:s.highlightEdgeIds.filter(id=>edges.has(id))}));return validateDocument(d);
}
export type History={past:Project[];present:Project;future:Project[]};
export function commitHistory(h:History,input:Project):History{return{past:[...h.past,h.present].slice(-25),present:validateDocument({...input,revision:h.present.revision+1}),future:[]};}
export function undo(h:History):History{return h.past.length?{past:h.past.slice(0,-1),present:h.past[h.past.length-1],future:[h.present,...h.future]}:h;}
export function redo(h:History):History{return h.future.length?{past:[...h.past,h.present],present:h.future[0],future:h.future.slice(1)}:h;}
