/** Qualify the delivery bundles outside this repository and its node_modules.
 * All inputs are synthetic. Output is an immutable, explicitly named directory. */
import {execFileSync,spawnSync} from 'node:child_process';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {bundleClients} from './lib/bundleClients';
import {documentSchema} from '../src/core/model';
import {analysisProfile} from '../src/intelligence/profile';
import {documentFromAtlas,validateManifest} from '../src/core/atlas';
const at=process.argv.indexOf('--out');if(at<0||!process.argv[at+1])throw new Error('--out <new-directory> required');
const out=resolve(process.argv[at+1]);mkdirSync(out);const isolated=mkdtempSync(join(tmpdir(),'diagramcloud-bundle-qualification-')),clients=join(isolated,'cli');
const grammars=await bundleClients(clients),cli=join(clients,'intelligence.mjs'),results:{id:string;status:'PASS'}[]=[];
const sourceSha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty=!!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),commit='a'.repeat(40);
const project=documentSchema.parse({schemaVersion:1,id:'synthetic-qualification',title:'Synthetic client qualification',privateNotes:'PRIVATE_BUNDLE_SENTINEL',rootViewId:'root',nodes:[{id:'api',label:'Synthetic API',basis:'static-source',sourceIds:['source']},{id:'data',label:'Synthetic data',basis:'planned'}],edges:[{id:'link',source:'api',target:'data',basis:'static-source'}],views:[{id:'root',title:'Synthetic system',nodeIds:['api','data'],edgeIds:['link'],positions:{api:{x:0,y:0},data:{x:300,y:0}}}],sources:[{id:'source',title:'Synthetic source',location:'README.md:1',visibility:'public'}]});
const write=(name:string,input:unknown)=>{const p=join(isolated,name+'.json');writeFileSync(p,JSON.stringify(input),{flag:'wx'});return p;};const projectPath=write('project',project);
const run=(mode:string,input:string,flags:string[]=[],name=mode)=>{const r=spawnSync(process.execPath,[cli,mode,'--input',input,'--out',join(out,name),...flags],{cwd:isolated,encoding:'utf8',env:{...process.env,NODE_PATH:''},timeout:60000});if(r.status!==0)throw new Error(mode+': '+r.stderr);results.push({id:'cli-'+name,status:'PASS'});};
const fixture=(name:string)=>resolve('examples/product-campaign/'+name+'.json');
run('graph',fixture('graph-1'),[],'graph-one');run('graph',fixture('graph-2'),['--current',join(out,'graph-one/project.candidate.json')],'graph-reimport');
run('brief',fixture('project-brief'));run('analyze',fixture('native-artifacts'),['--repository-id','repo','--revision',commit]);run('delivery',fixture('delivery-brief'),['--current',join(out,'brief/project.candidate.json')]);
run('inspect',projectPath);run('query',projectPath);run('evolution',projectPath,['--current',projectPath]);
const documents=[{path:'README.md',text:'# Synthetic source\nSee [table](source.csv).'},{path:'source.csv',text:'id,title\nitem,Synthetic input'}];run('docs',write('documents',documents));
run('profile',write('profile',{depth:'deep',overrides:{purpose:'education'}}));
const profile=analysisProfile('deep',{analyzers:['documents','tree-sitter']});run('bundle',write('bundle-input',{files:documents,repositoryId:'repo',revision:commit,profile}));
run('deep',write('deep-input',{files:[{path:'main.ts',text:'export function syntheticWork(value:number){return value + 1;}'}],repositoryId:'repo',revision:commit,profile}));
const deep=JSON.parse(readFileSync(join(out,'deep/analysis-bundle.private.json'),'utf8'));if(!deep.items.some((i:{kind:string})=>i.kind==='function-declaration'))throw new Error('Bundled local WASM did not return a symbol');
const requested={id:'synthetic-spec',repositories:[{id:'repo',repository:'owner/synthetic',commit}],checks:[{id:'test',nodeId:'api',edgeId:'link',repositoryId:'repo',question:'Synthetic requested check',expected:'Exact selected commit',kind:'test'}]};
run('verification-spec',write('requested',requested),['--current',projectPath]);
const receipt={schema_version:1,receipt_id:'synthetic-external-fixture',subject:{schema_version:1,entity_id:'synthetic:release',owner_app:'external-ci',entity_type:'release',local_id:'synthetic'},app_id:'external-ci',product_version:'1.0',document_schema_version:1,galaxy_level:'G0',revision:{vcs:'git',repository:'owner/synthetic',commit,dirty:false},verification_level:'DECLARED',status:'passed',checks:[{check_id:'test',status:'passed',evidence_ref_ids:['check-evidence']}],evidence_refs:[{schema_version:1,evidence_id:'check-evidence',kind:'test_run',source_system:'ci',locator:{run_id:'synthetic'},captured_at:'2026-10-09T00:00:00Z',observed_revision:commit,visibility:'private',synthetic:false,review_state:'unreviewed'}],created_at:'2026-10-09T00:00:00Z',caveats:['Synthetic protocol test input; never release evidence.']};
run('verification-receipt',write('receipt',receipt),['--current',projectPath,'--spec',join(out,'verification-spec/verification-spec.proposed.json'),'--runner','Synthetic runner','--run-id','synthetic']);
const now=new Date(),cockpit={format:'diagramcloud.cockpit-snapshot',version:1,id:'synthetic-cockpit',sourceApp:'synthetic-host',authority:'Synthetic host fixture',capturedAt:now.toISOString(),expiresAt:new Date(now.getTime()+3600000).toISOString(),permission:{selectedProjectId:project.id,dataAccessGranted:true,scope:'selected-project'},observations:[{id:'synthetic-host-claim',nodeId:'api',sourceRevision:commit,summary:'Synthetic host snapshot',claim:'partial'}]};run('cockpit',write('cockpit',cockpit),['--current',projectPath]);
const sources={source:'Synthetic candidate runs a job.'},proposal={format:'diagramcloud.entity-proposal',version:1,projectId:project.id,baseRevision:project.revision,entities:[{id:'candidate',label:'Synthetic candidate',kind:'process',citations:[{sourceId:'source',line:1,endLine:1,quote:sources.source}]}],relations:[]};run('entity-proposal',write('entities',proposal),['--current',projectPath,'--sources',write('sources',sources)]);
const atlas=documentFromAtlas(validateManifest({format:'diagramcloud.project-manifest',version:1,project:{id:'synthetic-atlas',title:'Synthetic atlas'},repositories:[{id:'repo',title:'Synthetic repository',host:'local',locator:'synthetic'}]})).document;run('cross-repository',write('analyses',[]),['--current',write('atlas',atlas)]);
run('publication',projectPath,['--views','root','--title','Synthetic frozen publication']);
const calls=[['diagramcloud_query',{kind:'summary'}],['diagramcloud_render',{kind:'quality',viewId:'root'}],['diagramcloud_propose_design',{format:'diagramcloud.design-brief',version:1,projectId:project.id,views:[{viewId:'root',type:'architecture'}]}],['diagramcloud_verification_spec',requested],['diagramcloud_propose_project',JSON.parse(readFileSync(fixture('project-brief'),'utf8'))],['diagramcloud_propose_publication',{title:'Synthetic publication',viewIds:['root'],profile:'blueprint'}],['diagramcloud_propose_entities',{proposal,selectedSources:sources}]] as const;
for(const selected of [false,true]){const requests=[{jsonrpc:'2.0',id:1,method:'initialize'},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/list'},...calls.map(([name,arguments_],i)=>({jsonrpc:'2.0',id:i+3,method:'tools/call',params:{name,arguments:arguments_}})),...(selected?[{jsonrpc:'2.0',id:20,method:'tools/call',params:{name:'diagramcloud_query_analysis',arguments:{kind:'summary'}}}]:[])];
 const r=spawnSync(process.execPath,[join(clients,'intelligence-mcp.mjs'),projectPath,...(selected?['--analysis',join(out,'deep/analysis-bundle.private.json')]:[])],{cwd:isolated,encoding:'utf8',env:{...process.env,NODE_PATH:''},input:requests.map(v=>JSON.stringify(v)).join('\n')+'\n',timeout:30000,maxBuffer:4*1024*1024});if(r.status!==0)throw new Error('MCP startup: '+r.stderr);const rows=r.stdout.trim().split('\n').map(s=>JSON.parse(s));if(rows.some(r=>r.error||r.result?.isError))throw new Error('MCP request failed: '+JSON.stringify(rows.filter(r=>r.error||r.result?.isError)));if(rows.find(r=>r.id===2)?.result.tools.length!==(selected?8:7))throw new Error('MCP selection/catalog mismatch');if(r.stdout.includes('PRIVATE_BUNDLE_SENTINEL'))throw new Error('Private Project leaked through MCP');results.push({id:selected?'mcp-selected-analysis':'mcp-public-seven-tools',status:'PASS'});
}
writeFileSync(join(out,'receipt.json'),JSON.stringify({format:'diagramcloud.bundled-client-qualification/1',sourceSha,sourceWorktreeDirty:dirty,hostRuntime:process.version,syntheticInputs:true,bundleOutsideRepository:true,isolatedFromProjectNodeModules:true,withoutNodePath:true,grammars,results},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({checks:results.length,status:'PASS',receipt:join(out,'receipt.json')}));
