import type {ScanFile} from './scanner';
export type GitBoundary={path:string;kind:'submodule'|'worktree'|'git-boundary';metadataOnly:true;evidence:{file:string;line:number;finding:string}[]};
export const VENDOR_PATH=/(^|\/)(node_modules|vendor|\.venv|venv|site-packages)(\/|$)/i;
export const GENERATED_PATH=/(^|\/)(dist|build|out|coverage|target|bin|obj|\.next|\.nuxt|\.cache|test-results|playwright-report)(\/|$)|(?:\.generated|\.g)\.(?:cs|ts|js)$|(?:^|\/)generated(?:\/|$)/i;
export const GENERATED_HEADER=/(?:<auto-generated>|@generated\b|Code generated .* DO NOT EDIT|This file (?:is|was) (?:automatically )?generated)/i;
const safe=(p:string)=>p.length<=512&&!/^(?:\/|[a-z]:)/i.test(p)&&!/[\\\u0000-\u001f]/.test(p)&&!p.split('/').some(x=>!x||x==='.'||x==='..');
/** Path-only boundary facts. A .git marker does not establish clone versus
 * worktree: no gitdir target is followed and no nested repository content read. */
export function gitBoundaries(paths:string[],modules?:ScanFile,markers:ScanFile[]=[]):GitBoundary[]{
 const result=new Map<string,GitBoundary>();for(const p of paths){const m=/^(.+?)\/\.git(?:\/|$)/.exec(p);if(m&&safe(m[1]))result.set(m[1],{path:m[1],kind:'git-boundary',metadataOnly:true,evidence:[{file:p.endsWith('/.git')?p:m[1]+'/.git',line:1,finding:'Nested .git marker metadata; clone/worktree/submodule type unknown. Contents below this boundary excluded.'}]});}
 if(modules){const lines=modules.text.split(/\r?\n/);for(let i=0;i<lines.length;i++){const m=/^\s*path\s*=\s*(.+?)\s*$/.exec(lines[i]);if(!m||!safe(m[1]))continue;const old=result.get(m[1]);result.set(m[1],{path:m[1],kind:'submodule',metadataOnly:true,evidence:[...(old?.evidence??[]),{file:modules.path,line:i+1,finding:'Explicit .gitmodules path declaration; submodule source is independently scoped and not scanned here.'}]});}}
 for(const marker of markers){const path=marker.path.replace(/\/\.git$/,'');if(!safe(path)||!result.has(path))continue;const reference=/^gitdir:\s*(.+)\s*$/m.exec(marker.text.slice(0,2048))?.[1].replace(/\\/g,'/');const kind=reference&&/(?:^|\/)\.git\/worktrees\//.test(reference)?'worktree':reference&&/(?:^|\/)\.git\/modules\//.test(reference)?'submodule':undefined;if(kind){const row=result.get(path)!;row.kind=kind;row.evidence.push({file:marker.path,line:1,finding:'gitdir metadata identifies a '+kind+' boundary. Pointer value is omitted and never followed.'});}}
 return [...result.values()].sort((a,b)=>a.path.localeCompare(b.path)).slice(0,200);
}
