import {documentSchema} from '../../src/core/model';
import {previewDeliveryBrief,deliveryPublicationPatch} from '../../src/intelligence/delivery';
import {applyDocumentPatch} from '../../src/core/patch';
export function syntheticDeliveryProject(){
 const seed=documentSchema.parse({schemaVersion:1,id:'synthetic-delivery-figures',title:'Synthetic delivery figures',rootViewId:'root',nodes:[{id:'api',label:'Synthetic API',icon:'generic-api'},{id:'data',label:'Synthetic data',icon:'generic-storage'}],edges:[],views:[{id:'root',title:'Synthetic system',nodeIds:['api','data'],edgeIds:[],positions:{api:{x:0,y:0},data:{x:300,y:0}}}],sources:[{id:'source',title:'Synthetic source',location:'fixtures/declared.ts:8 @ source-revision-1',visibility:'private'}]});
 const doc=previewDeliveryBrief(seed,{format:'diagramcloud.delivery-brief',version:1,projectId:seed.id,baseRevision:seed.revision,delivery:{environments:[{id:'dev',label:'Synthetic development',role:'preview',sourceIds:['source'],bindings:[{kind:'tenant',label:'PRIVATE_TENANT_DECLARATION',sourceIds:['source']}]},{id:'prod',label:'Synthetic production',sourceIds:['source']}],artifacts:[{id:'artifact',label:'Synthetic artifact',version:'artifact-version-7',sourceRevision:'source-revision-1',sourceRepositoryId:'standalone-source',buildId:'build-run-42',digest:'sha256:'+'a'.repeat(64),sourceIds:['source']}],releases:[{id:'release',label:'release-label-9',artifactIds:['artifact'],sourceIds:['source']}],instances:[{id:'api-dev',nodeId:'instance-dev',componentId:'api',environmentId:'dev',artifactId:'artifact',releaseId:'release',declaredRevision:'source-revision-1',sourceIds:['source']},{id:'api-prod',nodeId:'instance-prod',componentId:'api',environmentId:'prod',artifactId:'artifact',releaseId:'release',declaredRevision:'source-revision-2',sourceIds:['source']}],promotions:[{id:'promotion',fromEnvironmentId:'dev',toEnvironmentId:'prod',artifactId:'artifact',releaseId:'release',gates:[{id:'review',label:'Synthetic human approval gate'}],sourceIds:['source']}],applicability:[{id:'not-applicable',componentId:'data',environmentId:'prod',state:'not-applicable',reason:'Explicit synthetic author exclusion',sourceIds:['source']}],configurations:[{id:'private-config',componentId:'api',environmentId:'dev',kind:'configuration',name:'PRIVATE_CONFIG_DECLARATION',valueState:'unknown',sourceIds:[]}]}}).document;
 return doc;
}
export function publicSyntheticDeliveryProject(){let doc=syntheticDeliveryProject();for(const [kind,id] of [['instances','api-dev'],['instances','api-prod'],['promotions','promotion'],['applicability','not-applicable']] as const)doc=applyDocumentPatch(doc,deliveryPublicationPatch(doc,kind,id,'public',true)).result;return doc;}
